### ISSUE TITLE
aircast very high cpu usage while streaming.

### ISSUE THREAD

**Issue by ralph-irving** [philippe44/AirConnect#1]
Hi Philippe, I'm really liking the new aircast bridge.  I've been using it the last couple days with a chromecast audio firmware 1.25.90308 with great success.  I noticed that the aircast-x86 build consistantly spins a cpu near 100% usage while streaming from an ipad 10.3.3 or itunes 12.6.2.  I suspect there's a spinning loop causing this issue, but I haven't been able to track it down.

13351 squeezeb  20   0 73396 3784 1924 S  95.6  0.0   0:38.43 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 100.1  0.0   0:39.61 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S  95.7  0.0   0:40.78 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 101.1  0.0   0:41.97 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 101.0  0.0   0:43.14 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 100.1  0.0   0:44.32 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 101.2  0.0   0:45.50 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 102.0  0.0   0:46.67 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 100.1  0.0   0:47.85 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S  94.6  0.0   0:49.02 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 100.2  0.0   0:50.21 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S  93.9  0.0   0:51.38 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S  88.8  0.0   0:52.55 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 100.1  0.0   0:53.73 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S 101.0  0.0   0:54.91 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S  93.6  0.0   0:56.07 aircast-x86
13351 squeezeb  20   0 73396 3784 1924 S  93.9  0.0   0:57.25 aircast-x86

CPU usage doesn't even register in vmstat when idle.

13351 squeezeb  20   0 73396 3876 2004 S   0.0  0.0   9:28.63 aircast-x86
13351 squeezeb  20   0 73396 3876 2004 S   0.0  0.0   9:28.63 aircast-x86
13351 squeezeb  20   0 73396 3876 2004 S   0.0  0.0   9:28.63 aircast-x86
13351 squeezeb  20   0 73396 3876 2004 S   0.0  0.0   9:28.63 aircast-x86
13351 squeezeb  20   0 73396 3876 2004 S   0.0  0.0   9:28.63 aircast-x86

Ideas?

Thanks,
Ralphy.

**Comment by philippe44** [comment]
Hi Ralphy - Good to hear from you again! Thanks for pointing out that problem. It's a bug I introduce while I was doing a better handling of network connection problems (like choppy networks). It's corrected now

**Comment by ralph-irving** [comment]
Thanks for the quick fix...much better now.  It's great to be able to use the chromecast with most of our ios app with a bridge that doesn't rely on LMS.  Works great with iPeng's airplay support...the best of both worlds!  Thanks again.

20835 squeezeb  20   0 47224 1624 1276 S   0.0  0.0   0:00.15 aircast-x86
20835 squeezeb  20   0 47224 1624 1276 S   0.0  0.0   0:00.15 aircast-x86
20835 squeezeb  20   0 73396 3764 1920 S  12.5  0.0   0:00.20 aircast-x86
20835 squeezeb  20   0 73396 3764 1920 S   6.2  0.0   0:00.22 aircast-x86
20835 squeezeb  20   0 73396 3764 1920 S   0.0  0.0   0:00.25 aircast-x86
20835 squeezeb  20   0 73396 3764 1920 S   6.3  0.0   0:00.30 aircast-x86
20835 squeezeb  20   0 73396 3764 1920 S   0.0  0.0   0:00.33 aircast-x86
20835 squeezeb  20   0 73396 3764 1920 S   6.4  0.0   0:00.37 aircast-x86
20835 squeezeb  20   0 73396 3764 1920 S   0.0  0.0   0:00.41 aircast-x86
20835 squeezeb  20   0 73396 3764 1920 S   6.2  0.0   0:00.45 aircast-x86
20835 squeezeb  20   0 73396 3764 1920 S   6.2  0.0   0:00.48 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:00.51 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   6.3  0.0   0:00.55 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   6.3  0.0   0:00.59 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   6.3  0.0   0:00.62 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   6.2  0.0   0:00.66 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:00.69 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:00.73 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   6.3  0.0   0:00.77 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   6.2  0.0   0:00.81 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:00.84 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:00.87 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   6.2  0.0   0:00.91 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:00.95 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:00.98 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:01.02 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:01.05 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   6.3  0.0   0:01.10 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   0.0  0.0   0:01.13 aircast-x86
20835 squeezeb  20   0 73396 3772 1920 S   6.3  0.0   0:01.17 aircast-x86

**Comment by philippe44** [comment]
Thanks - BTW, one thing you could help me with is visibility for these new apps. As usual, it's free apps but my "reward" is to have them as widely use as possible and I don't know exactly where I should promote these (AirCast & AirUPnP). Any idea?

**Comment by ralph-irving** [comment]
That's a tough one, no I haven't any idea.  I don't have any projects outside of LMS.  I only use the slimdevices forums to get the word out of new builds and even that isn't very useful these days.  I recently updated squeezeplay and squeezelite with linux pulseaudio support instead of ALSA but in the month since I announced it I've only had a handful of downloads.  Perhaps, it's just because it's the summer.  Have to wait and see what happens in the fall.   Have you asked on the forums?  Perhaps some members have a marketing background and could suggest ways to promote them.

**Comment by philippe44** [comment]
Yes, same issues here :-(. Maybe we could share a blog or a wiki or any sort of site.

**Comment by ralph-irving** [comment]
That's a good idea.  We should start planning for the demise of forums.slimdevices.com.  I've maintained a wiki in the past, it was a lot of work.

**Comment by philippe44** [comment]
You probably have backgrounded the application without using the -Z option on its command line, no ?

**Comment by vicegold** [comment]
Yes, my fault. Sorry.

**Comment by philippe44** [comment]
no worries
