### ISSUE TITLE
How to uninstall Airconnect (Raspberry Pi)

### ISSUE THREAD

**Issue by patwinz** [philippe44/AirConnect#100]
Hi
With the recent Sonos update, Airplay 2 is now natively available and thus I rather like to remove AirConnect from my Raspberry Pi as the process "airupnp-arm" is extremly heavy on the CPU (spikes up to 100% every few seconds). Could you please update your readme file and include the uninstall routine? I did not manage to uninstall it properly and thus have to kill the airupnp-arm process after each reboot. 
Thanks.

**Comment by philippe44** [comment]
See updated README to disable the service. Having said that, it should not have such CPU spikes. Are you sure that you did not forget to add the -z parameter on the command line?

**Comment by philippe44** [comment]
Close for inactivity

**Comment by nmcc1212** [comment]
i was just about to uninstall becasuse of the high cpu usage, then realised i didnt use -z 🤦
