### ISSUE TITLE
package for automatic installation for Seagate Personal Cloud

### ISSUE THREAD

**Issue by Anglagard** [philippe44/AirConnect#101]
Is it possible to have a package for automatic installation for Seagate Personal Cloud ?
Best regards.

**Comment by philippe44** [comment]
I don't know what's inside such device or how to create a package

**Comment by Anglagard** [comment]
Here is the link : 
https://www.seagate.com/nasos/SDK/0.7/third-party/index.html
Hope it helps.

**Comment by philippe44** [comment]
It does but candiely I can't do that currently. My only adjustement variable is time, as all I do is for free. So I usually add features when I need them personally or when it's potentially used by a large number of people, which is not the case here, unfortunately. 
You probably can get somebody on https://www.upwork.com/ for a tiny amount of money

**Comment by Anglagard** [comment]
I have created a simple package for NAS OS (Seagate).
My KEF LS50 Wireless are now seen as Airplay devices.
Thank you very much.
Let me know if you want the package.

**Comment by philippe44** [comment]
Congrats! I'd be happy to put the package here to share with others

**Comment by philippe44** [comment]
I'll close that item, still happy to put the package here
