### ISSUE TITLE
update systemd example in readme

### ISSUE THREAD

**Issue by cactus** [philippe44/AirConnect#102]
I think the systemd example in the README could be updated slightly.

1. `Type=forking` can be omitted, if `-Z` is used and `-z` is left off. This leaves airupnp in the foreground, and lets systemd retain the context (without having to follow forking). It's just a bit cleaner.

2. `-f` can also be left off, as systemd should handle stdout/stderr log capture itself. The log output can later be viewed with `journalctl -u {name-of-service}`. In this case `journalctl -u airupnp.service`.

```
[Unit]
Description=AirUPnP bridge
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/var/lib/airconnect/airupnp -l 1000:2000 -Z -x /var/lib/airconnect/airupnp.xml
WorkingDirectory=/var/lib/airconnect/
Restart=on-failure
RestartSec=30
User=nobody
Group=nobody

[Install]
WantedBy=multi-user.target
```

**Comment by philippe44** [comment]
Thanks - I've updated the README
