### ISSUE TITLE
Allow us to choose network adapter

### ISSUE THREAD

**Issue by KilianB** [philippe44/AirConnect#103]
I encounter the same issue as described in #24 happening due to a second network adapter being present because of oracle virtual box. Once I disable the adapter air upnp launches sucessfuly. 

Can you please give us a command line parameter to choose the network adapter.

**Comment by philippe44** [comment]
I think it’s different - please read the readme and then use the command line options (-h). Your problem will be solved

**Comment by KilianB** [comment]
All that was needed. Thanks
