### ISSUE TITLE
OpenSSL 1.0.0 can't be found

### ISSUE THREAD

**Issue by seanchs** [philippe44/AirConnect#104]
I followed the instructions to install AirConnect on my Pi3. When I tried to install OpenSSL1.0.0 with the command: 
 wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb

I got following errors. Feels like the file couldn't be found. Please help: 

--2018-08-25 15:33:43--  http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb
Resolving security.debian.org (security.debian.org)... 128.61.240.73, 128.101.240.215, 128.31.0.63, ...
Connecting to security.debian.org (security.debian.org)|128.61.240.73|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-08-25 15:33:43 ERROR 404: Not Found.

Thanks,

Sean

**Comment by torange** [comment]
Use libssl1.0.0_1.0.1t-1+deb8u9_armhf.deb instead:

http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u9_armhf.deb

**Comment by philippe44** [comment]
README updated - thanks
