### ISSUE TITLE
Airplay to Chromecast (with no AppleTV)

### ISSUE THREAD

**Issue by FaserF** [philippe44/AirConnect#110]
Your Application works great on my Raspberry Pi. Thanks a lot for this. I can use your service to stream music to my google home.
But is it also possible to stream the display from an ios device to a chromecast anyway? On ios it says searching for AppleTV but doesnt display Chromecast+
So is it not possible right now?

**Comment by philippe44** [comment]
I'm not I understand the question. If you want to send whateer is displayed on your iOS device to CC, it's not what AirConnect is made for; It's audio only

**Comment by FaserF** [comment]
Thank you for your answer. That was my question if streaming other than audio (display) ist also possible.
