### ISSUE TITLE
AirPlay 2 Support

### ISSUE THREAD

**Issue by miked1313** [philippe44/AirConnect#114]
Is it possible to add AirPlay 2 support to AirConnect?

**Comment by philippe44** [comment]
AirPkay2 specification are still not available

**Comment by miked1313** [comment]
Ok thank you for the info.

**Comment by jolimk** [comment]
I have the same question now! is it possible?

**Comment by GEJEHA** [comment]
Philippe I just stated using your Airconnect on my DS and it works very good but having Airplay 2 would make it perfect. Is there a change that you can add Airplay 2 in the future?

**Comment by philippe44** [comment]
Very unlikely. AirPlay2 is undocumented and does not bring much for what AirConnect does

**Comment by rgallo** [comment]
https://9to5mac.com/2019/12/05/airplay-2-cracked/

It looks like some progress was made on this recently, any chance it could be reused and implemented?

**Comment by smilebasti** [comment]
Is there a new update to the Topic AirPlay 2?

**Comment by philippe44** [comment]
N, I don't have the intention to add AirPlay2

**Comment by joopjuh** [comment]
Is there a possibillity to stream to multiple speakers? As Airplay 1 didn't support this i'm guessing not?
Would be great if the intention changes in the future.

**Comment by pwt** [comment]
@joopjuh wrote:
> Is there a possibillity to stream to multiple speakers? As Airplay 1 didn't support this i'm guessing not?

Note that if you're using Sonos speakers you can just group them using the Sonos app, then use airupnp to stream to the master speaker. The audio will play on all the grouped speakers.

**Comment by joopjuh** [comment]
im using a LG soundbar and LG TV but i don't think i can pair these like the Sonos speakers.

**Comment by philippe44** [comment]
AirPlay supports streaming to multiple speakers in sync, it works pretty well. Apple has decided to never make it available from iOS, but you can use from iTunes (e.g.). Now, UPnP does not support sync, so that will probably defeat the purpose you have.
