### ISSUE TITLE
Works! How? Low volume and not clear and powerfull audio respect Sonos application.

### ISSUE THREAD

**Issue by biapar** [philippe44/AirConnect#117]
Works! How?
Problem: Low volume and not clear and powerfull audio.

**Comment by philippe44** [comment]
Sorry, I don't understand the question

**Comment by biapar** [comment]
I tried the MacOS app  but I hear this difference that is the audio is better with Sonos Application than with this workaround on Air Connect. I tried with the same song.

**Comment by philippe44** [comment]
When left with default, AirConnect does not do any modification to the audio, it's a bit-exact transfer. Now, it depends what is your source track. AirPlay only uses 16bits@44.1kHz while Sonos can do 16bits@48kHz. Now, what is the encoding and sample rate and size of the original track? When it is send from your iPod/iPad or iTunes, the necessary decoding and re-sampling will be done by the iXXX device if needed. Now if the track is already 16bits@44.1kHz, there is no changes made to the samples at all between playing through Sonos or playing through AirConnect. It's just the decoder and all decoder produce the same output when using the same input. The only difference can be volume which, as you know, even a little difference can make a subjetcive impact.

**Comment by biapar** [comment]
The difference is not only by volume, but also in loudness and the sound is more rich.

**Comment by philippe44** [comment]
Well, I don't know then. A said before, if the initial file is 16bits@44.1kHz, then wait is sent to Sonos speakers is bit-identical, unless you've selected to re-encode audio in mp3. But not knowing the audio source you're using or the configuration of AirConnect, I cannot tell

**Comment by biapar** [comment]
This are my flows for testing:
1) iTunes on MacOS -> Airplay -> Sonos Play:1
2) Sonos Application -> Sonos Play:1

**Comment by philippe44** [comment]
Can you tell me what is the original format (in iTunes and as scanned by the Sonos app)? As well, what parameters did you use for AirConnect? Especially the <mode> one

**Comment by biapar** [comment]
Do you suggest to try direct with your library without SonosAir? Apple Music use 256kbps AAC

**Comment by philippe44** [comment]
Yes - it's a bit less convenient if you are not technical, but SonoAir is "just" wrapping AirConnect with a UI to start/stop/configure it. 256kAAC does not tell me what is the sample rate

**Comment by biapar** [comment]
I'm a programmer -:). I'm not able to read the sample rate on Apple Music but It's at least 44.1kHz

**Comment by philippe44** [comment]
If you are a programmer you can use the OS X example to manually create a startup solution. I do not understand why you can’t get the file infos that tell you sampling rate. I have that in iTunes for every file

**Comment by biapar** [comment]
I tried your code...and the sound is good, now!
/airupnp-osx-multi  -l 1000:2000 -d all=error -d main=info -f airupnp.log
I close the post.
Thanks!

**Comment by biapar** [comment]
Can I push a lots of likes -:)!!!!!!!!!!
