### ISSUE TITLE
Running AirConnect on router

### ISSUE THREAD

**Issue by jnoobus** [philippe44/AirConnect#118]
Hi,

Is it possible to run AirConnect as a background process on my router? I have an Asus RT-AC68U with AiMesh installed, so I have SSH enabled. It would save me from running the background process on my laptop before streamed from my iOS phone to Chromecast.

Thanks!

**Comment by philippe44** [comment]
Probably not. It would require to have a proper Linux system and a known CPU. You can try, once you have identified which CPU it as. I assume it runs Linux, not sure if this is a chopped down version

**Comment by jnoobus** [comment]
Thanks. They all run a linux variant, as do the other open source router softwares (dd-wrt...etc). I figured that you might know since the README references the router that I have.

**Comment by philippe44** [comment]
Close for inactivity

**Comment by f4nyc** [comment]
Sorry to bother, I happen to have the same problem, airupnp-arm can't run on the router RT-AC68U, it has the ARM architecture Broadcom BCM4708A0 chip.  Are you willing to help figure out the cause of the problem?

**Comment by philippe44** [comment]
It's a very special setup, you know. You can try to run the the airupnp-arm-static that I've just pushed but it's unlikely to work

**Comment by timtn** [comment]
> It's a very special setup, you know. You can try to run the the airupnp-arm-static that I've just pushed but it's unlikely to work

Just tried arm-static, but it seems like the kernel on Asus-merlin is too old:
```
admin@RT-AC68U-47C0:/tmp/mnt/optware/entware# ./airupnp-arm-static
FATAL: kernel too old
Illegal instruction
```

```
uname -a
Linux RT-AC68U-47C0 2.6.36.4brcmarm #1 SMP PREEMPT Fri Aug 14 15:20:58 EDT 2020 armv7l ASUSWRT-Merlin

cat /proc/cpuinfo
Processor	: ARMv7 Processor rev 0 (v7l)
processor	: 0
BogoMIPS	: 1998.84

processor	: 1
BogoMIPS	: 1998.84

Features	: swp half thumb fastmult edsp 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

Hardware	: Northstar Prototype
Revision	: 0000
Serial		: 0000000000000000
```
