### ISSUE TITLE
freebsd and libssl.so.1.0.0 not found

### ISSUE THREAD

**Issue by ideal2545** [philippe44/AirConnect#119]
I'm trying to run this on Freebsd 11 but I have not been able to get it going successfully as libssl.so.1.0.0 is not found, any chance you could provide assistance with getting it installed in FreeBSD 11?

**Comment by philippe44** [comment]
Best is that you search where to find openssl1.0.0 on FreeBSD 11 (there has to be a pkg with that) or, last resort, try to create symbolic links (I do not recommend doing that, though). Find libssl.so.x.y and libcrypto.so.1.x.y and create links libssl.so.1.0.0 and libcrypto.so.1.0.0 to 1.0.2 to them.

**Comment by philippe44** [comment]
Close for inactivity
