### ISSUE TITLE
Use with Docker?

### ISSUE THREAD

**Issue by jrothlis** [philippe44/AirConnect#12]
Hi there, is there a documented way of getting this to work inside docker?

**Comment by philippe44** [comment]
no - it's a simple application that just need openssl shared lib (and glibc). All the rest is statically linked. As I said on another thread, docker is a total overkill for this. If you are concerned about security, scan the binary. If you are still concern, look at the source code and rebuild it. I will not create a docker guide for that, maybe somebody else will, I don't know

**Comment by jrothlis** [comment]
Docker is super lightweight (usually one command to install, one command to enable), and it eliminates dependencies and makes it a simple one line to run the software. In my case, I've downloaded the Linux executable, and this is all I get:

root@photon-machine [ ~/AirConnect/bin ]# ./airupnp-x86-64 -d all=sdebug
[22:15:57.348351] main:1185 Starting airupnp version: v0.1.1.0 (Oct 29 2017 @ 20:36:26)
[22:15:57.348496] main:1193 no config file, using defaults
[22:15:57.349134] Start:971 Binding to 192.168.71.231:49152
[22:16:12.001621] CallbackEventHandler:420 event: 7 [UPNP_DISCOVERY_SEARCH_TIMEOUT] [(nil)]
[22:16:12.001960] UpdateMRThread:650 Begin UPnP devices update
[22:16:12.002117] UpdateMRThread:725 End UPnP devices update 0
[22:16:42.001542] CallbackEventHandler:420 event: 7 [UPNP_DISCOVERY_SEARCH_TIMEOUT] [(nil)]
[22:16:42.001613] UpdateMRThread:650 Begin UPnP devices update
[22:16:42.001661] UpdateMRThread:725 End UPnP devices update 0

No discovery.

**Comment by philippe44** [comment]
I'm not saying docker is heavyweight, I just thought it      is not useful for such a simple application that has very limited dependencies. 
Re no discovery, are you in a VM that uses NAT? It won't work then, you lust use bridge and be one the same net. As well, if you have multiple NIC, you must select the right one. Other than that, your players should be found

**Comment by jrothlis** [comment]
No NAT involved... The VM only has a single NIC plus the loopback address. I tried the -b option just to be sure, but it didn't make any difference. This is running on Photon OS, a very lightweight Linux.

**Comment by philippe44** [comment]
So unless there is firewall involved, then I'm sorry I don't know. It's likely networking related. It's the upnp discovery request/response that is filtered out

**Comment by jrothlis** [comment]
I've built a Ubuntu VM and AirConnect is working great. Thanks!

General question: how do I configure it to run as a systemd service so that it starts whenever I reboot the VM, and so that systemd will restart the service if it fails?

And a general suggestion: can you change the code so that in the Sonos app it doesn't say "stream.flac" but rather "Streaming via AirConnect" or even better the name of the device that is streaming?

Thanks again!

**Comment by philippe44** [comment]
I'm not very good with systemd, I think you should create what is called a unit and make sure it's only started after the network is up, but I've not used that much. Re name, I can change that, it's about sending  metadata that I do not do with this application, but I have the 'infra' to do that

**Comment by philippe44** [comment]
Version 0.1.2.0 set title to "Streaming from AirUPnP/AirCast". I can't set the name of the AirPlay source

**Comment by jrothlis** [comment]
Tested, and works great. Minor nitpick: I would change it to "Streaming from AirConnect" (it's nicer than AirUPnP).
![file 22-11-2017 14 10 12](https://user-images.githubusercontent.com/17953/33131610-00cc21ce-cf8f-11e7-984c-797cc2624253.png)

**Comment by philippe44** [comment]
I wanted to differentiate from the Chromecast version (which says 'streaming from AirCast'). Any other vote? :-)

**Comment by jrothlis** [comment]
The ChromeCast and UPnP versions can never overlap, so why not call them both AirConnect (a much catchier name)?

**Comment by philippe44** [comment]
Added 0.1.2.1 with "Streaming from AirConnect"
