### ISSUE TITLE
Here is the sample rate of Apple Music

### ISSUE THREAD

**Issue by biapar** [philippe44/AirConnect#121]
@philippe44 : here is the info about the sample rate
![image](https://user-images.githubusercontent.com/661517/49288077-058ef600-f4a0-11e8-8f01-956947411e59.png)

**Comment by philippe44** [comment]
ok, so there should be no degradation at all when sent to Sonos

**Comment by biapar** [comment]
I like to know how you wrapper airplay and Sonos protocol. How?

**Comment by philippe44** [comment]
Closed for inactivity
