### ISSUE TITLE
AirConnect drops out consistently

### ISSUE THREAD

**Issue by Pe8er** [philippe44/AirConnect#123]
Setup:
- airupnp-osx-multi 2.2.2 running via launchctl on macOS High Sierra (10.13.3) on a Mac Mini, connected via ethernet
- Streaming from macOS Mojave 10.14, iTunes 12.9.0.164
- Streaming to Sonos Play:1 v9.3
- Router is Netgear R6400

AirConnect consistently stops working after 10-20 minutes.

Multicast filtering on my router is disabled.

I'm attaching my config and the log. Please help, this is driving me nuts 😅 

[airupnp.log](https://github.com/philippe44/AirConnect/files/2636780/airupnp.log)
[config.txt](https://github.com/philippe44/AirConnect/files/2636781/config.txt)

**Comment by philippe44** [comment]
That log seems to indicate that airupnp is voluntarily stopped/terminated every 20 minutes or so. Did you do something or just let it run?
Mayb try to run it manually in a command line window first

**Comment by Pe8er** [comment]
Thank you for quick reply! I set it up to launch automatically using launchd, like so:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>com.local.airupnp</string>
	<key>LaunchOnlyOnce</key>
	<false/>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/stasis/Applications/airupnp/airupnp-osx-multi</string>
		<string>-Z</string>
		<string>-x</string>
		<string>/Users/stasis/Applications/airupnp/config.xml</string>
		<string>-f</string>
		<string>/Users/stasis/Applications/airupnp/airupnp.log</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```
Suspiciously, it's been running fine for the past couple of hours… 😁 I also went through the launchd plist and realized that "LaunchOnlyOnce" should probably be set to false, considering what it means:

> This optional key specifies whether the job can only be run once and only once. In other words, if the job cannot be safely respawned without a full machine reboot, then set this key to be true.

If it breaks again, I'll run it manually and report back.

**Comment by philippe44** [comment]
Closed for inactivity
