### ISSUE TITLE
Core dump when running airupnp-arm inside a container after Sonos speaker grouping

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#127]
I'm running airupnp-arm v0.2.2.2 inside a Docker container on a Raspberry Pi, and streaming to Sonos is working very well.

However, if I group two Sonos rooms together, airupnp-arm will always core-dump at the point where it removes one of the Sonos slaves due to the relevant room now being part of the group. Example log excerpt:

```
[11:09:50.138317] UpdateThread:717 [0x941ac]: remove Sonos slave: Bedroom+
*** Error in `/airupnp-arm': munmap_chunk(): invalid pointer: 0x000945c3 ***
Aborted (core dumped)
```

This happens independently of whether anything is being streamed. The issue is **not** present when running airupnp-arm outside of a container, on the same host device.

I understand that this is a strange corner case, and I'm just looking for any ideas as to what might be happening.

**Comment by pwt** [comment]
Continuing to investigate. The core dump does not occur if I start airupnp-arm manually/interactively from within a container.

**Comment by pwt** [comment]
Ok, this is all to do with my config.xml file, and nothing to do with containers. I'm closing the issue, but may open another one. For the record, this is the content of my config.xml file:

```
<?xml version="1.0"?>
<airupnp>
    <common>
        <enabled>1</enabled>
        <max_volume>100</max_volume>
        <codec>flac</codec>
        <metadata>1</metadata>
        <artwork>https://github.com/pwt/docker-airconnect-arm/raw/master/airconnect-logo.png</artwork>
        <latency></latency>
    </common>
    <main_log>info</main_log>
    <upnp_log>info</upnp_log>
    <util_log>warn</util_log>
    <raop_log>info</raop_log>
    <log_limit>-1</log_limit>
</airupnp>
```

**Comment by philippe44** [comment]
it's artwork related - found and fixed

**Comment by pwt** [comment]
Great -- thank you. I'll look out for the commit.
Sorry for the container misdiagnosis.

**Comment by philippe44** [comment]
No worries, thanks for reporting the issue! - I've uploaded the update (did that quickly, so I did not test ...)

**Comment by pwt** [comment]
A quick test confirms that your fix works for me. Great work -- thanks again.
