### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [philippe44/AirConnect#128]
I would like to point out that identifiers like “[`__AIRCAST_H`](https://github.com/philippe44/AirConnect/blob/4b8af1bc92c4ef599e1b5a089b558393465e1acf/aircast/src/aircast.h#L21 "Update candidate")” and “[`_STR_LEN_`](https://github.com/philippe44/AirConnect/blob/f29deb5ba1838b658efe4797eb2eb54a87802b47/tools/platform.h#L163 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by philippe44** [comment]
Well, I hear you but I started like that and AirConnect is a simple application that is not a library or mission critical (see my other comment) so I don't have the patience to do all these better style changes, knowing that all i'm doing is night & week-ends work

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by philippe44** [comment]
Ok - you sound like a troll or a bot. I'll give you once chance to make a proper reponse and then I'll close that issue
