### ISSUE TITLE
Build for RPi 1

### ISSUE THREAD

**Issue by conloos** [philippe44/AirConnect#131]
Hi,

i have an old Raspberry Pi 1 Rev 2 Modell b and want to use them for AirConnect.
If i try to start the the arm Version provided by you i get an error, i think the binary is created for an other Rasperry Version.
Is it possible to build a version for armel?

# cat /proc/cpuinfo 
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 000e
Serial          : 0000000084f4f838

Thanks Frank

**Comment by philippe44** [comment]
The -arm5 build is normally done for that

**Comment by philippe44** [comment]
Closed for inactivity
