### ISSUE TITLE
AirConnect is running, but no Sonos on Iphone

### ISSUE THREAD

**Issue by Michelangelo18** [philippe44/AirConnect#137]
AirConnect is running on Raspberry without errors:
pi@raspberrypi:/var/lib/airconnect $ service airconnect status
● airconnect.service - AirUPnP bridge
   Loaded: loaded (/etc/systemd/system/airconnect.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-01-13 11:50:23 GMT; 6min ago
  Process: 1067 ExecStart=/var/lib/airconnect/airupnp-arm -x /var/lib/airconnect/config.xml -l 1000:
 Main PID: 1068 (airupnp-arm)
   CGroup: /system.slice/airconnect.service
           └─1068 /var/lib/airconnect/airupnp-arm -x /var/lib/airconnect/config.xml -l 1000:2000 -z

Jan 13 11:50:23 raspberrypi systemd[1]: Starting AirUPnP bridge...
Jan 13 11:50:23 raspberrypi systemd[1]: Started AirUPnP bridge.

Log:
[11:50:23.353471] main:1224 Starting airupnp version: v0.2.2.4 (Dec 16 2018 @ 16:04:27)
[11:50:23.411987] Start:984 Binding to 192.168.0.205:49152
[11:50:23.596584] AddMRDevice:896 [0x941b4]: adding renderer (Küche)
[11:50:23.596834] AddMRDevice:911 [0x941b4]: cannot get mac Küche+, creating fake 1eb5f70d
[11:50:23.612681] MasterHandler:604 [0x941b4]: subscribe success
[11:50:23.641710] ProcessEvent:403 [0x941b4]: UPnP Volume local change 12
[11:50:23.879988] AddMRDevice:896 [0x960d8]: adding renderer (Wohnzimmer)
[11:50:23.890546] MasterHandler:604 [0x960d8]: subscribe success
[11:50:23.900569] ProcessEvent:403 [0x960d8]: UPnP Volume local change 15

I can't see any Sonos devices in the airplay list of the Iphone with IOS 10.3.3

What can I do ??

Thanks.....

**Comment by philippe44** [comment]
Is your iPhone on the same before or through anything that blocks multicast traffic?

**Comment by Michelangelo18** [comment]
what do you mean with blocks multicast traffic?

**Comment by philippe44** [comment]
Sorry, typo, the "before" was supposed to mean "network" (typed that on an iPhone). Some routers or bridges block multicast traffic between segments (PLC, ethernet, WiFi). 
AirConnect probes your network using multicast for UPnP devices (that works in your case) and then announces their AirPlay twins using as well multicast. This announce might be blocked by one of the network element between the Pi and your iPhone. 
In your example, do you have devices connected *exactly* on the same physical part of your network than the Pi and that are discovered by your iPhone? (like Chromecast or other AirPlay devices). More generally, can you describe the topology of your network.

**Comment by Michelangelo18** [comment]
Oh, it was my mistake. It works perfectly fine. I have never used Airplay and just clicked on this button (IOS10.3.3). Then he looks for airplay devices but no found it. But if you continue to wipe left, all Airplay devices are offered.
Many Thanks.
