### ISSUE TITLE
Continued issues with Raspberry Pi Zero W / Raspbian Stretch (latest build)

### ISSUE THREAD

**Issue by ztaub** [philippe44/AirConnect#138]
Hi Philippe,

I have been following the readme, older issue threads, etc. trying to get my Pi to run, but I am also still getting the "Illegal Instruction" when running airupnp-arm and -arm5. I downloaded the openssl that you recommended, and I saw that there might be a different one required due to the difference between armv6 and armv7, but i couldn't find an older openssl build that could work. I even tried using the older deb7u4, but that didn't work either. Could it be related to the ssl file (i.e. is there another active install that would work) or could it be that I am now running raspbian stretch, and it requires Jessie? I wanted to ask because i didn't want to have to wipe my RPi and start over with Jessie if it works on stretch, but I am seemingly out of ideas after searching for answers as to how to overcome the illegal instruction.

Thanks!

**Comment by philippe44** [comment]
You can use the last resort option that I don't like: create a symlink to the libssl1.1
sudo ln -s libcrypto.so.1.1 libcrypto.so.1.0.0
sudo ln -s libssl.so.1.1 libssl.so.1.0.0

**Comment by ztaub** [comment]
Hmmm... for some reason this still is not working (i.e. still illegal instruction). I followed your instructions including downloading that .deb file... do I need to uninstall that or is it fine to sit there? Is there anything else I might be able to try?

**Comment by philippe44** [comment]
no no, there is nothing anymore to download then. Just doing a symlink to your *existing* crypto libs

**Comment by philippe44** [comment]
An update?

**Comment by philippe44** [comment]
No worries, let’s close the issue then
