### ISSUE TITLE
airupnp v0.2.3.0 binaries report version v0.2.2.6

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#141]
Not quite sure what's going on here, but the current airupnp binaries tagged v0.2.3.0 are reporting v0.2.2.6 when started. Tested with airupnp-arm and airupnp-osx-multi. The build time looks right, however. See embedded version strings below:

```
$ strings airupnp-arm | grep 0.2.2.6
v0.2.2.6 (Jan 18 2019 @ 18:01:12)
v0.2.2.6 (Jan 18 2019 @ 18:01:12)
```

**Comment by philippe44** [comment]
Thanks for catching that. I'm not sure what happended, so I've done a full rebuild of 0.2.3.1

**Comment by pwt** [comment]
Thanks @philippe44 . Confirmed fixed.
