### ISSUE TITLE
Possible improvement for Denon HEOS speakers

### ISSUE THREAD

**Issue by olalid** [philippe44/AirConnect#142]
It seems Denon HEOS speakers have some kind of bug, not sure how and when it is triggered, but sometimes, they will stop responding to upnp search requests (M-SEARCH). In my setup it is more likely to happen on one specific speaker for some reason (I have 3 HEOS 1 speaker, all have the same hardware and firmware revision). A couple of theories is that it can be because it is further away from the access point or that it has something to do with Spotify connect playback.

The speaker seems to work just fine anyway, as it is possible to send audio to them using the HEOS app and Spotify, and also the upnp "ALIVE" packets are still being transmitted faithfully exactly once a minute from the speaker.
I am thinking that it might be possible to work around this bug by "passively" listening to the ALIVE packet data and make sure not do delete the device in case these keep coming, even though it does not respond to a search.

In air airupnp.c function MasterHandler() incoming upnp events of the type UPNP_DISCOVERY_ADVERTISEMENT_ALIVE are currently ignored, but should be possible to implement something fairly simple that updates the "LastSeen" entry in the device so that it does not time out as long as the ALIVE messages are being sent out.

It is not given that it will work, but probably worth a try.

Maybe I can work on this a bit and test this myself.
However, I have not been able to build the SW so far.
I seem to get a lot of strange errors that I can not really work around without making changes to the code in lots of places, which seems unnecessary, it must be possible to get it to compile as is I assume.
What compiler are you using for Linux builds? I have gcc 7.3.0 on ubuntu 18.04.

**Comment by philippe44** [comment]
I'm still mainly using gcc 4.9.1 on my x86 build
Re using UPNP_DISCOVERY_ADVERTISEMENT_ALIVE, I have to remember why, but I think I used the message at some point but had issues with that and decided to ignore it. I'll to dig into that

**Comment by olalid** [comment]
After looking in to this, I am not so sure anymore the bug is in the HEOS devices. It seems this happens when they are connected to the 2.4GHz WiFi (as opposed to 5 GHz WiFi). The access point I have (UniFi AC-Pro) is configured with the same networks SSID for both 2.4 and 5 GHz, so clients will choose for themselves which of 2.4/5GHz they will connect to.
So perhaps, when the HEOS devices first boot, they will connect to 5GHz for a while, then switch to 2.4GHz if they feel that is better (which mostly happens for the device that is furthest away from the access point).
So maybe there is some kind of limitation (bug or feature) with broadcast traffic from wired network being routed over to 2.4GHz network. The other way around (broadcast traffic from 2.4GHz network to wired and 5GHz network) seems to work reliably though, so making a change like the one I proposed would probably work around this issue. Not sure if that is the right thing to do, but it may actually make things easier for some people.

**Comment by olalid** [comment]
I have now set "Group Rekey Interval" to "never" in my access point and everything has been stable for the last 24 hours. This key is apparently used for broadcast traffic LAN->WLAN, while broadcast traffic WLAN->LAN uses client specific keys.
So if the group key is not in sync between all wireless clients some clients will not receive broadcast data.
Which would explain what I see, that the HEOS device stops responding to search requests that are sent over broadcast, while they continue to send out alive packets that are received at the wired LAN.
So I guess there real issue here is some incompatibility between my HEOS devices and my access point.

**Comment by olalid** [comment]
Closing.
