### ISSUE TITLE
Qnap package

### ISSUE THREAD

**Issue by RogueAi-NYC** [philippe44/AirConnect#146]
Hi @philippe44,

thanks so much for developing this. I was really thinking of getting rid of my 3 room Sonos system as my wife was not willing to install a new app and insisted on Airplay.

Is there any chance you or someone else already installed this on a QNAP NAS and can write a guide on how to do that? I'm unfortunately not versed enough in Linux to do so, but am confident enough in following step by step guides.

Happy to make a donation (either direct or to a charity of choice).

**Comment by philippe44** [comment]
I've not heard about a QNAP installation. Now if you know how to SSH on you QNAP NAS, it's probably fairy easy at least to try AirConnect. Maybe ask around on QNAP forums?

**Comment by oioilu** [comment]
> Hi @philippe44,
> 
> thanks so much for developing this. I was really thinking of getting rid of my 3 room Sonos system as my wife was not willing to install a new app and insisted on Airplay.
> 
> Is there any chance you or someone else already installed this on a QNAP NAS and can write a guide on how to do that? I'm unfortunately not versed enough in Linux to do so, but am confident enough in following step by step guides.
> 
> Happy to make a donation (either direct or to a charity of choice).

RogueAi,
You may try install Container Station on Qnap (if your Qnap can support this feature). Then try to install a docker image from dockerhub  named "swilsonau/docker-airconnect".

This works for me .

**Comment by philippe44** [comment]
Closed for inactivity
