### ISSUE TITLE
Q: '-m' option: differentiate between new & old Sonos PLAY:5s?

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#150]
Do you know if there's a way to differentiate between the gen1 and gen2 models of the Sonos PLAY:5, when using the '-m' command line option in airupnp? Only the latter supports native AirPlay, but the following command line would (I believe) exclude both PLAY:5 models:

-m PLAY:5,PLAYBASE,BEAM,One,Amp

Thanks.

**Comment by philippe44** [comment]
I don't have a new play:5, but according to what you see they don't see to have a different upnp model name, right? I they don't, I can't think of an easy way to differentiate them other than through the config file

**Comment by pwt** [comment]
Thanks for the response. I only have examples of the newer PLAY:5, so I don't know what model name string is reported for the older version.

Any chance you could check what model name string is returned for the older PLAY:5? I'm going to assume it's also 'PLAY:5', but it's worth confirming.

**Comment by pwt** [comment]
This is an excerpt of the uPnP device information for the gen2 PLAY:5

```
<device>
<deviceType>urn:schemas-upnp-org:device:ZonePlayer:1</deviceType>
<friendlyName>192.168.0.31 - Sonos Play:5</friendlyName>
<manufacturer>Sonos, Inc.</manufacturer>
<manufacturerURL>http://www.sonos.com</manufacturerURL>
<modelNumber>S6</modelNumber>
<modelDescription>Sonos Play:5</modelDescription>
<modelName>Sonos Play:5</modelName>
<modelURL>http://www.sonos.com/products/zoneplayers/S6</modelURL>
<softwareVersion>48.2-61220</softwareVersion>
<hardwareVersion>1.13.1.7-2</hardwareVersion>
...
</device>
```

I assume the `modelName` will be the same for the gen1 PLAY:5, so I guess the differentiation would need to be done on the `modelNumber` string, which is not currently used by AirConnect.

**Comment by pwt** [comment]
Ok, I've updated airupnp.c to add a **'-n'** option that works just like **'-m'**, but matches on device model numbers instead of names. Both options can be used simultaneously. I don't have a build environment set up for AirConnect, so I haven't done any compilation or testing, but the changes are fairly simple and limited.

However, I'm getting tripped up by line-ending conventions in git (it thinks I've changed every line) so I'm not going to create a pull request. While I sort this out, you can find the updated version of airupnp.c at https://gist.github.com/pwt/5c56424c129e0b74b519af1b99633c2a

**Comment by pwt** [comment]
Hi @philippe44 : I've now managed to set up a rudimentary build environment on macOS, to the extent that I can now at least successfully build and run the `airupnp-osx-multi` executable.

I've tested the new **'-n'** option, and it's working fine after a couple of minor tweaks. Note that I can only test with Sonos equipment, as I have no other uPnP players.

Perhaps you could take a quick look at the code linked below, and let me know if it's something you'd accept as a PR? If so, I'll try to figure out how to address the formatting issues. If you pull down the file into a local git working copy, you can isolate my changes using `git diff -b airupnp.c`.

https://gist.github.com/pwt/5c56424c129e0b74b519af1b99633c2a

Thanks!

**Comment by philippe44** [comment]
Thanks - Should be in 0.2.5.0. I've not tested it yet :-)

**Comment by pwt** [comment]
Great -- thanks! Let me know if you want a PR from me, or feel free just to apply the changes yourself.

Note that I'm having a problem in that the `airupnp.c` file appears to have mixed line ending conventions, meaning I'm finding it hard to create a 'clean' commit isolated only to my changes.

**Comment by pwt** [comment]
Thanks for adding this feature.
