### ISSUE TITLE
No audio output on Sonos devices with v0.2.5.0

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#151]
With the new 0.2.5.0 version, I'm not getting any audio output at the Sonos devices. Source devices connect OK. I've tried airupnp-osx-multi and airupnp-arm, with the same result. Reverting to the v0.2.4.0 executables (leaving everything else the same) fixes the issue.

Perhaps I'm doing something dumb! Let me know if you'd  like me to run any specific tests.

**Comment by philippe44** [comment]
I think there was a problem with the build itself, don't know what happened. I've updated to 0.2.6.0 and added other optimizations to reduce CPU usage in idle

**Comment by pwt** [comment]
Thanks @philippe44. A quick test of v0.2.6.0 indicates all is well again! Closing the issue.
