### ISSUE TITLE
Minor issue: airupnp v0.2.8.0 binaries report version v0.2.7.0

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#153]
This is just a heads-up to flag a possible build issue. Not expecting a fix ... might as well just wait for the next set of changes.

**Comment by philippe44** [comment]
I probably forgot to run one of my scripts - thanks for the heads-up!

**Comment by philippe44** [comment]
Should be fine now

**Comment by pwt** [comment]
Thanks @philippe44
