### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by bjowes** [philippe44/AirConnect#155]
Hi @philippe44 , thanks for making this!

I am attempting to use the volume scaling feature to make my new soundbar usable together with my iPhone (with default volume control the steps are far too large, which I understand is common when using iPhone with external speakers that aren't Airplay capable).

I found in the source code that the volume scaling is only activated when casting to a group of Chromecast devices. For my use case I want to use it with a single device. Hence I am attempting to build a custom version of your software - if successful I may deliver a PR with this feature.

Now I am stumbling with making this all compile with the additional libraries. For several of the libraries there have been issues which I think I resolved by using a slightly older release of the library. To simplify this task, could you please specify the exact version you are using for each library? Also, what is your build environment - what do I need to install to cross compile for arm for instance.

**Comment by philippe44** [comment]
Normally the libraries indicated at the bottom can be taken from the give links. For AirCast you need libixml.a, libshine.a and libFLAC.a. They can be tough to build in a cross-compiling environment. That's what I'm doing but are you sure you want to go there? I can send you some pre-build ones, just tell me the target

**Comment by bjowes** [comment]
I would be interested in those libraries for OS X and Raspberry Pi 3, thanks!

I could find all the sources from the links in the README, but some of the repos apparently allow updates directly to the master - hence there is a difference between the master and the latest numbered release. This could potentially break your build - I might have something else missing in my setup, but I found that stepping back to an older version helped in several cases. Therefore I think it would be valuable if you could just add the current versions you use to compile.

**Comment by philippe44** [comment]
libixml : libupnp 1.6.19
shine: the most recent one
libflac: 1.3.2
here https://www.dropbox.com/sh/ef593une5d3mc62/AACocpnn3IqiKRykUtHBCg23a?dl=0

**Comment by bjowes** [comment]
Thanks a bunch! I'll have another go at it in the near future. Closing.
