### ISSUE TITLE
outdated libcrypto.so.1.0.0 requirement

### ISSUE THREAD

**Issue by MrSimmo** [philippe44/AirConnect#158]
Hi,

When I tried to run the prebuilt airupnp-x86-64 binary on CentOS7, it bombs saying:

./airupnp-x86-64: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

CentOS7 and others use a newer version of libcrypto (libcrypto.so.1.0.2k) so I needed to symbolic link it to trick airupnp into working:

sudo ln -s /usr/lib64/libcrypto.so.1.0.2k /usr/lib64/libcrypto.so.1.0.0

Would it be possible to provide version the binary that supports the newer versions of the library please?

**Comment by philippe44** [comment]
There is no good solution to that problem. A lot of systems still run 1.0.0, so that would break all these. I'll wait for some time till most system have moved to 1.0.2 an I'll rebuild something then

**Comment by MrSimmo** [comment]
Thanks Philippe all good
