### ISSUE TITLE
Chromecast devices (Nvidia SHIELD and Chromecast Audio) only show up randomly in AirPlay

### ISSUE THREAD

**Issue by ratsputin** [philippe44/AirConnect#162]
I have an unusual problem I'm hoping you can help me troubleshoot.

When I start AirConnect, I may or may not see the Chromecast devices in Airplay.  Here are a couple of startup examples:

```
wyer@ubuntu:~/AirConnect/bin$ ./aircast-x86-64 -x ./config.xml
[09:13:09.806068] main:914 Starting aircast version: v0.2.9.0 (Apr 20 2019 @ 14:33:41)
[09:13:09.806154] Start:689 Binding to 192.168.1.9
[09:13:09.807952] AddCastDevice:626 [0x68e2c0]: adding renderer (SHIELD)
[09:13:09.820201] AddCastDevice:626 [0x68eb48]: adding renderer (Kitchen Speaker)
exit
[09:13:28.012165] main:1031 stopping Cast devices ...
Segmentation fault (core dumped)
wyer@ubuntu:~/AirConnect/bin$ ./aircast-x86-64 -x ./config.xml
[09:13:50.485564] main:914 Starting aircast version: v0.2.9.0 (Apr 20 2019 @ 14:33:41)
[09:13:50.485710] Start:689 Binding to 192.168.1.9
[09:13:50.487655] AddCastDevice:626 [0x68e2c0]: adding renderer (SHIELD)
[09:13:50.501825] AddCastDevice:626 [0x68eb48]: adding renderer (Kitchen Speaker)
```
The first time, neither showed up in AirPlay, the second time, both showed up.  Once they show up, they work flawlessly.

I have tried leaving AirConnect running for several hours to see if it's just a timing thing with no luck.

I should note that I have an Apple TV that shows up 100% of the time.

Do you have any insight or ideas of where I can start?

**Comment by philippe44** [comment]
They are detected both time, are you sure this is not something with the iDevice? have you tried iTunes on a PC to see what it sees? I also ahve to look why there is a crash upon exiting, which is a different problem

**Comment by ratsputin** [comment]
Thank you for the response and the suggestion.

I did some experiments and it appears that having iTunes up on a PC (or Mac) makes the behavior of AirConnect more reliable and predictable for iDevices.  I'd guess that without iTunes up, I could only get to my Chromecast Audio maybe 20% of the time from my iPhone.  If, however, I have iTunes up on a PC or Mac, that improves to probably 95% of the time.

Interestingly, in the instances where the AirConnect devices don't show up on my iPhone, I can run iTunes and it will fix it almost immediately.  Apparently, there is something that iTunes is doing that resolves the issue causing the devices not to show up.

When I get a chance, I'm going to take a look at the mDNS entries and see if iTunes is adding something that's missing.

**Comment by philippe44** [comment]
You might have network elements like PLC, router, switches, gateways ... that block or don't deal well with multicast traffic

**Comment by philippe44** [comment]
Closed for inactivity
