### ISSUE TITLE
Duplicate Airplay Devices (ending with _______+)

### ISSUE THREAD

**Issue by yonigold1** [philippe44/AirConnect#163]
Me again lol after forcing myself to figure out how to set up airconnect (took me a good 3 hours and I'm super proud of myself 😆) I now am able to airplay to my chromecast and Sonos but I see that in my airplay menu there are duplicates of all my speakers and i wanna know if its possible to get rid of it some how or maybe you can do something to the file and make it ignore the other devices or something idk im stupid with this stuff lol but its a lil frustrating but it is possible to live with 
<img width="201" alt="SS 2019-05-03 at 6 26 37 PM" src="https://user-images.githubusercontent.com/34217684/57169371-420aa900-6dd4-11e9-9490-a04226cfccad.png">

**Comment by pwt** [comment]
That's because you probably have some Sonos speakers that have native AirPlay 2 capability (the duplicates without the '+'). You can prevent AirConnect from including these speakers with command line options: take a look at how I do this at the following link:

https://github.com/pwt/docker-airconnect-arm/blob/master/Dockerfile

See the text at the bottom of the Dockerfile.

**Comment by yonigold1** [comment]
> That's because you probably have some Sonos speakers that have native AirPlay 2 capability (the duplicates without the '+'). You can prevent AirConnect from including these speakers with command line options '-m' and '-n': take a look at how I do this at the following link:
> 
> https://github.com/pwt/docker-airconnect-arm/blob/master/Dockerfile
> 
> See the text at the bottom of the Dockerfile.

**Comment by yonigold1** [comment]
the Basement and Jacobs room speakers are not sonos though

**Comment by pwt** [comment]
> the Basement and Jacobs room speakers are not sonos though

It may be something similar, though. It's only the speakers with a '+' that AirConnect is adding as AirPlay targets.

I only have experience with (a wide range of) Sonos speakers, but you may be able to modify my advice for the speakers you have.

Failing that, you can generate and edit a 'config.xml' file to disable specific speakers.

**Comment by yonigold1** [comment]
so I just wanna clarify the + speakers are the ones that AirConnect meaning that when AirConnect is off the list should just be:
<img width="203" alt="SS 2019-05-03 at 7 35 54 PM" src="https://user-images.githubusercontent.com/34217684/57170402-ab8db600-6dda-11e9-9e1b-b85268e495ae.png">

and if that's what u mean would u mind walking me through how to do that :) it would be a big help

**Comment by yonigold1** [comment]
oops accidentally closed the issue

**Comment by pwt** [comment]
Yes, the AirPlay targets with '+' appended to their names are the ones created by AirConnect. You have two options for getting AirConnect to exclude the speakers that already support AirPlay:

**1) Exclude the speakers automatically by model name and/or model number.**

- For this, use the '-m' and/or '-n' command line options.
- Model name is the `modelName` string in the UPnP device description for the speaker, model number is the `modelNumber` string. You'll have to determine these somehow, or you could try a few guesses.
- So, if your speaker name is (e.g.) 'Play:5', you'd add `-m Play:5` to the command line you use to start airupnp.

**2) Exclude the speakers manually by disabling them in a configuration file.**

- First, generate a config file by starting airupnp with the `-i config.xml` option; you can then stop airupnp.
- This will create a `config.xml` file in the current directory. If you inspect this file, you'll see some XML for each of your discovered speakers, each in a `device` section.
- Edit the file: for each speaker you want to disable, set the `enabled` field to `0`.
- When you next start airupnpn, it will read the `config.xml` file and omit the disabled speakers.

**Comment by philippe44** [comment]
BTW, one thing you can do is set the `enabled` field to 0 in the <common> section and just keep listed the device(s) you want and put an `enabled` field to 1 for that (or these) devices. With by default, any newly discovered device will be disabled

**Comment by yonigold1** [comment]
im going to try both of these ideas will let u guys know if i need anymore help

**Comment by yonigold1** [comment]
> Yes, the AirPlay targets with '+' appended to their names are the ones created by AirConnect. You have two options for getting AirConnect to exclude the speakers that already support AirPlay:
> 
> **1) Exclude the speakers automatically by model name and/or model number.**
> 
> * For this, use the '-m' and/or '-n' command line options.
> * Model name is the `modelName` string in the UPnP device description for the speaker, model number is the `modelNumber` string. You'll have to determine these somehow, or you could try a few guesses.
> * So, if your speaker name is (e.g.) 'Play:5', you'd add `-m Play:5` to the command line you use to start airupnp.
> 
> **2) Exclude the speakers manually by disabling them in a configuration file.**
> 
> * First, generate a config file by starting airupnp with the `-i config.xml` option; you can then stop airupnp.
> * This will create a `config.xml` file in the current directory. If you inspect this file, you'll see some XML for each of your discovered speakers, each in a `device` section.
> * Edit the file: for each speaker you want to disable, set the `enabled` field to `0`.
> * When you next start airupnpn, it will read the `config.xml` file and omit the disabled speakers.

so for this what do u mean "use the '-m' and/or '-n' command line options" like i just type -m? or -n? like where do i type it in terminal?

**Comment by yonigold1** [comment]
also, what can someone just make sure that everything here is how it should be? 

<img width="569" alt="SS 2019-05-05 at 12 51 36 PM" src="https://user-images.githubusercontent.com/34217684/57197379-8614bf80-6f34-11e9-8fd9-36ed03248de5.png">

**Comment by yonigold1** [comment]
so i did this:
2) Exclude the speakers manually by disabling them in a configuration file.

First, generate a config file by starting airupnp with the -i config.xml option; you can then stop airupnp.
This will create a config.xml file in the current directory. If you inspect this file, you'll see some XML for each of your discovered speakers, each in a device section.
Edit the file: for each speaker you want to disable, set the enabled field to 0.
When you next start airupnpn, it will read the config.xml file and omit the disabled speakers.

but now i dont think it sees the config file so i still see the + devices


<img width="1440" alt="SS 2019-05-05 at 1 00 09 PM" src="https://user-images.githubusercontent.com/34217684/57197480-b872ec80-6f35-11e9-89d8-4dab0b612c89.png">

**Comment by yonigold1** [comment]
ok so i got it to work by running the command: `./airupnp-osx-multi.dms -x /Users/yonigold/AirConnect/config.xml ` and im currently not seeing the duplicates and im seeing eveything that i like but my only other question is now is how can i modify the original file so that when i open the airupnp-osx-multi.dms it will run the command `./airupnp-osx-multi.dms -x /Users/yonigold/AirConnect/config.xml` and so it will exclude the devices 
<img width="830" alt="SS 2019-05-05 at 1 05 47 PM" src="https://user-images.githubusercontent.com/34217684/57197533-81510b00-6f36-11e9-8ecf-1272cf5c3e25.png">

**Comment by pwt** [comment]
I'm afraid I don't know what a `.dms` file is. Did you look at the section in the Readme entitled 'Start automatically in MacOS'? That lets you add the config file ... in the example it uses `aircast.xml` as the config file name.

**Comment by yonigold1** [comment]
will try this and let u know

**Comment by yonigold1** [comment]
another question how do i check to see if it runs when it starts up

**Comment by pwt** [comment]
> how do i check to see if it runs when it starts up

The obvious thing to do is to check that the relevant speakers appear in your list of AirPlay targets. You can also check for the log file: `/Users/yonigold/AirConnect/airupnp.log`.

**Comment by yonigold1** [comment]
i dont have the file `airupnp.log ` is that bad?

**Comment by philippe44** [comment]
you can use the -p <pidfile> option. It will create a file named <pidfile> with contains the processus id. If the file is empty, then it is not running. But why are you worried about that at the first place?

**Comment by yonigold1** [comment]
> you can use the -p option. It will create a file named with contains the processus id. If the file is empty, then it is not running. But why are you worried about that at the first place?


so i want the file to see if air connect launches when i log into my mac

**Comment by yonigold1** [comment]
> > how do i check to see if it runs when it starts up
> 
> The obvious thing to do is to check that the relevant speakers appear in your list of AirPlay targets. You can also check for the log file: `/Users/yonigold/AirConnect/airupnp.log`.

so when i log into my mac in the log file the last time i see it boot is april 20

**Comment by philippe44** [comment]
It's the date of the build

**Comment by yonigold1** [comment]
> It's the date of the build
 ah ok i have another issue believe it or not i have the config.xml setup with all the devices i want disabled and one of my devices is still duplicated with a + at the end

**Comment by philippe44** [comment]
Use the advice I gave you there https://github.com/philippe44/AirConnect/issues/163#issuecomment-489346776

**Comment by yonigold1** [comment]
thats what i did but it still doesnt seem to work

**Comment by pwt** [comment]
Could you post the contents of your `config.xml` file, and confirm what the name of the duplicate device is? I'll take a look.

**Comment by yonigold1** [comment]
> Could you post the contents of your `config.xml` file, and confirm what the name of the duplicate device is? I'll take a look.

will do as soon as i get home

**Comment by yonigold1** [comment]
so im still trying to play around with it. All good so far. ill report back at the end of the week
