### ISSUE TITLE
some devices didnot found

### ISSUE THREAD

**Issue by ideafxl** [philippe44/AirConnect#165]
I have 3 Smart speakers，Xaiomi and Xiaodu，i run the airconnect on raspberry ，but only the xiaomi speaker can be found，others like on-existent，what can i do to this，appreciate！
![批注 2019-05-12 223133](https://user-images.githubusercontent.com/49922868/57583705-c57b7700-7505-11e9-9668-7e1372d3062d.png)

**Comment by philippe44** [comment]
are you sure they are all UPnP? Other than that, what's your network topolgy?

**Comment by philippe44** [comment]
Closed for inactivity
