### ISSUE TITLE
CCA only has audio: Local meta data and command line transport control?

### ISSUE THREAD

**Issue by OneBobone** [philippe44/AirConnect#166]
Hello!
Very nice project that you are developing. Congratulations!
I am trying to integrate Airconnect to an older WHA system: Nuvo Grand Concerto.
CCA has been very useful for this. I am also using HomeSeer and a CCA plugin.

Not sure what is supposed to work, but I cannot get get NEXT and PREVIOUS to work nor basic metadata to the CCA (as seen on GH). Only Audio and PAUSE/STOP.

If this could work, it would obviously be great but, I am actually looking for:
- command line transport control from Airconnect
- metadata piped to a local file
- album art piped to a local file

Is this possible? 
I am running on Windows 7 but could run on Cygwin as well.

Thanks,

Bob

**Comment by philippe44** [comment]
Hi - Next and Previous can only come from the AirPlay controller, so you would have to detect it and send  commands to it. The raopcore.c gives you a good idea on how to detect active-remote and submit commands to these (look at the general raop/dmcp on the internet as well).

Understand that AirPlay is virtually an audio pipe with an OutofBand control to send volume commands & metadata info. Once playback has started, everything is just a looong track and whenever metadata changes, AirPlay controller sends that update OoB using RTSP.

Unfortunately, CC devices do not work that way, they want each track to be an individual URL (if you want metadata to be displayed) and there is no OoB control. So to some extend, AirPlay is a webradio to the CC and unfortunately CC does not even accept shoutcast in-band metadata update for mp3/aac, so there is now way to update it

Having each metadata & artwork update piped by AirConnect and having AirConnect offer a command line interface to notify back the AirPlay controller is a lot of work that is really out the scope of what I'm doing. I'm not even sure that you could do anything with these from a CC point of view. I assume this is more for the WHA needs, right?

**Comment by OneBobone** [comment]
Yes, you are perfectly right, the CCA would just be a DAC in sense, but that is a valuable starting point.
As some metadata is visible in the logs, I was assuming that album art was also passing through the airconnect engine?
With your knowhow, do you think that it is possible to use raopcore.c with Windows to control Airplay? (I forgot to mention that “volume” control works.)

**Comment by philippe44** [comment]
The album art is passed as a data blob (not an an URL),  I just discard it currently. 
You can control the AirPlay controller, I already do that to send play, pause, stop and volume when I detect somethign happened on the CCA side. It dont in raop_notify()

**Comment by OneBobone** [comment]
Hello Phillipe,
Thank you very much for your kind input. All of what you write sounds quite promissing!
I may however have given you the wrong impression of my skills. I am not a C++ programmer and Linux abilities are quite limited.

Do you not need to have a unique token or similar to control Airplay on an iDevice?
My need is to get this to work on Windows. I have also tried to get Shairport-Sync to work, but there the control problems had to do with dbus compatibilty with Cygwin, according to the friendly developer.

How would you suggest that I proceed? 
- Can I call raop_notify() somehow from a command line?
- How do I capture the blob? If it could just get dumped in a file that is overwritten, it would be great. Possibly with other metadata (duration, title, album, artist)

Many thanks,
Bob

**Comment by philippe44** [comment]
Hi Bob - Unfortunately, these modifications require C-level programming and if you are not familiar with that, it's going to be impossible. You would need, in the C program, to create a namedpipe a send metadata (including image) to it, a bit like shairport-sync does. You would also need to find a way to get input from another pipe, maybe stdin to direct command to the player, adn this is probably the most difficult one. I would even not do that from AirConnect, I would in fact use external applications to detect the remote and connect with it.

**Comment by OneBobone** [comment]
> You would also need to find a way to get input from another pipe, maybe stdin to direct command to the player, adn this is probably the most difficult one. I would even not do that from AirConnect, I would in fact use external applications to detect the remote and connect with it.

Thank you!
My thinking was that since you already manage to command the Airplay controller from Airconnect, that it might be possible to access those commands by exposing them in some way? This would be valuable when control from e.g. CCAs is not (directly) possible.
What other project would you have in mind that could work alongside with Airconnect? It would have to be in the same session, right?

**Comment by philippe44** [comment]
I don't have in mind a specific project, but you don't need to use the same airplay session, you just need to detect controller and send them commands.
What you describe is absolutely possible, I just cannot put that on my todo list currently

**Comment by OneBobone** [comment]
> I don't have in mind a specific project, but you don't need to use the same airplay session, you just need to detect controller and send them commands.
> What you describe is absolutely possible, I just cannot put that on my todo list currently

Ok, fair enough. I respect that.
Just to be sure, by controller you mean e.g. a typical iPhone?

**Comment by philippe44** [comment]
yes
