### ISSUE TITLE
Can't run aircast in a router running Openwrt

### ISSUE THREAD

**Issue by bit3725** [philippe44/AirConnect#167]
Hi Philippe, 

I'm trying to run version 0.2.10.1 of aircast and airupnp in a router running Openwrt.
because the CPU of this router is Intel® Celeron® Processor J1900, I chose aircast-x86-64 and airupnp-x86-64.
when I try to launch aircast or airupnp from command line, I just saw this error message:

> -ash: ./aircast-x86-64: not found

I guess it's because some dependent libraries are missing in Openwrt. is there a way to detect which libraries are missing?

by the way, libssl version is 1.1. I tried to create symbolink for libssl.so.1.1 and libcrypto.so.1.1 like you mentioned in this [issue](https://github.com/philippe44/AirConnect/issues/138), but got same error message.

**Comment by philippe44** [comment]
There was a mistake in the x86-64 version of airupnp where it was still trying to load openssl the "old way". This is now corrected (I've not updted version number ... yet). I've also added a -static version, where everything is statically linked. Let me know if it works

**Comment by bit3725** [comment]
Hi Philippe,

I tried with airupnp-x86-64-static this time, it said can't load SSL libraries and can't start:

> [09:25:48.587532] main:1289 Starting airupnp version: v0.2.10.1 (May 10 2019 @ 21:13:38)
> [09:25:48.587696] main:1297 no config file, using defaults
> [09:25:48.638824] Start:1017 Binding to 192.168.100.12:49152
> [09:25:48.638965] Start:1022 Cannot load SSL libraries
> [09:25:48.640569] main:1330 Cannot start

**Comment by philippe44** [comment]
Almost there - you should find an libcrypt.so and libssl.so and make it at a place where airupnp can access them

**Comment by bit3725** [comment]
Hi Philippe,

I have copied libcrypto.so and libssl.so and placed them into the folder of airupnp-x86-64-static saved, but I still got the same error. 
Do I need to move so files to another folder or add a parameter when launch airupnp-x86-64-static?

**Comment by philippe44** [comment]
Did you try the non-static version as well

**Comment by bit3725** [comment]
I saw you didn't update non-static version when release airupnp-x86-64-static.

The non-static version just gave this error message as I mentioned before:

> -ash: ./aircast-x86-64: not found

**Comment by philippe44** [comment]
Ok so let’s stick with the -static version. Did you have LD_LIBRARY_PATH set to where these libraries are?

**Comment by bit3725** [comment]
Didn't have LD_LIBRARY_PATH set before.
When I have set LD_LIBRARY_PATH, I can start airupnp-x86-64-static successfully.
Then I remove symlink for libssl and libcrypto, it still works. confirmed if set LD_LIBRARY_PATH correctly, airupnp-x86-64-static works well.

Could you help to build aircast-x86-64-static also?
Thanks very much!

**Comment by philippe44** [comment]
It will now be part of default build

**Comment by bit3725** [comment]
@philippe44 Thanks for your amazing work!

**Comment by philippe44** [comment]
YW
