### ISSUE TITLE
airupnp-win no playback on sonos

### ISSUE THREAD

**Issue by PabloSTL** [philippe44/AirConnect#169]
Hi -
Very cool project!
When I run this on windows, there is not any audio from sonos:1 device. The sonos app displays error message "unable to connect to 192.168.0.110:64123.

I am able to see the virtual air play device on both itunes on my windows device as well as on my iphone, but neither results in any sound from sonos, 
log below

thank you for looking at this!

[airconnect log.txt](https://github.com/philippe44/AirConnect/files/3287213/airconnect.log.txt)

**Comment by philippe44** [comment]
Very likely your windows firewall is blocking airupnp-win. Add an entry in firewall

**Comment by PabloSTL** [comment]
you are exactly correct. fixed. 
thank you so much!
