### ISSUE TITLE
aircast ignoring device definitions in config

### ISSUE THREAD

**Issue by bjeanes** [philippe44/AirConnect#17]
This manifests 2 ways:

`aircast -i castconfig.xml` generates a config file but exits before scan occurs, so the config file has no devices listed. `aircast -x castconfig.xml -I` stays up and performs discovery but still doesn't add device definitions.

If I do `airupnp -i pnpconfig.xml` I am able to generate device definitions (and successfully disable/rename certain ones). If I use the `<device>` definitions there as a guide and manually add the the Chromecast/Google Home devices' MAC addresses to my aircast config, they seem to be ignored and all devices are discovered and enabled, regardless of config's names or enabledness.

**Comment by philippe44** [comment]
Good catch - It's corrected in 0.1.3.2.

**Comment by bjeanes** [comment]
Confirmed! It's working now. Thanks for the fast turn-around. What a beautiful sight:

![2017-12-07 at 4 19 pm](https://user-images.githubusercontent.com/2560/33699961-7e1f171c-db6a-11e7-9fee-7df73056f4d1.png)
