### ISSUE TITLE
Updater/Installer Script for Linux

### ISSUE THREAD

**Issue by FaserF** [philippe44/AirConnect#170]
Hi,

I have created an simple updater/installer script (both in one script). Maybe you want to include in into your github?
The Bash Script is attached below
[updater-installer.txt](https://github.com/philippe44/AirConnect/files/3297210/updater-installer.txt)

**Comment by philippe44** [comment]
Thanks - I will incorporate that soon

**Comment by philippe44** [comment]
Integrated, thanks
