### ISSUE TITLE
_raop._tcp entities, but no _airplay._tcp

### ISSUE THREAD

**Issue by Juggler00** [philippe44/AirConnect#171]
Running the latest version (0.2.10.2) on a Raspberry Pi. From the CLI, I see AirConnect finds all my Google devices. I have a mDNS discovery app that shows all of the advertised protocols; from this I can only see _raop._tcp advertised for each Google device, no _airplay._tcp.

On my Mac, I can see and stream to all of the found devices. However, none of my iOS devices see any of these.

**Comment by philippe44** [comment]
Not fully clear. On your Mac, using iTunes (eg) you can stream to AirConnect which runs on the Pi or does AirConnect run on the Mac for that test? You might have an issue with Avahi (or another mDNS) being in exclusive mode on the Pi (disallow-other-stacks) and preventing AirConnect from broadcasting. Or your router is stopping the multicast traffic that comes from your Pi from being reflected on the WiFi interface

**Comment by Juggler00** [comment]
My apologies... after much more digging/logging it turns out it was a networking issue. Everything is working as expected. Thank you for an amazing util!
