### ISSUE TITLE
Act as audio out

### ISSUE THREAD

**Issue by mareeekkkk** [philippe44/AirConnect#172]
Hi,

Would it be possible to get the audio stream that goes out via upnp also to play on the host device? E.g. having a RPi running AirConnect with Sonos Speakers and use the Pi to connect to a separate amp for a subwoofer?

Thank you

**Comment by philippe44** [comment]
No it's not possible and you will not have synchronization anyway

**Comment by philippe44** [comment]
Closed for inactivity
