### ISSUE TITLE
Core dump on initial launch

### ISSUE THREAD

**Issue by cowieson** [philippe44/AirConnect#177]
This issue may be DOA due to the (apparent) lack of available detail, but here goes: 

I've cloned the latest version of this repo on a CentOS 6.10 server, and attempted to run airupnp-x86-64-static. 

Upon manual execution I receive the following: 

```
./airupnp-x86-64-static
[13:43:41.176702] main:1289 Starting airupnp version: v0.2.10.2 (May 28 2019 @ 16:42:15)
[13:43:41.177025] main:1297 no config file, using defaults
[13:43:41.228863] Start:1017 Binding to 192.168.0.10:49152
Segmentation fault (core dumped)
```

I've tried increasing the log level (`-d all:sdebug`) and writing the output to a file, but no further detail was available in either case. 

I've also tried binding to 127.0.0.1, with the same results (the above output was with no address specified at all; it picks up my main ethernet interface IPv4 address on its own). 

Possibly relevant: to be able to execute the static binary at all, I had to export `LD_LIBRARY_PATH` as `/usr/lib64`. 

Can you advise/is there anything else I should try - or any more info I can provide to debug this issue?

**Comment by philippe44** [comment]
do you have dbg installed and do you know how to use it? I can build a version with debug symbols

**Comment by cowieson** [comment]
I'm afraid I neither have it installed nor do I know how to use it. 

However, I was having a look at this issue last night again - I have a suspicion that it does have to do with glibc versions; when running the non-static executable, I receive error messages about not finding glibc-2.14 or glibc-2.15. CentOS 6 only has glibc-2.12 available in the main repos. 

I tried compiling glibc-2.15 but ran out of time last night - before I return to that, could you confirm whether it may indeed be the issue and whether or not it might be possible to compile airupnp against glibc-2.12 by any chance?

**Comment by philippe44** [comment]
if you know how to compile, you should be able to use gdb. I just to know where it crashes

**Comment by cowieson** [comment]
OK - I've installed gdb. As you mention, if you're able to build a version with debug symbols, I'll try running that and post the output.

**Comment by philippe44** [comment]
here you go https://www.dropbox.com/sh/a3i176k2y7x50r6/AABe-7NDRwIeJ3DfDDWt6ApPa?dl=0

**Comment by cowieson** [comment]
OK, 
Here are my results so far:

Running the static: 
```Reading symbols from /opt/AirConnect/bin/debug/airupnp-x86-64-static...done.
(gdb) run
Starting program: /opt/AirConnect/bin/debug/airupnp-x86-64-static
[11:41:23.768993] main:1289 Starting airupnp version: v0.2.10.3 (Aug 18 2019 @ 12:11:24)
[11:41:23.769326] main:1297 no config file, using defaults
[11:41:23.822313] Start:1017 Binding to 192.168.0.10:49152
warning: the debug information found in "/usr/lib/debug//usr/lib64/libcrypto.so.1.0.1e.debug" does not match "/usr/lib64/libcrypto.so" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64/libcrypto.so.1.0.1e.debug" does not match "/usr/lib64/libcrypto.so" (CRC mismatch).


Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
Missing separate debuginfos, use: debuginfo-install openssl-devel-1.0.1e-58.el6_10.x86_64
(gdb)
```

Running the standard version: 
```Reading symbols from /opt/AirConnect/bin/debug/airupnp-x86-64...done.
(gdb) run
Starting program: /opt/AirConnect/bin/debug/airupnp-x86-64
/opt/AirConnect/bin/debug/airupnp-x86-64: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/AirConnect/bin/debug/airupnp-x86-64)
/opt/AirConnect/bin/debug/airupnp-x86-64: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /opt/AirConnect/bin/debug/airupnp-x86-64)

Program exited with code 01.
```
Having done some research, unfortunately it would appear (as far as I can tell) that there does not currently exist a debuginfo package for openssl-devel-1.0.1e-58 (yet?) - which is a bit unhelpful as I'm sure there may well be more useful output from the openssl debuginfo as per the above. 
Unless I'm missing something, I don't believe the above adds any further useful info so far?

**Comment by philippe44** [comment]
Try version 0.2.12.x. I just relazed that previous version did not include the openssl stack in static mode.

**Comment by cowieson** [comment]
Excellent - that seems to have done the trick! It's now up and running nicely. Many thanks!
