### ISSUE TITLE
protocolInfo for Pioneer/Pharos/Play-Fi

### ISSUE THREAD

**Issue by timtn** [philippe44/AirConnect#178]
I've got a Pioneer Play-Fi speaker that I'm trying to use without much success and bunch of  `buffer_put_packet:61` errors similar to https://github.com/philippe44/AirConnect/issues/173

The speaker is showing as a **Phorus-Renderer**, and seems to have limited audio support:
```
http-get:*:audio/x-flac:*
http-get:*:audio/flac:*
http-get:*:audio/aac:*
http-get:*:audio/mpeg:*
http-get:*:audio/vnd.dlna.adts:*
http-get:*:audio/mp4:*
http-get:*:audio/3gpp:*
http-get:*:audio/x-hx-aac-adts:*
```

While it says that it supports, flac, I've only been able to stream mp3s over UPnP using JRiver's Media Center (and only when the 'DLNA' option is ticked in the advanced settings). The speaker does seem to support flac while using the proprietary DTS Play-Fi app, but I have been unable to find a way to do so over UPnP.

From playing around with Wireshark, I believe it needs:
```
http-get:*:audio/mpeg:DLNA.ORG_PN=MP3
```
in the protocolInfo in order for it to play mp3s over UPnP.
Is there an easy way to change the protocolInfo without recompiling to test this theory?

(AirConnect is working great with my Sonos on the same network, so I don't believe it's a network or firewall issue)

**Comment by philippe44** [comment]
Can you still send a log? I'd like to know if the player queries the AirConect webserver. The DLNA option I set for MP3 is precisely: 
"http-get:*:audio/mp3:DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000"

**Comment by timtn** [comment]
AirConnect logs always look something like this:
```
[00:53:41.641731] handle_rtsp:365 [0x7fe82fe00820]: received SET_PARAMETER
[00:53:41.641785] handle_rtsp:563 [0x7fe82fe00820]: responding:
RTSP/1.0 200 OK
Audio-Jack-Status: connected; type=analog
CSeq: 8


[00:53:45.715954] buffer_put_packet:613 [0x10ac32000]: fill [level:513] [W:4879 R:4367]
[00:53:46.029400] ActionHandler:491 [0x10abccb10]: uPNP playing
[00:53:49.802470] buffer_put_packet:613 [0x10ac32000]: fill [level:1025] [W:5391 R:4367]
[00:53:53.890246] buffer_put_packet:613 [0x10ac32000]: fill [level:1537] [W:5903 R:4367]
[00:53:57.977552] buffer_put_packet:613 [0x10ac32000]: fill [level:2049] [W:6415 R:4367]
[00:54:02.064589] buffer_put_packet:613 [0x10ac32000]: fill [level:2561] [W:6927 R:4367]
[00:54:06.150663] buffer_put_packet:613 [0x10ac32000]: fill [level:3073] [W:7439 R:4367]
[00:54:10.237930] buffer_put_packet:613 [0x10ac32000]: fill [level:3585] [W:7951 R:4367]
...
```
and just continues on like that.

Haven't really been able to manually POST the SetAVTransportURI with AirConnect since the meta data gets overwritten on pause/play, but I am able to play other mp3s over the speaker if I tweak protocolInfo. 
It seems like this strange speaker really wants `/mpeg:DLNA.ORG_PN=MP3` in addition to the other DLNA options. No audio if I swap `/mpeg` for `/mp3` or delete the `DLNA.ORG_PN=MP3` options.

**Comment by pwt** [comment]
FWIW, those logs look normal to me (for INFO level logging).

Have you tried setting the airupnp codec to MP3 instead of FLAC, using something like `-c mp3:320` on the command line?

**Comment by philippe44** [comment]
@pwt: I think what's happening is that the player never do a HTTP GET because it does not like the DLNA option. 
@timtn: what version do you use, so I can make a special build

**Comment by timtn** [comment]
>Have you tried setting the airupnp codec to MP3 instead of FLAC, using something like -c mp3:320 on the command line?

Yes, but I don't get any audio out of the speaker. As I mentioned above, I can replicate the issue using some POST commands to stream audio to the device. It only seems to work with the `/mpeg` and `DLNA.ORG_PN=MP3` options in `protocolInfo`, both of which are missing in AirConnect.

This does not appear to be an AirConnect specific issue, but rather an issue with the way the speaker handles UPnP since it has difficulties playing audio with other apps/projects.
Not sure if this issue is widespread with all 'Play-Fi' speakers, but I wouldn't recommend them because of this and other issues.

> @timtn: what version do you use, so I can make a special build

Thanks! I'm using the osx version.

**Comment by philippe44** [comment]
Try latest version (0.2.12.x). Save a new config file and you should see the new parameter

**Comment by timtn** [comment]
Thank you so much @philippe44!
I was able to make the necessary changes to protocolInfo and it is working perfectly for mp3s!

Here's the string I used for my Pioneer/Phorus speaker if anyone else has the same issue:
```
<mp3>http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</mp3>
```

Now I just need to figure out the correct string for flac!

**Comment by timtn** [comment]
Just heard back from Play-Fi support. It seems like none of the other formats are enabled and mpeg/mp3 is only there as an artifact of another protocol the speaker uses.

I'll be marking this issue as resolved for now since we can still use the mp3 with the config option in 0.2.12.x+.
