### ISSUE TITLE
Sample config.xml

### ISSUE THREAD

**Issue by mariagwyn** [philippe44/AirConnect#18]
Can you provide a sample (or default) xml file that can then be customized? That would help those of us a little less tech savvy. In my case, I am running this on OSX (and it works very well, thank you!). I want to create a simple startup and config file so that I can install this on family computers of users who are not tech savvy at all. A sample xml would help considerably.

Thanks.

**Comment by mariagwyn** [comment]
(I already have the startup file, I just want to see an config.xml with all the parameters laid out so I can modify).

**Comment by philippe44** [comment]
I'm not sure I understand, if you launch the application with -i <file> you'll get a file with all potential parameters for existing players set to their defaults

**Comment by mariagwyn** [comment]
I see the parameters listed with -i. What I don't see is a generated .xml file that I can then customize.

**Comment by philippe44** [comment]
no, you see the help if you just type "airupnp-osx-multi -i" because you are typing a wrong syntax command. You have to type "airupnp-osx-multi -i <some_filename.xml>" and then <some_filename.xml> will be filled with all default parameters. Please look at the help!
