### ISSUE TITLE
Error that Makes AirUPN-OSX-Multi Crash after Pausing/Resuming

### ISSUE THREAD

**Issue by AnderCrafter** [philippe44/AirConnect#180]
Airupnp on OSX El Capitan for Sonos often hangs after Stopping, Resuming or changing the playback head (or song).

This is the first time i have a error that is really logged:
https://pastebin.com/hBMM0z0B

I included everything that seemed interesting as i didn't want to send what i am hearing with it.

**Comment by AnderCrafter** [comment]
There is a possibility this has been repaired by upgrading the Software on my Computer, i will notify you if the issue persists. My Old version was from April 2019

**Comment by philippe44** [comment]
Closed for inactivity
