### ISSUE TITLE
Sonos grouping: airupnp can't 'hand over' the AirPlay stream to a different speaker

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#181]
Not sure if this is fixable, but I'll report it just in case:

**Test Scenario:**
1. Start AirPlay playback (via airupnp) to Room-A speaker
2. Use Sonos app to group Room-B speaker with Room-A: playback works fine to both speakers
3. Then, remove Room-A speaker from the group

**Test result:**
- Expected behaviour: playback continues on Room-B and stops on Room-A
- Actual behaviour: playback stops on both speakers.

Essentially, the original speaker to which the AirPlay stream was sent always has to remain part of the group for playback to continue. You can't use grouping to 'hand over' a playback stream as you can with other Sonos sources.

**Comment by pwt** [comment]
Hi @philippe44. Thanks for taking a look. I guessed it might be tricky to fix.

I'm not sure how Sonos itself implements the handover for other sources: it seems to be able to hand over the stream URL to a new speaker while maintaining audio sync.

**Comment by philippe44** [comment]
I looked at that and it's really too complicated to do

**Comment by pwt** [comment]
Understood. Thanks for thinking about it.
Let's close this as 'won't fix'.
