### ISSUE TITLE
Sonos speaker renames are not picked by airupnp

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#182]
Minor issue: if I rename a Sonos speaker (change its 'Room' name in the Sonos app), this change is not picked up by airupnp until it's been restarted.

Might be worth fixing it it's an easy change, otherwise not a big deal.

**Comment by philippe44** [comment]
I've tried to do something, but it's more complicated than it seems b/c you have to take into account the fact that user have set a name in config file, in which case name change shuld not take precedence

**Comment by pwt** [comment]
Thanks! A quick test indicates that this is working fine in v0.2.13.0. I don't over-write room names in the config file, so I haven't tested that part. Let me know if you do want me to test this.

**Comment by philippe44** [comment]
That would be great if you could help with testing (w/ and w/o a config file, w/ and w/o default name)

**Comment by pwt** [comment]
I've tested the scenarios above and they're working fine. Better than the Sonos iOS app, actually, which doesn't update one of its views! :)

Thanks again.
