### ISSUE TITLE
UPnP init failed: -203

### ISSUE THREAD

**Issue by IT-Lueg** [philippe44/AirConnect#183]
![airconnect](https://user-images.githubusercontent.com/4661044/63929682-2ba6ee00-ca52-11e9-82ed-49daa60759b1.JPG)

What am I doing wrong ?

Raspberry Pi 4
Raspbian Buster

**Comment by pwt** [comment]
I can't help with the error you're seeing, but if you're interested you could try my dockerized version of airupnp-arm: https://github.com/pwt/docker-airconnect-arm

This is verified to work properly on RPi 4 / Raspbian Buster.

**Comment by IT-Lueg** [comment]
Okay, cool :)

Unfortunately I don't have any experience with Docker.
Can you explain to me how to install it ?

what's the difference if it runs with Docker or not ?

**Comment by pwt** [comment]
Ah, OK. I had to install Docker from a non-stable release channel to get it running on Buster, not something I'd recommend to the uninitiated. I'm sure this will be fixed shortly. However, if you want to investigate, start at: https://docs.docker.com/install/

AirConnect works identically under Docker, it's just a much more convenient packaging & execution model (imho).

**Comment by philippe44** [comment]
-203 is a socket binding problem. So basically AirConnect cannot use your ethernet/wifi connection and port combination. Is there anything (firewall or I don't know what) preventing application to use it?

**Comment by IT-Lueg** [comment]
There is a Unifi-POE-Switch and a Unifi Security Gateway.
I enabled UPnP... now this works, thanks.
**But** I can't find the devices on Airplay. Do you have an Idea what I can do ?

![upnp](https://user-images.githubusercontent.com/4661044/63999157-22298e80-cb03-11e9-8531-aa5a9ea48950.JPG)
![airconnect](https://user-images.githubusercontent.com/4661044/63999169-25247f00-cb03-11e9-8d4c-b2c1b9a915ce.JPG)

**Comment by IT-Lueg** [comment]
Ohhh sry it's my fault. **its working :)**

![airconnect](https://user-images.githubusercontent.com/4661044/64000353-d7f5dc80-cb05-11e9-87bd-a83f2418d8b8.JPG)
