### ISSUE TITLE
AirPlay Device

### ISSUE THREAD

**Issue by Maercle** [philippe44/AirConnect#185]
Hi,
I have a question concerning identified devices in the AirPlay list. 
I'm using a RasPi3+ with the current Raspbian and a new AirConnect installation. Everything works fine but when I open the AirPlay device list on the iPhone an additonally device is shown, only by the IP-Adress not with a special name. I suspected that the device is the rasperry pi itself. But when I plug in a speaker and connect to the device there is no sound. Is it possible that the device is the raspberry pi and how can I get sound with that connection?

**Comment by philippe44** [comment]
It's probably shairport indeed. But AFAIK? it requires ciphering to be enabled (as all software players), so check that option for this player's setting in my plugin's setting (in LMS)

**Comment by philippe44** [comment]
Close for inactivity
