### ISSUE TITLE
Nothing happening (Sonos Play:1)

### ISSUE THREAD

**Issue by eramdam** [philippe44/AirConnect#186]
I'm trying to use AirConnect with a Sonos Play:1 (pre AirPlay 2) and I can't seem to make it work. What puzzles me is that I have no useful logs showing no matter how hard I try.

Here are the (I assume?) relevant informations:
- MacOS 10.14.6
- Raspberry Pi 3 Model B Plus Rev 1.3 / Raspbian GNU/Linux 9.6 (stretch) armv7l

Log on Raspberry Pi
```
pi@pi:~/Desktop/AirConnect/bin $ ./airupnp-arm
[18:29:20.424402] main:1305 Starting airupnp version: v0.2.13.1 (Aug 30 2019 @ 21:02:57)
[18:29:20.424762] main:1313 no config file, using defaults
[18:29:20.426800] Start:1033 Binding to 192.168.86.241:49152
```

Log on macOS
```
<master!> » ./airupnp-osx-multi -l 1000:2000
[18:29:56.996908] main:1305 Starting airupnp version: v0.2.13.1 (Aug 30 2019 @ 21:03:34)
[18:29:56.998534] main:1313 no config file, using defaults
[18:29:57.000248] Start:1033 Binding to 192.168.86.208:49152
```

Sonos informations:
- Software version: 51.1-66240
- Software date: 2019-06-24 12:51:57.121277
- Hardware version: 1.20.1.6-1

**Comment by philippe44** [comment]
It works but nothign is discovered. You probably have a firewall that prevents AirConnect to access your network or you have 2 ethernet interfaces on your Mac and it's using the wrong one

**Comment by eramdam** [comment]
@philippe44 Firewall is off on both the Mac and the Raspberry Pi. And as far as I can tell it's using the right ethernet interface
![Screen Shot 2019-09-07 at 7 54 19 PM](https://user-images.githubusercontent.com/1409924/64482584-4e9b7580-d1a9-11e9-911c-ae9f6c19f71e.png)

**Comment by philippe44** [comment]
What happens often as well is a router that filters out multicast

**Comment by LanceSandino** [comment]
I have the same issue, it only sees my Samsung TV.
I even created a config file but it doesn't even seem to be using it....

![image](https://user-images.githubusercontent.com/1300195/64491177-e7bea080-d22a-11e9-9a0b-53767028ef3f.png)

**Comment by eramdam** [comment]
> What happens often as well is a router that filters out multicast

Argh, it seems Google WiFi doesn't support that (what the heck, Google?) 
https://support.google.com/wifi/forum/AAAARapEvqgQsbUJ_itQMo/?hl=en-CA

Would there be a way to work around this? Like, if I knew the IP of the Sonos player directly?

**Comment by LanceSandino** [comment]
^^ so I have google wifi too -- I rebooted the sonos and it popped up....

**Comment by eramdam** [comment]
@LanceSandino I tried that..no dice. Oh well, at least I know who to blame now (Google) :D

**Comment by airsquared** [comment]
I've been having this issue too with the same setup(Sonos Play:1 w/ a Raspberry Pi and a Google WiFi).

**Comment by philippe44** [comment]
I've tried to hack the upnplibrary and add a unicast dedicated search to specific devices. It's supposed to be a upnp 1.1 feature and unfortunately, no device seem to support it, they don't respond.

**Comment by LanceSandino** [comment]
Should have clarified, I did it on my Mac.... Just made sure I didn't have the process running a bunch of times...

Didn't work on my Synology or my Ubuntu VM (on server with VMware)

**Comment by philippe44** [comment]
Closed for inactivity

**Comment by LanceSandino** [comment]
Just want to add an update .... I hadn't used this in awhile and pulled the latest code.... created a config (because I have to disable my sonos beam & TV that it finds) and boom it works great! :)

![C5E859ED-303C-4A26-845C-0BD836070DE5_1_102_o](https://user-images.githubusercontent.com/1300195/69107245-55aaf380-0a36-11ea-91e8-f1317c1ba16c.jpeg)


This is my config

```
<?xml version="1.0"?>
<airupnp>
<common>
<protocolInfo>
<pcm>http-get:*:audio/L16;rate=44100;channels=2:DLNA.ORG_PN=LPCM;DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</pcm>
<wav>http-get:*:audio/wav:DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</wav>
<flac>http-get:*:audio/flac:DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</flac>
<mp3>http-get:*:audio/mp3:DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</mp3>
</protocolInfo>
<enabled>1</enabled>
<max_volume>100</max_volume>
<codec>flc</codec>
<metadata>1</metadata>
<artwork></artwork>
<latency>1000:2000</latency>
<drift>0</drift>
</common>
<main_log>info</main_log>
<upnp_log>info</upnp_log>
<util_log>warn</util_log>
<raop_log>info</raop_log>
<log_limit>-1</log_limit>
<device>
<udn>uuid:UID</udn>
<name>[TV] Living room+</name>
<mac>bb:bb:37:00:00:00</mac>
<enabled>0</enabled>
</device>
<device>
<udn>uuid:RINCON_UID</udn>
<name>Kitchen</name>
<mac>bb:bb:ca:00:00:00</mac>
<enabled>1</enabled>
</device>
<device>
<udn>uuid:RINCON_UID</udn>
<name>Living Room</name>
<mac>bb:bb:ca:00:00:00</mac>
<enabled>0</enabled>
</device>
</airupnp>
```

and this is the command I run:

```
$PWD/bin/airupnp-x86-64-static -b 10.0.0.1:49155 -l 1000:2000 -d all=info -x $PWD/config.xml
```

This is on my ubuntu server :)
