### ISSUE TITLE
How do I get metadata to show up on the Sonos app?

### ISSUE THREAD

**Issue by airsquared** [philippe44/AirConnect#187]
How can I get the album art and song name/artist to show up on the Sonos app?

**Comment by philippe44** [comment]
There is no great answer to that: the only option is to use mp3 to re-encode audio (see README) and, when ICY is supported (which is the case for Sonos), you'll get some metadata, but not image as Sonos does not support all ICY extension.
It's the nature of such bridge: AirPlay sends a single long stream of audio and an out-of band metadata information when it changes, but UPnP is more oriented to be a file-by-file playback and metadata is set together with a new track. 
So the trick is to simulate a webradio were some support this in-band metadata update

**Comment by airsquared** [comment]
Ok, I'll try that. Thanks!
