### ISSUE TITLE
Volume of grouped Sonos speakers is not respected when AirConnect stream's volume is changed

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#188]
Sonos speakers in groups have their volumes set independently. When an AirConnect stream to a Sonos group has its the volume changed, the volume of grouped speakers is not correctly respected.

**Test Secanario**:

- Room A and Room B are grouped; Room A is the group coordinator
- AirConnect is playing a stream to Room A
- Room A volume is set to 50; Room B volume is set to 0
- Increase the volume on the sending device by one 'click'

**Test Result**:
- Room A volume increases to 60, but Room B volume jumps immediately to 44

I think the expected behaviour here should be a **scaled** increase in the volumes of both speakers, as would happen if one used the 'master' Sonos app volume control. If this is not possible, change only the volume of the group coordinator (Room A).

**Comment by pwt** [comment]
A similar issue occurs when a stream is started to grouped speakers. If Room B's volume is set to 0, it will jump to something much louder if the sending device is set louder.

I think this relates to the fact that when a stream is started (regardless of grouping), the speakers adopt the volume of the sending device. Personally, I'd prefer that the sending device adopt the volume setting of the speakers, but this may be incompatible with the AirPlay protocol.

**Comment by philippe44** [comment]
Yes, I mentionned that in the README. There is not much I can do unfortunately. Sonos does not give you flexible control on group volume. There is one function call, and that changes the volume of all devices to the same level, as you've observed, there is no group function to do relative change. To change them individually, you would need to address group member individually but I do not keep a list of group members. When a group is detected, all slaves are removed from AirConnect and their context destroyed. So changing that would be a major effort.

**Comment by philippe44** [comment]
okay, I've tried something in 0.2.20.0. Need more tests, so that would be great if you could give it a try. I cannot guarantee that you won't see 100% randomly, so be cautious.

It was/is really complicated, so you own me one on this one (just kidding)

**Comment by pwt** [comment]
Excellent — thanks so much for working on this. I’m away from my home base for a couple of weeks, so I won’t be able to do much testing, but I’ll get straight onto it once I’m back.

**Comment by pwt** [comment]
I'm now back at home and I've started testing with airupnp v0.2.21.2. Working well so far. I'll close this issue and open new ones for anything that comes up in testing.

I know this was a major enhancement and I'm very grateful for your work on it. I'm also impressed you were able to deliver it so quickly. Great work!
