### ISSUE TITLE
Devices disappear after ~1-2 Minutes

### ISSUE THREAD

**Issue by IT-Lueg** [philippe44/AirConnect#189]
Airconnect runs on a Raspberry Pi 3B.
When I restart the service (service airconnect restart) I see my Sonos speakers on my iPhone.

![IMG_1301](https://user-images.githubusercontent.com/4661044/64587070-799aea80-d39e-11e9-8d34-32ec63468d68.PNG)

The service runs with the following settings...

```
[Unit]
Description=AirUPnP bridge
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
ExecStart=/var/lib/airconnect/airupnp-arm -l 1000:2000 -z -f /var/log/airupnp.log
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target
```
But after ~1-2 minutes the devices simply disappear again.

![IMG_1302](https://user-images.githubusercontent.com/4661044/64587128-99caa980-d39e-11e9-96ef-020e6c6ec124.PNG)

I use a unifi network.
IT looks like this...

![Untitled Diagram](https://user-images.githubusercontent.com/4661044/64587218-de564500-d39e-11e9-805b-5597f529da56.png)

UPnP is enabled
![UPnP](https://user-images.githubusercontent.com/4661044/64587327-4c027100-d39f-11e9-8e33-c520ab32f297.JPG)

mDNS is enabled
![mDNS](https://user-images.githubusercontent.com/4661044/64587330-53297f00-d39f-11e9-83f3-6ac614af848b.JPG)

Multicast is enabled on my APs
![mDNS-APs](https://user-images.githubusercontent.com/4661044/64587346-62103180-d39f-11e9-8588-d1978d281b4c.JPG)

and I tried it with IGMP-Snooping On & Off
![IGMP Snooping](https://user-images.githubusercontent.com/4661044/64587353-6ccac680-d39f-11e9-8a34-e7ed01454b48.JPG)

This is my Log...

[airupnp.log](https://github.com/philippe44/AirConnect/files/3593907/airupnp.log)

**What am I doing wrong ???**

**Comment by philippe44** [comment]
Your players (especially Esszimmer) explicitely send a UPnP disconnect, so AirConnect removes them. I Don't know why they do that

**Comment by IT-Lueg** [comment]
Is it this ?
![disconnect](https://user-images.githubusercontent.com/4661044/64670460-774f9380-d465-11e9-8d27-00a0e5d4a50c.JPG)

They're all Sono's speakers.
"Esszimmer" is a Sonos-Playbar.

Is there any way to do something about it?

**Comment by IT-Lueg** [comment]
And if "Esszimmer" sends a UPnP disconnect, why do **all** devices disapear ?

**Comment by philippe44** [comment]
I’ve not looked at the log in full details, but they all seem to disappear at some point

**Comment by IT-Lueg** [comment]
Can you take a closer look at it as soon as you have time?

Today I will try to turn off the device "Esszimmer" and test if it works.

**Comment by IT-Lueg** [comment]
soooo... I unplugged the "Esszimmer" Speaker and tried it again.

If i restart the Service everything works.
But after some time all the Speakers disappear.

I created a new (smaller) log.
Can you please look into it ?

[airupnp.log](https://github.com/philippe44/AirConnect/files/3600321/airupnp.log)

**Comment by marekbell** [comment]
@IT-Lueg I think it's the IGMP snooping on Unifi equipment.  Try turning it off again, and then restarting your Sonos.  It might work after that.

**Comment by philippe44** [comment]
Closed for inactivity
