### ISSUE TITLE
AirUPNP: UPNP volume control erroneous when rapidly changing AirPlay host volume setting

### ISSUE THREAD

**Issue by Gummibando** [philippe44/AirConnect#19]
If you change the volume in the AirPlay host app (e.g. iTunes) rapidly (like, moving the iTunes volume slider instantly from left to right and vive versa) , then the UPNP volume control can't "catch up" and starts to "stutter" and gets unsynchronised from the AirPlay host volume setting.

If you change the AirPlay host volume slowly (e.g., using the iTunes volume up/down keyboard shortcuts), the UPNP volume is adjusted correctly.

[macOS High Sierra 10.13.2, airupnp-osx-multi 0.1.3.2, Naim NAC-N 172 XS streaming pre-amp]

**Comment by philippe44** [comment]
Yes, this is unfortunately an issue with volume management which is a consequence of having bi-directional volume synchronization. There is already some filtering used, but it's not enough for super rapid volume chnages. I don't have a solution for that

**Comment by Gummibando** [comment]
Can you please describe the filtering currently in place?

**Comment by philippe44** [comment]
AirPlay sends a volume command (-144, -30.0 ... 0.0) which is transformed into a  UPnP volume command (0..100). Every .5s, the UPnP player is polled for volume change, but whetver the volume has been changed "locally" or has changed as a result of an AirPlay request is impossible to tell. When polling indicates that volume has changed, it's forwarded back to AirPlay and filtered out if the change happens less than a second after the most recent AirPlay command

**Comment by Gummibando** [comment]
The problem appears to be only the AirPlay -> UPNP direction. Is it somehow possible to "collect" the AirPlay volume info into a buffer and then – when the timestamps of the values are within a certain time frame – drop all value changes except the most recent one?

Also, if I read the log readout correctly (see below), the UPNP volume info seems to be queued and then sent in rapid succession to the UPNP device. Alternatively, maybe this could be filtered out in the same way as mentioned above?

```
[12:17:46.587795] HandleStateEvent:317 [0x100078530]: UPnP Volume local change 43
[12:17:46.800381] HandleStateEvent:317 [0x100078530]: UPnP Volume local change 40
[12:17:46.888259] HandleStateEvent:317 [0x100078530]: UPnP Volume local change 41
[12:17:47.085797] HandleStateEvent:317 [0x100078530]: UPnP Volume local change 38
[12:17:47.301451] HandleStateEvent:317 [0x100078530]: UPnP Volume local change 31
[12:17:47.523597] HandleStateEvent:317 [0x100078530]: UPnP Volume local change 40
```

**Comment by philippe44** [comment]
The commands are not queued, but what happens is you see all the "local changes" that are UPnP echos of the commands sent by iTunes. Most of these echos are filtered out and iTunes is not notified if the last time it sent a command was less than a second ago. I'm surprised that it's creating an issue on your player. On my tests, even if the UPnP device does not follow, it is sent all the commands and yes, it will shutter for a small while but then when you stop moving back and forth the iTunes volume, the last echo will be sent to iTunes which shoudl match its last request, so nothing bad should happen.

**Comment by Gummibando** [comment]
I will try to capture some UPNP traffic between the AirPlay host and the Naim streamer over the weekend (Debookee, ftw.). Let's see if this brings some light into the matter.

Just as a sidenote. Your project is just fantastic. You solved a problem which Naim was never able – or willing – to implement. Love it.

**Comment by philippe44** [comment]
Thank you :-)
