### ISSUE TITLE
Provide Consistent Releases

### ISSUE THREAD

**Issue by jacobleonwoffenden** [philippe44/AirConnect#191]
Hi @philippe44,

Thanks for providing this tool!

I was just wondering if you could provide more consistent releases to GitHub.

For example, I can see on master (e390d8caecb97dd667d71100a7d420eb33b64dde) you've created 0.2.13.1 but on https://github.com/philippe44/AirConnect/releases, it only shows 0.2.1.1.

A small thing I realise, but it allows me to consistently build my AirConnect Docker image (https://github.com/jacobleonwoffenden/container-airconnect/blob/master/Dockerfile#L3)

Thanks!

**Comment by philippe44** [comment]
I'll try to do that from time to time
