### ISSUE TITLE
Speaker loses '+' after its AirConnect name

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#196]
Slightly odd (minor) problem: one of my Sonos speakers (a Sonos One) loses the '+' appended to its zone name. The speaker is called 'Diner' in Sonos, and its AirConnect name is usually 'Diner+', but recently the AirConnect name has become just 'Diner'.

I have a hunch this is to do with the grouping/volume changes, but that may be wrong! Restarting airupnp corrects the issue.

**Comment by philippe44** [comment]
Is it now always loosing the + or is it from time to time when you create/delete groups

**Comment by pwt** [comment]
Not clear yet. It's also happened with one of my stereo pairs, without any grouping actions being performed. I'll have a play around and try to find a definite reproducer.

**Comment by pwt** [comment]
Using airupnp v0.2.21.3, the log events for instances of this issue are of the form:
```
[16:01:21.546893] UpdateThread:765 [0x992c0]: Device name change 192.168.1.32 - Sonos One Diner
[16:01:21.799422] UpdateThread:765 [0x992c0]: Device name change Diner 192.168.1.32 - Sonos One
```
I'm not sure what's triggering AirConnect to think that a speaker's name has changed when it hasn't. My other Sonos One is exhibiting the same behaviour.

**Comment by philippe44** [comment]
Do you still see that issue?

**Comment by pwt** [comment]
I assume it's still there, but I haven't seen it recently, nor was I able to find a reproducer. Probably best if I close the issue for now.
