### ISSUE TITLE
Problem with Airconnect 

### ISSUE THREAD

**Issue by fpichelb** [philippe44/AirConnect#199]
Hi Philippe,

first of all this Project  is so nice.

But now straight to my issue. For a few Days i try to install it on my Go flex home. I have to compile it from scratch, because your binarys wont work for that little fucker. 

It runs Gcc v 4.2.3
openssl 0.9.8
libc 2.5

i already fixed some Problems with pragma gcc diagnostics not allowed inside functions by commenting them out. And did the same with SO-REUSEPORT undeclared in mdnssd-min.c line 1068.

But know i run into :

../tools/sslsym.c:110: error: conflicting types for 'SSLv23_client_method'\
/opt/include/openssl/ssl.h:1515: error: previous declaration of 'SSLv23_client_method' was here\
../tools/sslsym.c:115: error: conflicting types for 'SSL_CTX_new'\
/opt/include/openssl/ssl.h:1344: error: previous declaration of 'SSL_CTX_new' was here\
../tools/sslsym.c:142: error: conflicting types for 'BIO_new_mem_buf'\
/opt/include/openssl/bio.h:625: error: previous declaration of 'BIO_new_mem_buf' was here\
../tools/sslsym.c:146: error: conflicting types for 'AES_cbc_encrypt'\
/opt/include/openssl/aes.h:104: error: previous declaration of 'AES_cbc_encrypt' was here}

and i have no clue how to fix it

**Comment by philippe44** [comment]
So you know what ssl stack is available there?

**Comment by fpichelb** [comment]
In 0.9.8 ?

**Comment by fpichelb** [comment]
Either way I have no clue which stack is available but I could look it up

**Comment by philippe44** [comment]
oh, I see now - sorry I missed you said you're using openssl 0.9.8 ... pretty old stack (not recommended) but anyway. I did these funky macros in sslsym.c to be able to dynamically but manually load the ssl stack, not matter what version. So simply look (in openssl/ssl.h and others) at the prototypes of the functions where your compiler whines and correct them in sslsym.c, it's probably a matter of "const" being used or not which explain the declaration conflict

**Comment by fpichelb** [comment]
Do you have a tip on how to get the libshine.a
it looks like i am to stupid to install shine

**Comment by philippe44** [comment]
What CPU is that?

**Comment by philippe44** [comment]
And libshine is pretty easy to recompile anyway, I think I have it forked on my github

**Comment by fpichelb** [comment]
Arm926EJ-s

**Comment by philippe44** [comment]
[arm5.zip](https://github.com/philippe44/AirConnect/files/3776201/arm5.zip)

**Comment by philippe44** [comment]
Closed for inactivity
