### ISSUE TITLE
Disable adding + to the AirPlay name

### ISSUE THREAD

**Issue by burritosoftware** [philippe44/AirConnect#200]
Hey! I have 3 Chromecasts, and would prefer to have a clean AirPlay menu without having + appended to the names. Is there a configuration to allow this or do I have to manually change each name? If it's not in the program yet, I want to suggest it as a feature.

**Comment by philippe44** [comment]
Kindly RTFM :-)

**Comment by burritosoftware** [comment]
I did read the README, and afaik you can't remove it.

**Comment by philippe44** [comment]
Set the <name> entry

**Comment by philippe44** [comment]
Close for inactivity
