### ISSUE TITLE
Q: only apple?

### ISSUE THREAD

**Issue by RezzZ** [philippe44/AirConnect#201]
I love this! great application that let me stream any audio from my Mac/iPhone to my sonos system directly but unfortunately not all devices at home are from apple. Any thoughts on how to get this working for android devices as well?

Wouldn't it be nice if the sonos devices showed up as cromecast devices as well / instead of airplay devices?

**Comment by philippe44** [comment]
It's impossible to mimic a ChromeCast device due to the way Google signs application running inside CC. You can try some Android apps that allow sending to AirPlay. NOt idea though

**Comment by RezzZ** [comment]
ok, thanks! At least I can properly stream to my speakers/zones now! Cool
