### ISSUE TITLE
Volume max's out at 50% when Airplaying to a Google Home Speaker Group

### ISSUE THREAD

**Issue by markusweldon** [philippe44/AirConnect#203]
Hey Philippe,

First, obligatory thank yous for a great solution in getting Airplay to work with Google cast-able devices.

I read and searched your Wiki before raising the issue I am experiencing. When casting to a group of Google Home speakers, what is happening is the volume on the physical speakers is limited to 50% (example only 2 of 4 lights show on a mini) however the Apple device (iPhone) broadcasting the Airplay music signal has volume set at max (100%).

This problem is specific to Speaker Groups as broadcasting to a individual speaker via Airplay works fine.

I've tried changing the volume of the Google Home speaker group to 0% and then readjusting without resolve, and also adjusting in the group directly via the Google Home app instead increasing it beyond 50% and that works but only temporarily, as when the next song is played in the Music app it resets the Google Home physical speakers in the group back to 50%.

Please let me know if you need any further elaboration?

Ultimately Google Home Speaker Groups are limiting maximum volume to 50%

Thanks again

**Comment by philippe44** [comment]
Have you tried \<media_volume\>

**Comment by mmmarkus85** [comment]
I've tried updating the config_cast.c file <media_volume> to a higher value, but still cannot get the Speaker Group to play any louder than 50%:

Original config line:
XMLUpdateNode(doc, common, false, "media_volume", "%0.04lf", glMRConfig.MediaVolume);

Updated to double:
XMLUpdateNode(doc, common, false, "media_volume", "%0.08lf", glMRConfig.MediaVolume);

Also tested updating to both:
XMLUpdateNode(doc, common, false, "media_volume", "%0.16lf", glMRConfig.MediaVolume);
XMLUpdateNode(doc, common, false, "media_volume", "%1.0lf", glMRConfig.MediaVolume);

No change, same behavior

Terminal Log, shows me adjusting from 0.0 to 1.0 (No volume in Apple Music app, slider adjusted straight through to full volume 1.0) however when the log shows as 1.0 (full) my speakers in the Google Home Mini group are all at 50%:

[19:14:59.590848] handle_rtsp:392 [0x7feb2a5015a0]: received SET_PARAMETER
[19:14:59.590894] handle_rtsp:557 [0x7feb2a5015a0]: SET PARAMETER volume 0.000000
[19:14:59.591165] CastSetDeviceVolume:323 [0x104009960]: Immediate VOLUME (id:143)
[19:14:59.591188] callback:233 [0x104009960]: Volume[0..1] 1.0000
[19:14:59.591251] handle_rtsp:589 [0x7feb2a5015a0]: responding:
RTSP/1.0 200 OK
Audio-Jack-Status: connected; type=analog
CSeq: 92

**Comment by philippe44** [comment]
It's already a double, it's just a matter of formatting the number in the config file (leading 0, 4 digits). I'll try in the coming days, I know I had to do some special volume handling for groups, hence this media_volume (must be between 0 and 1), but I've not used for a long while.

**Comment by philippe44** [comment]
Closed for inactivity

**Comment by Garulf** [comment]
Any update on this? I have my Google Home Speakers set in pair mode (which shows as a group to air connect). These speakers max at 50% when playing.

**Comment by maxexcloo** [comment]
Is there a way to set the default volume as 100%? I don't need a manual config otherwise...

**Comment by lxgr** [comment]
Same here – this is the only thing that prevents me from just running a config-less containerized instance.

**Comment by philippe44** [comment]
hmmm... have you tried -v that does that on the command line?

**Comment by lxgr** [comment]
Oh, I didn't realize there was a default offset! `-v 1` indeed fixes it for me.

Out of curiosity, what's the reasoning behind the default offset of `0.5`?

**Comment by philippe44** [comment]
No I can't remember why, I'd have to think about it more 😄.There was a reason, that I remember, but I can't recall what it was.

**Comment by philippe44** [comment]
Changed in 1.1.6 and above

**Comment by maxexcloo** [comment]
It could be that normal airplay to Apple TV and such from an iPhone is defaulted lower also?
