### ISSUE TITLE
./airupnp-arm: Syntax error: newline unexpected

### ISSUE THREAD

**Issue by bender75** [philippe44/AirConnect#208]
i want to execute the arm binary on my rasperry pi 4, but the executable terminates with
```
➜  ~ ./airupnp-arm -h                                                             
./airupnp-arm: 8: ./airupnp-arm: Syntax error: newline unexpected
```

**Comment by pwt** [comment]
Are you sure you’ve downloaded the binary file? What does `ls -l airupnp-arm` return?

**Comment by bender75** [comment]
oooh sorry my fault - you are right. i downloaded a html file.
