### ISSUE TITLE
Short burst of audio after AirPlay stream has been paused (airupnp with Sonos)

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#211]
Just reporting this for completeness:

I'm observing a minor issue where there is a short (250ms?) burst of audio, emitted from the Sonos player shortly after an AirPlay stream has been paused. I.e., the speaker stops playing for a moment, then there's a short burst of sound.

It appears only to occur when a track is paused before it reaches the end. If the track runs to the end, the audio burst doesn't occur. This behaviour seems repeatable.

I'm streaming with the FLAC codec, and I have latency set to `750:750:f.`

**Comment by philippe44** [comment]
I can't reproduce that. What is the AirPlay source?

**Comment by pwt** [comment]
Interesting. A bit of further testing shows that it's independent of the sending AirPlay device, but instead depends on the receiving Sonos device.

For the devices I've been able to test: my Sonos Connects exhibit the issue, my Play:1 and (second-gen) Play:5 speakers do not.

So, I guess we put this down to a problem on the Sonos end?

**Comment by jonathangreen** [comment]
I see this as well, but only with my Gen 1 Play:5.

**Comment by pwt** [comment]
Thanks for the extra data point. The P:5gen1 is of the same basic Sonos hardware generation as the Connect (ZP90).

**Comment by philippe44** [comment]
Anybody seing the same on P:3? I don't have the issue on mine

**Comment by pwt** [comment]
That's another good datapoint. The P:3 is a later h/w generation than the ZP80/90/100/120 and P:5 gen 1. It adds a 5GHz WiFi radio (to enable surround speaker capability), which is missing in the earlier variants.

**Comment by stephenjharrington** [comment]
Just to (maybe) confuse the issue and as another data point, I tried to reproduce this issue playing a podcast off my iPhone via airupnp (running on an old Mac Mini server) to my old Sonos devices, a stereo pair of Play:5 Gen 1’s and my Connect (ZP90), and no matter how much I play/pause/play I can’t seem to reproduce this issue, no nasty bursts of audio post-pause at all.

Maybe I should try a music track? Is it only music or all audio?

**Comment by jonathangreen** [comment]
Podcasts should do the trick. It's usually podcasts I'm listening to when this happens. Streaming from the Podcast app in iOS. [This](https://github.com/philippe44/AirConnect/files/3894178/Airupnp.Sound.zip) is a recording of what I hear. Note the short burst about 4 seconds after the podcast stops (GitHub doesn't support attaching audio, so I had to zip the m4a before attaching it).  I'm running with latency set to `1000:2000`.

**Comment by pwt** [comment]
@jonathangreen Yes, that's the effect I'm referring to. It happens with multiple sources for me, although not with Spotify (definitely playing over AirPlay via AirConnect), oddly.

I'll reiterate that I don't think is is anything more than a minor wrinkle, just curious as to why it might be happening.

**Comment by philippe44** [comment]
Can I close this one? It feels it's an issue on Sonos' side

**Comment by pwt** [comment]
I've only done minimal testing, but this effect seems to have disappeared. This is presumably the result of a Sonos update at some point.

Thanks for following up. Let's close it.
