### ISSUE TITLE
Artwork requirements?

### ISSUE THREAD

**Issue by AGithub457** [philippe44/AirConnect#212]
Based on #120, I tried to use many different icons for the artwork tag, but none of them show up. What are the specifications of the icon for airplay? Or is this a Sonos specific feature?

**Comment by philippe44** [comment]
per #120, you must point to a *URL*, not just to a file

**Comment by AGithub457** [comment]
Yes, I already know that, per #120, it needs to be a URL. I’m saying I tried multiple URLs and none of the artwork seems to work.

**Comment by philippe44** [comment]
No it should not. Have you tried a url somewhere on the internet or is this to a local webserver?

**Comment by AGithub457** [comment]
The internet. Tried a couple random pictures, then tried having the picture on my own hosted site. Are there any size, transparency, or other requirements?

**Comment by pwt** [comment]
In case it's useful, [here's](https://raw.githubusercontent.com/pwt/docker-airconnect-arm/master/airconnect-logo.png) one that works with AirConnect and Sonos. It's 600x600px.

The config file entry is:
`<artwork>https://raw.githubusercontent.com/pwt/docker-airconnect-arm/master/airconnect-logo.png</artwork>`

**Comment by AGithub457** [comment]
I tried this, and airplay menu does not show any proper icon.

**Comment by pwt** [comment]
What do you mean by ‘AirPlay menu’?

The image URL is sent to the playback device, and can consequently be shown by this device on its display If it has one, or in its controlling apps. It’s not part of what’s displayed in the Apple AirPlay list.

In the case of Sonos, the image is shown in the Sonos controller apps when a Sonos device is playing from AirConnect.

**Comment by AGithub457** [comment]
I probably misunderstood then, I thought an airplay device would get its own artwork icon in the airplay menus if supplied by the artwork tag. Like how homepods and airpods get their own icon, and TVs get a generic icon, I thought we could supply the artwork ourselves. Apologizes, closing.
