### ISSUE TITLE
Firewall issues on Synology

### ISSUE THREAD

**Issue by GitCharlieHub** [philippe44/AirConnect#213]
Hello,
THANK YOU for putting AirConnect together! It's perfect to stream from iphone to any google home / mini / etc...
I'm struggling a bit with the set-up over a firewall and wonder if anyone can help. I'm using the linux executable on a Synology DSM. It works fine - if the Synology firewall is deactivated.
Withe the firewall activated I would get to:
./aircast-x86-64 -I
[19:17:08.062198] main:945 Starting aircast version: v0.2.21.3 (Oct  4 2019 @ 14:02:14)
[19:17:08.062343] Start:712 Binding to 192.168.1.11

And I wouldn't see the airplay devices on the iPhone. To help anyone out there, if this is the issue, open the Bonjour "discovery" port on the firewall: UDP 5353
I've now got to:
./aircast-x86-64 -I
[19:17:08.062198] main:945 Starting aircast version: v0.2.21.3 (Oct  4 2019 @ 14:02:14)
[19:17:08.062343] Start:712 Binding to 192.168.1.11
[19:17:08.101977] AddCastDevice:649 [0x690380]: adding renderer (Kitchen Speaker)
[19:17:08.102824] AddCastDevice:649 [0x690d10]: adding renderer (Home)
[19:17:08.290775] AddCastDevice:649 [0x6916a0]: adding renderer (Bedroom Speaker)

And the list of devices appear on the iphone.  However if the firewall is activated, selecting one of the speakers on the iPhone times out. I'm stumped as to what ports to open with the firewall.
I've tried destination ports (TCP&UDP): 80,443,554,1900,3689,5297,5298,5350,5351,5353,49159,49163
following the airplay protocol on this webpage: https://carleton.ca/iteam/airplay-protocol/
Also destination Ports 8008; 8009 from the chromecast protocol and nothing.

Note I don't want to turn the firewall off. What port range to I need to open?

Thanks in advance!

**Comment by GitCharlieHub** [comment]
Follow-up: The Synology firewall is inbound only (doesn't block outbound). I tried filtering by IP and opening all ports for the iPhone and all for the google home. It only works if ports are open for both devices (vs only the iphone which was my ingoing assumption.
What would be the port range and is it necessary for both devices?

**Comment by philippe44** [comment]
You won’t be able to identify a fixed set or ports. When playing, at least 3 ports are totally random - per player

**Comment by GitCharlieHub** [comment]
@philippe44, thanks for the reply!

Is there any range or specific ports I should be aware of? Also, any guidance on what would be incoming ports to the synology? i.e. would guess airplay from the iphone? What would be the range of the google home?

**Comment by philippe44** [comment]
No, as said the ports are random (I was just talking incoming ports). There is a dynamic webserver on 49152 and up to 64 ports which is used for UPnP and Chromecast to "GET" the audio, but the ports for AirPlay are randoms. Maybe one day I'll work on setting a base for these, but it's a bit complicated

**Comment by GitCharlieHub** [comment]
Clear! Would be great to have some type of fixed ports, if you ever get around to it would be great!

Thanks so much for a great product and quick replies on requests! Closing.
