### ISSUE TITLE
Linux x86-64 0.2.22.1 binaries don't appear to work 

### ISSUE THREAD

**Issue by paulgit** [philippe44/AirConnect#214]
I have tried to update my installation as normal but the 0.2.22.1 binaries return the following error when executed:

```
./airupnp-x86-64: 8: ./airupnp-x86-64: Syntax error: newline unexpected
```

Is there a known issue or am I doing something wrong?  The previous release works fine so for now I have reverted to that.

**Comment by pwt** [comment]
It's likely you've downloaded some GitHub HTML instead of the actual binary. You could `cat` the file to confirm.

Download the actual binary at: https://github.com/philippe44/AirConnect/raw/master/bin/airupnp-x86-64

**Comment by paulgit** [comment]
Indeed, I am a muppet! Need more coffee!
