### ISSUE TITLE
Mac & iOS device doesn't find Sonos

### ISSUE THREAD

**Issue by oaklandm** [philippe44/AirConnect#215]
Hi,

I have AirConnect running on my Mac but it doesn't find my Sonos speaker. When I run it it says no config found but the config file is placed in the same folder as the airupnp-osx-multi file. Can anyone shed some light on this? I'm a basic user and not used Github much before.

Here is a paste of my config file:

<?xml version="1.0"?>
<airupnp>
<common>
<protocolInfo>
<pcm>http-get:*:audio/L16;rate=44100;channels=2:DLNA.ORG_PN=LPCM;DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</pcm>
<wav>http-get:*:audio/wav:DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</wav>
<flac>http-get:*:audio/flac:DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</flac>
<mp3>http-get:*:audio/mp3:DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</mp3>
</protocolInfo>
<enabled>1</enabled>
<max_volume>100</max_volume>
<codec>flc</codec>
<metadata>1</metadata>
<artwork></artwork>
<latency>1000:2000</latency>
<drift>0</drift>
</common>
<main_log>info</main_log>
<upnp_log>info</upnp_log>
<util_log>warn</util_log>
<raop_log>info</raop_log>
<log_limit>-1</log_limit>
<device>
   <udn>uuid:RINCON_949F3EFF44AA01400</udn>
   <name>Kitchen</name>
   <mac>94:9F:3E:FF:44:AA</mac>
   <enabled>1</enabled>
</device>
</airupnp>

**Comment by oaklandm** [comment]
Ok it's now finding the config but still not finding the Sonos speaker on my network

**Comment by pwt** [comment]
Are you running the Mac on a wireless network? Some networks (wireless in particular) do not handle multicast traffic properly, and this is required for speaker discovery.

If it's possible for you, try the Mac on a wired connection and switch off its WiFi.

**Comment by oaklandm** [comment]
Oh right, unfortunately I'm not able to try that as I have one of those MacBook's with just usb-c ports : )
I have a Raspberry Pi 3 that is always on and connected by ethernet so I'll try and set it up on there and see if that discovers it.

**Comment by oaklandm** [comment]
just installed on my pi and its working great. Must have been something with the wifi. Thanks very much for the tip. I'll close this now
