### ISSUE TITLE
Troubleshooting Steps for airupnp AirPlay Devices not Appearing?

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#217]
I'm trying to debug an installation running airupnp (ARM version, on a Raspberry Pi) where all the Sonos devices are being correctly discovered, and the RAOP advertisements are being correctly sent, but the AirPlay targets are not appearing on Apple devices on the same network.

Other (native) AirPlay devices are appearing on the Apple devices, and the airupnp ones did also appear temporarily on one occasion. The Apple devices are connected on WiFi ... I'm awaiting the results of a test with a wired device. The obvious hypothesis is that this isn't an AirConnect issue, but that something in the network infrastructure is impeding the RAOP advertisements.

**So ... I'm looking for any suggestions folks might have about what to investigate, what troubleshooting steps I should try, etc.** This is a remote installation, so I have access to the Raspberry Pi but not to anything else on the network.

Thanks for any suggestions!

**Comment by philippe44** [comment]
You can use my mdns searcher (see my other github repos) to see what search gives. 

Could the Pi run avahi in a mode where it refuses to share mDNS broadcast (it's an option of avahi: disallow-other-stack)

**Comment by pwt** [comment]
Thanks. I've used `avahi-browse` (running on the Raspberry Pi) to explore the mDNS advertisements on the network. I'm seeing the RAOP entries I'd expect generated by airupnp along with numerous other services on the network. There are 10 Sonos devices advertised by airupnp. I'll also take a look at your mDNS searcher.

Apparently the airupnp devices do sometimes fleetingly appear in the AirPlay menus after a long delay, and can be selected, so advertisements are evidently sometimes getting through.

This is one of a number of identically configured Raspberry Pi devices, all running in different network environments, all of which are functioning correctly regarding mDNS aside from the delay issue described in #176. I don't think there's a fundamental avahi configuration issue.

**Comment by philippe44** [comment]
At that point I'm running out of ideas. As you said, it's usually a problem with some network configuration and multicast or IGMP snooping. Let me know if you find something.

**Comment by philippe44** [comment]
Closed for inactivity
