### ISSUE TITLE
AirPlay 2? 

### ISSUE THREAD

**Issue by jackgold58** [philippe44/AirConnect#218]
Would it be possible to get AirPlay 2 with AirConnect?

I Saw on [9to5Mac](https://ww.9to5mac.com/2019/12/05/airplay-2-cracked/) that AirPlay 2 was just cracked and immediately thought of AirConnect. This would be so cool if this was added to AirConnect!

**Comment by philippe44** [comment]
Maybe but how would AirPlay2 be useful for such bridges? It won’t bring synchronization

**Comment by hmook** [comment]
I use AirConnect on my Synology and it would make it possible to stream to my Sonos Playbar on Airplay 2 instead of AirPlay 1. Usefull for makeing groups!

**Comment by jackgold58** [comment]
> Maybe but how would AirPlay2 be useful for such bridges? It won’t bring synchronization

it would be useful because I use air connect for my Sonos enabled speaker and I wish that I could stream to both my Sonos and my apple tv and adding airplay2 to air connect would allow for that

**Comment by philippe44** [comment]
But Sonos support AP1 and you can send to a Sonos group

**Comment by hmook** [comment]
It does support AP1. But in case of using the playbar in home theater setup you cannot group them right from AppleMusic for example.

**Comment by samaero** [comment]
Could this theoretically be used to mix & match Chromecast / Sonos / Raspberry Pis into multi-room groups?

**Comment by jackgold58** [comment]
> But Sonos support AP1 and you can send to a Sonos group

I don't understand. I have a Sonos Connect which doesn't support have AirPlay. I use AirConnect to give it AirPlay capabilities and was hoping that if AirPlay2 support was added then I would be able to AirPlay to multiple devices at once.

**Comment by pwt** [comment]
What @philippe44 is saying is that if you have multiple Sonos devices, you can use AirConnect/AirPlay to stream to one speaker, and group that speaker with other Sonos speakers using the Sonos app. Obviously, this doesn't work if you have non-Sonos speakers in the mix.

I don't see how AirConnect can be enhanced to provide AirPlay2 synchronisation. AirConnect sits in the middle acting as a bridge between AirPlay streaming and Sonos streaming, and it can't precisely control the playback timing at the Sonos speaker.

**Comment by philippe44** [comment]
@samaero: no, there is no timing control possible in AirConnect. UPnP does not allow any of that and CC protocol is not public not has been reversed engineered

@pwt: exactly

**Comment by timtn** [comment]
Other than multi-speaker function (which probably wouldn't work due to the sync issue), wouldn't AirPlay 2 allow for HomeKit integration? 

I only have a few AirPlay 2 enabled devices, but I believe it would enable remote control of the speaker from multiple devices and not just the device streaming the audio. i.e. start playing music from your iPad and adjust the volume and control the speaker from your iPhone/Mac/other devices in your HomeKit.

**Comment by jackgold58** [comment]
So is it going to be added to airconnect or nah?

**Comment by philippe44** [comment]
currently it's rather nah :-)
