### ISSUE TITLE
Unable to use if on a VPN

### ISSUE THREAD

**Issue by stuax** [philippe44/AirConnect#219]
I am using Private Internet Access vpn on Linux (ubuntu) but Air Connect wont find any Sonos evices while connected to the VPN despite local traffic being unrestricted.

I understand this is not strictly an AirConnect issue but do you have a suggestion as to why this might be?

Thank you.

**Comment by philippe44** [comment]
Your VPN must allow multicast packets to go through and it probably does not

**Comment by philippe44** [comment]
Closed for inactivity
