### ISSUE TITLE
bonjour service

### ISSUE THREAD

**Issue by jowtron** [philippe44/AirConnect#220]
Im using the upnp version with a Sonos speaker and the airplay speaker appears when the program first loads, but drops out very quickly after. It reappears on restarting the app. I am using a pi zero connected through a usb lan adapter. Funnily enough the exact same install works fine on a first generation rpi.

**Comment by philippe44** [comment]
Usually this is a network configuration typically IGMP snooping

**Comment by jowtron** [comment]
Weird that it works fine running on one rpi but not another, the exact same software. I have enabled  IGMP snooping on the router, but hasn't fixed the problem when running the pi zero.

**Comment by pwt** [comment]
I've never managed to get airupnp running on a Zero. What are the logs telling you?

**Comment by philippe44** [comment]
Closed for inactivity
