### ISSUE TITLE
Volume issue

### ISSUE THREAD

**Issue by joeinger** [philippe44/AirConnect#221]
Hi,

thanks for this wonderful project! I‘m glad I bumped into this.
I read it, booted the pi and brought your code to run.

I read all your advices and I‘m still a bit confused with the volume thing.
There is a group of 2 sonos play 1 speaker. Both play music over airplay from my iPhone, at different volumes. Your advice, to lower the volume to zero to synchronize the volume does not work. On speaker is ignoring the new volume and plays always on the same volume. I deleted the group and and created again without any solution. Wenn I adjust the volume you can see in the sonos app, that only one speaker really changes the volume. Any further advice?

Regards Joe

**Comment by philippe44** [comment]
Could not reproduce
