### ISSUE TITLE
Setup CI to automate building of releases

### ISSUE THREAD

**Issue by jdfalk** [philippe44/AirConnect#224]
The releases page has the source code for newer builds but the bin folder does not contain the latest version. Setting up some automated CI like travisci (free for non-commercial open source projects) would automate those steps and ensure that release artifacts are also published. 

I'd be happy to help if you need assistance in getting this setup.

**Comment by philippe44** [comment]
Thank you but it's a complicated build with a lot of cross-compiling so I'm not feeling like doing more. Which binary do see not being updated

**Comment by philippe44** [comment]
Closed for inactivity
