### ISSUE TITLE
Mac OS 10.15.2 (Catalina) stuck on Presence checking

### ISSUE THREAD

**Issue by RudolfOSX** [philippe44/AirConnect#225]
Hi all,

Just made the leap to 64 bit only world of Mac OSX 10.15, downloaded the latest binary of airupnp (v0.2.22.1 Nov 9) and from the previous version under Mac OSX 10.14 I am not not getting any response from my Sonos speakers.  It appears the binary has bound to the correct (only) IP address, in this case 192.168.0.2:49152, but not response from the paging. I've confirmed via Network Utility that port 49152 is open.

Any thoughts?  I saw a thread that something similar happened for some users on earlier versions of Mac OS X, any generic fixes known by the community?

Thanks

G

**Comment by RudolfOSX** [comment]
Update... was using an config.xml from a previous version, so decided to mv this out of the way and get this latest version to build its own.  Perfect it works!.  Now edited the config to disable an already AirPlay2 enabled Sonos and nows it bust again and repeat this sequence is not recovering it.  Not sure what is at play here, but continuing to dig...

**Comment by pwt** [comment]
Note that you can explicitly include only the Sonos speaker models you want using the command line option:
`-o S1,S3,S5,S9,S12,ZP80,ZP90,ZP100,ZP120`

(This is the full set of legacy, non-AirPlay 2 Sonos devices.)

**Comment by RudolfOSX** [comment]
Thanks, right now I just spinning in circles trying to get it to find any speakers :-(.  Very frustrating.

**Comment by pwt** [comment]
Given what you've described, I'd remove the config file and use the `-o` option instead for now. 

Could you post your config.xml file?

**Comment by RudolfOSX** [comment]
config.xml.old - is from an earlier version of airupnp that worked before "upgrade" to Mac OS X 10.15.x
config.xml.new - is from when I ignored the above and used -I to discover plays and build a new config.xml.  I then edited it to disable on speaker, reboot and now its all dead again.

Er?

[config.xml.new.txt](https://github.com/philippe44/AirConnect/files/3991528/config.xml.new.txt)
[config.xml.old.txt](https://github.com/philippe44/AirConnect/files/3991529/config.xml.old.txt)

**Comment by pwt** [comment]
Can't see anything wrong with the new config file. I don't know why it's preventing discovery.

For now you can omit the config file completely and instead use the airupnp command line options to exclude the speaker.

**Comment by RudolfOSX** [comment]
Cheers!

I presume that without a working discovery omitting or not via the cmd line is not going to get me air speakers working, right?

Here is the aircast.log (sorry its big), but at the end you can see one moment yesterday when it finally discovered, after a lot of presence checking - but today nothing
[aircast.log.txt](https://github.com/philippe44/AirConnect/files/3991544/aircast.log.txt)

**Comment by RudolfOSX** [comment]
Something unusual in the Mac OS X 10.15.2 Firewall.  I have to manually toggle from "Allow incoming connections" to "Disable incoming connections", back to "Allow incoming connections".  I do not know the command line for this so unable to verify more deeply.  Will run for a few hours no to see how it goes and then risk a reboot with the auto startup job....

Cheers

**Comment by Olgoetz** [comment]
Same issue here.

`MasterHandler:566 event: 7 [UPNP_DISCOVERY_SEARCH_TIMEOUT] [0x0] (recurse 0)`

**Comment by RudolfOSX** [comment]
Just a quick update.  Not had time to work on fixing this.  I just disallow / allow incoming connections in System Preferences -> Security -> Firewall and then the presence checking works.  Just a workaround.

**Comment by biapar** [comment]
This issue disappear with the latest release.

**Comment by philippe44** [comment]
Good to hear, but I did not do anything around that

**Comment by RudolfOSX** [comment]
So... stranger and stranger. I saw biapar's comment and downloaded the recent version and GREAT IT WORKS! This was about 4 days ago.  Today a Big Mac OS X patch and its dead again. Tried the trick on disable / enable Firewall settings for the binary (allow incoming), nothing.  Something is odd.  Again just stuck on presence checking.  To my knowledge no changes to my LAN router (its from Sky).... Being hitting this on and off today to no joy....

**Comment by RudolfOSX** [comment]
Ok, Mac OS X firewall off and it finds all my upnp devices immediately. FIrewall on, dead.

**Comment by biapar** [comment]
Maybe the firewall block some ports?

**Comment by philippe44** [comment]
Closed to inactivity
