### ISSUE TITLE
Synchronized voice and audio / latency (Sonos)

### ISSUE THREAD

**Issue by dxdc** [philippe44/AirConnect#226]
Thanks so much for creating this @philippe44 !

I know that the latency is not supposed to allow for synchronized audio and video.

> Sometimes you might get lucky because the video-to-audio delay will almost match the HTTP player delay, but it is not reproducible and will not be stable over time.

However, I've discovered something quite interesting. If I use these parameters, I can get the audio/video to sync perfectly on a Mac for many, many videos. It is extremely reproducible. In rare cases where it doesn't sync, if I just refresh my browser tab, it's back in sync.

```xml
<latency>-1:295</latency>
<drift>1</drift>
```

Based on some initial testing, the only requirement is that play it from a Mac computer.

I'm extremely curious if the key to this whole thing is the audio encoding, and perhaps, there is a delay being caused when the encoding is not in a "preferred" format. If that is true, the latency could also potentially be calibrated by timing the conversion from different formats into a "preferred" format.

I did some initial testing with FFMPEG but I didn't have any initial luck getting a video that was off-sync to in-sync by varying the `-acodec` parameter. Also, note that this doesn't work at all from iPhones, but the audio encoding could be changing there as well.

I'm sharing these details, would be great to know if others can reproduce these results or have other insights.

#### In-sync:
- https://www.youtube.com/watch?v=kcEtF_RgOK0
- https://www.youtube.com/watch?v=YoM0wbZn7jw
- https://www.youtube.com/watch?v=gwZuUxeBYV8
- https://www.youtube.com/watch?v=ZT6dde0Tz2c
- https://www.youtube.com/watch?v=oBIxScJ5rlY
- https://www.youtube.com/watch?v=PECGceI0AsE
- https://www.youtube.com/watch?v=zIE3CFNpZ5Y

#### Off-sync:
- https://www.youtube.com/watch?v=qMxX-QOV9tI
- https://www.youtube.com/watch?v=CTA71Mb5pJo
- https://www.youtube.com/watch?v=ER8b92HS0Jk
- https://www.youtube.com/watch?v=whfQf3Pd5bU

* FYI: This does *not* work if I stream using an iPhone on the same videos.

#### Set up:
- AirConnect running on Raspberry Pi
- Google Wifi mesh network
- Sonos PLAY:1 (latest firmware as of Dec 22 2019)
- Mac 10.14.6 (haven't tested other OS)
- Note: Sync is not impacted regardless of browser or player format - even downloading the video then playing in QuickTime works fine.

**Comment by dxdc** [comment]
Another really interesting insight!

1. Ensure that no audio is playing. Then, load and play this audio clip: [cut.mp4.zip](https://github.com/philippe44/AirConnect/files/3992766/cut.mp4.zip)

2. At the same time (while the clip is playing) load any of the Off-Sync videos. They will play perfectly in-sync now.

**Comment by philippe44** [comment]
Setting first parameter to -1 basically means asking the bridge to use zero buffering for playback (so slightest network congestion will be heard - now if AirConnect is running on the Mac that sends audio, that's probably fine :-). The HTTP latency of 295 is probably the result of the delay that your Mac puts between audio and video (2 seconds nowadays), minus the times it takes for the Sonos to react, GET the audio and start playing. Again, it's "luck" in the sense that your system (computer, network, airplay player) in most of the case has a similar latency to do these various tasks. But understand it can and will fluctuate so, as I said, there is no way to guarantee anything.

**Comment by dxdc** [comment]
Hi @philippe44 -- yes, my network set up has a quite low latency. So, that is definitely helpful!

What I discovered though is rather interesting. I'm not familiar with the Airplay protocol, but based on the experiments I ran, it seems there is another factor at play (which maybe could be taken advantage of?)

It seems the process works something like this:

After device/computer is connected to AirConnect virtual player:
1. User initiates audio "play"
2. There is a handshake of some kind (probably between AirConnect and the actual Sonos/etc.?)
3. Audio buffers and begins to play

What is fascinating is that the speed of Step 2 depends on some kind of feature of the audio encoding -- or perhaps -- the size of the file. I'm not quite sure on that part yet.. but it's highly reproducible.

Because, from my experiments, the time that Step 2 takes either makes the audio perfectly in sync (for certain youtube links - no matter what) - or perfectly out of sync by up to 1-2 seconds for other youtube links.

The interesting part is that if we begin playing a specific kind of audio in step 2, and THEN, play a new kind of audio at the same time, we can completely avoid the latency issue with step 2. 

In other words:

1. User initiates audio "play" with audio of specific encoding (see my `cut.mp4` above)
2. There is a handshake of some kind (probably between AirConnect and the actual Sonos/etc.?)
3. Audio buffers and begins playing in "sync" with video
4. User initiates audio "play" with any kind of additional audio. Now, the encoding doesn't matter! *Note that the audio from Step 1 is still playing!*
5. User can close the audio from step 1 and now the audio from Step 4 is still in sync.

From my tests, it seems the important factor here is that audio with the "correct" encoding type starts the connection, and after that, it doesn't matter as long as the connection is still going.

But, we could take advantage of this within AirConnect if it's true!

1. User initiates audio "play" with their preferred type of audio encoding
2. Because AirConnect has no existing connection to the Sonos/etc., it will begin sending a premade "silent" audio file to open the connection and fill the buffer.  We could determine precisely how to create this.
3. AirConnect will drop any packets from the audio player while this initial connection is being established. In other words, if 2 seconds of `cut.mp4` are required, then, 2 seconds of the user's audio will be dropped.
4. As soon as the connection is made, AirConnect will revert back to the user's audio. Now the connections will be made with the same amount of latency every single time!

Hopefully this all makes sense. I'm just curious if this is reproducible for anyone else? It just seems so reproducible on my end. We could take it a step further and (perhaps?) even calibrate the latency further based on the connecting MAC address/IP address to really tune this further.

This way:

1. The initial handshake time would be consistent
2. The user's preferred amount of audio/latency could be cut by the device sending the request. In other words, a prescribed number of audio frames/packets could be dropped to account for typical connection lag.

**Comment by philippe44** [comment]
I'll read your post in more details tomorrow, but on AirPlay, there is the opening of a RTSP session before you can send RTP (real time audio) frames.

iTunes does not tear down that RTSP session before ~30s (I think, I have to check) when you pause or not at all when you switch track. So that makes a second track (unless you pressed stop) start faster. 

Then when you play different codecs, your computer certainly has to load video and audio codecs shared libraries and depending on the codec, it will take a different amount of time. In addition, when playing the same twice it's cached, so then it goes much faster. 

What I'm trying to say is that most of that experience will change with different computers and networks, unfortunately. 

I understand your desire to make that work, but it's just not possible to make it a consistent experience across systems, it's just inherent to the process itself. Sonos players respond fast, some more slowly, different computers, network. To have video/audio sync, the protocol must allow it. AirPlay does but when bridged to a UPnP device, you lose that possibility. UPnP has no provision for controlling audio timing playback. 

Believe me, I've implemented AirPlay from the ground up now and sync for both client and server and LogitecMediaServer sync as well.

**Comment by dxdc** [comment]
> on AirPlay, there is the opening of a RTSP session before you can send RTP (real time audio) frames.

Exactly what I was thinking. Thanks for the explanation!

> Then when you play different codecs, your computer certainly has to load video and audio codecs shared libraries and depending on the codec, it will take a different amount of time. In addition, when playing the same twice it's cached, so then it goes much faster.

What's fascinating here is that the latency is actually not defined by the audio codec directly but by the audio codec that *opened* the RTSP session. Audio codecs after that don't seem to have any effect on speed.

Mirroring your explanation here:
> iTunes does not tear down that RTSP session before ~30s 

- Assume that `youtube 1` is a youtube clip that normally plays "in-sync" for me.
- Assume that `youtube 2` is a youtube clip that normally plays "off-sync" for me.

1. Open RTSP session with in-sync youtube 1
2. Begin playing youtube 1
3. While youtube 1 is playing, start off-sync youtube 2 (now they are both playing)
4. Stop youtube 1
5. Now, youtube 2 is also playing in sync... *and* can be paused/restarted (within a limited timeframe) and maintain sync.

...and...the reverse is also true...

1. Open RTSP session with off-sync youtube 2
2. Begin playing youtube 2
3. While youtube 2 is playing, start in-sync youtube 1 (now they are both playing)
4. Stop youtube 2
5. Now, youtube 1 is also playing OFF-sync!

To me, this means that the encoding that opened the RTSP session is the only one that matters!

> To have video/audio sync, the protocol must allow it. AirPlay does but when bridged to a UPnP device, you lose that possibility. UPnP has no provision for controlling audio timing playback.

Yeah, I understand how complicated this can be, and appreciate you engaging in this discussion @philippe44! Just noticed this interesting phenomenon about the opening of the session and wondering if it could be tuned to improve consistency at the very least.
