### ISSUE TITLE
Segmentation fault (core dumped) - libc.so.6

### ISSUE THREAD

**Issue by timtn** [philippe44/AirConnect#228]
Helping a friend get setup with airupnp-arm5 and having a similar issue as: https://github.com/philippe44/AirConnect/issues/177

It will start up fine and discover a few speakers and show up in airplay for a few seconds but then spits out `Segmentation fault (core dumped)`.

getting this in gdb:

````
Thread 9 "airupnp-arm5" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb3570460 (LWP 13200)]
0xb6df7fc4 in strlen () from /usr/lib/libc.so.6

**Comment by philippe44** [comment]
are you sure you need the arm5 version and can't use the more recent arm

**Comment by timtn** [comment]
Unfortunately, that's the only _always on_ server that my friend has locally at the moment.
I've setup a similar system with the airupnp-arm5 and I believe that one is still working fine, so not sure why this particular setup isn't working.

**Comment by timtn** [comment]
Quick update. Was able to test the airupnp-arm5 without issue on two other arm5 devices, so something is probably wrong with that one system.

System is running ArchLinuxARM, and dependencies seem to be met:
```
Version information:
./airupnp-arm5:
	librt.so.1 (GLIBC_2.4) => /usr/lib/librt.so.1
	libdl.so.2 (GLIBC_2.4) => /usr/lib/libdl.so.2
	libm.so.6 (GLIBC_2.4) => /usr/lib/libm.so.6
	libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
	libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
	libpthread.so.0 (GLIBC_2.4) => /usr/lib/libpthread.so.0
```


Still keeps crashing after a while for some reason:

```
main:1363 Starting airupnp version: v0.2.24.0 (Jan  4 2020 @ 16:24:51)
main:1371 no config file, using defaults
Start:1089 Binding to 10.1.1.15:49152
AddMRDevice:981 [0x9a4c0]: adding renderer (AS-BRAVIA4K[DMR])
MasterHandler:649 [0x9a4c0]: subscribe success
AddMRDevice:981 [0x9c900]: adding renderer (Dining Room)
MasterHandler:649 [0x9c900]: subscribe success
Segmentation fault (core dumped)
```

Anything else to test or try out?

**Comment by timtn** [comment]
Ok, another update. Had some time to play around with everything this weekend and **It's not the arm build, but one of the speakers causing the core dump**.

I ran some of the other builds including the airupnp-osx-multi and get the same error whenever that particular speaker (Dining Room) is connected to the network.

**Comment by timtn** [comment]
This is what I get when I backtrace in gdb with the binary you posted on https://github.com/philippe44/AirConnect/issues/177#issuecomment-522650689:

```
(gdb) run
AddMRDevice:921 [0x6a80c0]: adding renderer (Dining Room)
AddMRDevice:936 [0x6a80c0]: cannot get mac Dining Room+, creating fake 3b9cb21c
[New Thread 0x7ffff48d5700 (LWP 6614)]
[New Thread 0x7ffff68d9700 (LWP 6615)]
MasterHandler:616 [0x6a80c0]: subscribe success

Thread 9 "airupnp-x86-64" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff38d3700 (LWP 6600)]
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) backtrace
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff716647e in __GI___strdup (s=0x0) at strdup.c:41
#2  0x0000000000411ed9 in XMLGetFirstDocumentItem (doc=<optimized out>, item=<optimized out>, 
    strict=true) at ../common/util.c:1369
#3  0x0000000000407454 in ProcessEvent (EventType=<optimized out>, Cookie=<optimized out>, 
    _Event=<optimized out>) at ./src/airupnp.c:391
#4  MasterHandler (EventType=6987856, _Event=0x7ffff48d4be0, Cookie=0x7fffd80013b0)
    at ./src/airupnp.c:579
#5  0x000000000047a3a0 in gena_process_notification_event ()
#6  0x000000000046ef13 in handle_request ()
#7  0x000000000047da77 in WorkerThread ()
#8  0x00007ffff7bc16ba in start_thread (arg=0x7ffff48d5700) at pthread_create.c:333
#9  0x00007ffff71e241d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)
```

**Comment by philippe44** [comment]
ok - found. I will correct that

**Comment by philippe44** [comment]
Done

**Comment by timtn** [comment]
> ok - found. I will correct that
>Done

Thanks! All the builds, including the arm5, are working now!

I am getting this message, but it doesn't seem to affect anything:
```
 XMLGetFirstDocumentItem:1374 ixmlNode_getNodeValue returned NULL
```

**Comment by philippe44** [comment]
Yes, this means a player should have set a value in XML doc but did not
