### ISSUE TITLE
Stop with TV Autoplay

### ISSUE THREAD

**Issue by alcayaga** [philippe44/AirConnect#229]
On the Sonos App I have turned on the option "TV Autoplay". When I turn on the TV, the Speaker switches automatically the source to the TV

When I'm using AirConnect, the music is "still playing" after switching sources and I have to stop the music manually from my phone.

Is there a way to stop this from the AirConnect server when it detects this change?

**Comment by philippe44** [comment]
I don't get the question

**Comment by philippe44** [comment]
Closed for inactivity
