### ISSUE TITLE
100% CPU usage on linux/arm32 (Raspbian February 2020)

### ISSUE THREAD

**Issue by froody** [philippe44/AirConnect#233]
First, thank you so much for writing this! I set it up easily and it's worked perfectly streaming from my iPhone to my Google Home Mini.

I noticed running top on my raspberry pi that aircast is running at 100% CPU all the time, even when not playing music. According to `perf record` it's spending most of the time in `_IO_vfscanf`:
```
  57.37%  aircast-arm  libc-2.28.so        [.] _IO_vfscanf
   7.60%  aircast-arm  aircast-arm         [.] strcmp@plt
   5.67%  aircast-arm  libc-2.28.so        [.] strcmp
   4.74%  aircast-arm  libc-2.28.so        [.] scanf
   3.06%  aircast-arm  libc-2.28.so        [.] _IO_default_uflow
   2.95%  aircast-arm  libc-2.28.so        [.] __uflow
   2.17%  aircast-arm  libc-2.28.so        [.] _IO_file_underflow@@GLIBC_2.4
   2.11%  aircast-arm  libpthread-2.28.so  [.] _pthread_cleanup_push_defer
```

I'm happy to debug this myself, if you have tips on where to look, let me know.

Thanks again!

**Comment by philippe44** [comment]
You probably have mixed up the -z and -Z options. Look at the README

**Comment by froody** [comment]
Fixed, thanks!

**Comment by rubengarciam** [comment]
I am seeing the same behavior in RaspberryPi IS Bullseye. @froody, which -z / -Z options did you use to get the high CPU usage resolved?
