### ISSUE TITLE
Cannot open socket connection (113)

### ISSUE THREAD

**Issue by quacktacular** [philippe44/AirConnect#237]
Hey there! Thanks for creating AirConnect its amazing. 

Been using successfully for many months, but last week it stopped working for some reason. AirConnect finds my Google Home Minis, and makes them available for AirPlay with the correct names.

When I connect to them on a Mac or iOS device it appears connected and appears to be playing. The home device doesn't play any sound and doesn't respond to volume changes either.

```
AirConnect    | [01:14:16.170086] buffer_put_packet:614 [0x7fa6f8006420]: fill [level:388] [W:56384 R:55997]
AirConnect    | [01:14:16.957460] callback:206 [0x690d10]: Play
AirConnect    | [01:14:17.597727] handle_rtsp:392 [0x7fa70000eb20]: received SET_PARAMETER
AirConnect    | [01:14:17.968987] CastConnect:356 [0x690d10]: Cannot open socket connection (113)
AirConnect    | [01:14:17.969048] CastLoad:99 [0x690d10]: Cannot connect Cast receiver
AirConnect    | [01:14:17.969058] CastSimple:211 [0x690d10]: Queuing PLAY
AirConnect    | [01:14:17.969069] CastSetDeviceVolume:333 [0x690d10]: Queuing SET_VOLUME
AirConnect    | [01:14:17.971424] handle_rtsp:574 [0x7fa70000eb20]: received metadata
AirConnect    | 	artist: Empire of the Sun
AirConnect    | 	album:  Two Vines (Deluxe)
AirConnect    | 	title:  Two Vines
AirConnect    | [01:14:17.971482] handle_rtsp:589 [0x7fa70000eb20]: responding:
AirConnect    | RTSP/1.0 200 OK
AirConnect    | Audio-Jack-Status: connected; type=analog
AirConnect    | CSeq: 168
```
I confirmed I can cast from Google Chrome on the devices that can't AirPlay through AirConnect. Any ideas?

**Comment by philippe44** [comment]
Error 113 is a "no route to host". It looks like something have changed in your network setup (depends on the router you're using) and AirConnect is refused the route to the CC device

**Comment by quacktacular** [comment]
You're right this was totally my fault. I added an extra route to for a site to site VPN and it was hijacking traffic bound for the subnet my IoT devices are on. 

Thanks!
