### ISSUE TITLE
AirUPnP osx

### ISSUE THREAD

**Issue by drheiser** [philippe44/AirConnect#239]
I have tried AirUPnP osx multi on osx Mojave. Only 0.2.0.1 is working. Tried 0.2.0.2 to 0.2.10 and the latest: no sonos devices will be detected. Sonos are up do date.

**Comment by philippe44** [comment]
Look at closed issues, I think it's a firewall problem, others had this and solved it

**Comment by philippe44** [comment]
Closed for inactivity
