### ISSUE TITLE
Stuck under Windows 

### ISSUE THREAD

**Issue by Danwardo** [philippe44/AirConnect#24]
Hi, Thanks for the project, looking really promising!

When loading it seems to gets stuck under windos 10 or indeed Windows Home Server 2011 with the following output: 

C:\Users\Administrator\Desktop\ircast>aircast-win.exe
[06:09:01.128] main:826 Starting aircast version: v0.1.4.3 (Dec 10 2017 @ 21:27:
56)
[06:09:01.128] main:834 no config file, using defaults
[06:09:01.752] Start:630 Binding to 192.168.1.14

No matter how long you wait it doesn't seem to get further. Run as admin and disabled firewall to no avail?

**Comment by philippe44** [comment]
It really looks like a firewall issue or you have more than one network card on your machine and aircast-win is picking up the wrong one.

**Comment by Danwardo** [comment]
Hmm I've disabled the firewall on both pc's and they only have one network card. Not sure where else to try?

**Comment by philippe44** [comment]
That's a difficult case then, I'm afraid. What I've seen a few times is that due to network topology or router filtering, the mDNS discovery requests/answers were filtered out.

**Comment by Danwardo** [comment]
Managed to get it working by running airupnp-win.exe instead of aircast-win.exe. No idea why, same setup, worked first time. 

Thanks for the epic app!!
