### ISSUE TITLE
aircast hangs on arm/raspberrypi when Google Home Mini disappears

### ISSUE THREAD

**Issue by froody** [philippe44/AirConnect#240]
Steps to repro:

1) Run aircast via systemd with `aircast-arm -Z` on raspberry pi 4
2) Connect a Google Home Mini to the same network
3) Play a song from iOS music app to the Google Home Mini device presented by aircast
4) Unplug the Google Home Mini while song is playing

At this point the aircast process becomes stuck and can't be killed with just `kill` or `systemctl restart airconnect`. iOS reports failure to connect to the device presented by aircast. It does respond to `kill -9`, and then restarting the service allows me to play music again. See attached log (look for kill)

Log here: https://gist.github.com/froody/17d016aa5fd3d2fca4ad018a21efdeed

**Comment by philippe44** [comment]
You're looking for troubles :-)

**Comment by philippe44** [comment]
Having said that, I checked and it closes. What needs to be done is waiting for the device presence timeout to expire and then it terminates. It's a minutes though
