### ISSUE TITLE
free(): invalid pointer: 0x70e00a48

### ISSUE THREAD

**Issue by Dayuuuuu** [philippe44/AirConnect#243]
I ran this on my rasberrypi and it happend this problem. I don't know how to solve it, can u help me? Thx alot.

pi@raspberrypi:~/air2 $ ./airupnp-arm 
[16:08:49.016806] main:1373 Starting airupnp version: v0.2.24.2 (Feb 23 2020 @ 19:01:05)
[16:08:49.017191] main:1381 no config file, using defaults
[16:08:49.069402] Start:1089 Binding to 192.168.3.7:49152
*** Error in `./airupnp-arm': free(): invalid pointer: 0x70e00a48 ***
已放弃

**Comment by Dayuuuuu** [comment]
I've found that it may similar to this: https://github.com/philippe44/AirConnect/issues/135

**Comment by Dayuuuuu** [comment]
I just tried to run airupnp-osx-mulit on my mac (10.12.6), and it is successfully running. But I still want to run it on my Pi. I hope this information will help you to deal it.

**Comment by philippe44** [comment]
What are the UPnP device on your network? Can you try airupnp with the additional command line "-d all=SDEBUG"

**Comment by Dayuuuuu** [comment]
The UPnP device is a player. I tried airupnp with the additional command line "-d all=SDEBUG" but it still not working :(
Here's the log:

pi@raspberrypi:~ $ sudo ./airupnp-arm -d all=SDEBUG
[22:33:49.858678] main:1373 Starting airupnp version: v0.2.24.2 (Feb 23 2020 @ 19:01:05)
[22:33:49.859016] main:1381 no config file, using defaults
*** Error in `./airupnp-arm': free(): invalid pointer: 0x70e025b0 ***
已放弃

Do u need the log on mac?

**Comment by philippe44** [comment]
No, that's the first time I see that, such an early crash. What Pi is that?

**Comment by Dayuuuuu** [comment]
Raspberry Pi 3 Model B

**Comment by philippe44** [comment]
And what OS? There has to be something on your side as many are using Pi/Raspbian with that build and as you can see, I don't have open issues of that sort

**Comment by Dayuuuuu** [comment]
Its Raspbian OS. I think it may be caused by the absence of some environment.

**Comment by pwt** [comment]
You might want to try my Docker version of airupnp-arm: https://github.com/pwt/docker-airconnect-arm.

You’ll need to have Docker running on your Pi first.

**Comment by Dayuuuuu** [comment]
OK I will try it. Thanks for your help. Does this mean that I cannot run it temporarily on Raspbian?

**Comment by pwt** [comment]
No, to reiterate what @philippe44 said, it works perfectly on Raspbian (without Docker). I haven’t seen any issues running it under Raspbian Stretch or Buster, on Pi 3 and Pi 4 devices.

However, running it under Docker gives you a complete packaged environment that may work around config issues with your Raspbian install.

**Comment by philippe44** [comment]
Closed for inactivity
