### ISSUE TITLE
Change Readme for Synology Package Repository

### ISSUE THREAD

**Issue by eizedev** [philippe44/AirConnect#245]
@philippe44 
**bandesz** has archived his repository for the [Airconnect-Synology](https://github.com/bandesz/AirConnect-Synology) package a few month ago.  
For the last months I have been building my own packages. But now I decided to continue this for and with the community as far as possible.  

If that's ok with you, you are welcome to include the link to my repository in your readme and point to it. The latest release is also online. If old releases are needed, I can also provide them.  
I try to update the latest version regularly. Since I use it myself, this should be possible without problems.

I have extended the readme and updated the scripts.

New Repository: https://github.com/eizedev/AirConnect-Synology
Github Page(s): https://eizedev.github.io/AirConnect-Synology/

**Comment by philippe44** [comment]
Update done - merci
