### ISSUE TITLE
Build for the ppc32 architecture of the DS213+

### ISSUE THREAD

**Issue by nlights** [philippe44/AirConnect#249]
Hello!
Is a compatible ppc version for the ppc32 architecture from the ds213+ possible?
See @eizedev's response [https://github.com/eizedev/AirConnect-Synology/issues/1](https://github.com/eizedev/AirConnect-Synology/issues/1#issuecomment-624132252) for details.
Thank you very much!

**Comment by philippe44** [comment]
I've added a static build, you can give it a try

**Comment by eizedev** [comment]
@nlights 

the quickest way to test the static build(s), is to download the two binaries to your NAS and try to run these binaries.
If it's easier for you, i can build a spk package.

If you want to start these binaries with the default settings, you can use the default command line arguments as mentioned in the |how it works](https://github.com/eizedev/AirConnect-Synology#how-it-works) section and start the binary using the airconnect user.

Static build(s):

[aircast-bsd-x64-static](https://github.com/philippe44/AirConnect/blob/master/bin/aircast-bsd-x64-static)
[airupnp-x86-64-static](https://github.com/philippe44/AirConnect/blob/master/bin/airupnp-x86-64-static)

**Comment by nlights** [comment]
@eizedev 
I'm not very familiar with linux, a spk package would be a big help for me. if it is not to much asked from you - thank you anyway!

**Comment by eizedev** [comment]
@philippe44 
I am not very familiar with static builds, but can i use the bsd static build of aircast in combination with the x86-64 static build of airupnp? 
The synology package combines both binaries (aircast and airupnp) at the moment. 

@nlights 
No problem, i will create an spk package for you and upload it to the [releases](https://github.com/eizedev/AirConnect-Synology/releases) page, as soon as it is ready.
I'll let you know.

**Comment by philippe44** [comment]
the -static builds are simply a build that has no external "loadable" library dependency. There is no incompatibility issues between static and classical builds across airxxxx application.

**Comment by eizedev** [comment]
thanks @philippe44 
I have created an spk package for testing (@nlights) as mentioned in the other [issue](https://github.com/eizedev/AirConnect-Synology/issues/1#issuecomment-624910263) and used the two binaries:  [aircast-bsd-x64-static](https://github.com/philippe44/AirConnect/blob/master/bin/aircast-bsd-x64-static) & [airupnp-x86-64-static](https://github.com/philippe44/AirConnect/blob/master/bin/airupnp-x86-64-static)

**Comment by philippe44** [comment]
you alos have airupnp-ppc-static

**Comment by eizedev** [comment]
@philippe44 cool, thanks! Stupid question, but i cannot find `airupnp-ppc-static` in the bin folder?

**Comment by philippe44** [comment]
ahah ... I forgot to push the modification :-)

Re doing a static for all, yes I can but it's adding a lot to my build time hence I'm doing them one by one (and it's a bigger bin as well)

**Comment by eizedev** [comment]
@philippe44 Thanks for your effort and the binary! :-)
I did not mean to say that we need a static binary for all architectures. But in the case of @nlights I would also need the aircast static binary. Would it be possible to create the static binary for aircast as well? So airupnp-ppc-static & aircast-ppc-static. For the Synology package I generally package both binaries. Many, many thanks

**Comment by philippe44** [comment]
Added the aircast-ppc-static. Static are still CPU/OS specific

**Comment by eizedev** [comment]
The ppc-static binaries are now part of the current and upcoming releases: https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.25.0-20200511
