### ISSUE TITLE
airupnp on mac os x - no "-z" option?

### ISSUE THREAD

**Issue by marco79cgn** [philippe44/AirConnect#25]
Hi,

I'm running AirConnect on a Raspberry Pi which works perfect. I also tried the Mac OSX binary which works as well, except the "-z" option? Isn't it available there? It just won't run in the background and stops everytime I close the terminal or push CMD-C.

**Comment by philippe44** [comment]
I don't know how to daemonize the process on OSX ... You can still do it "manually" on the command line (&) and use the -Z option to make sure the apps does no try to use stdin, no?

**Comment by marco79cgn** [comment]
Ahh, sure. The "-Z &" (capital Z) is a solution. 
Otherwise I guess you would have to use launchd and create a plist beforehand. Thanks!
