### ISSUE TITLE
rename Sonos group master after detection

### ISSUE THREAD

**Issue by nipsgur** [philippe44/AirConnect#250]
First, thanks a lot for this project!

Would it be possible to get the name of the master in a Sonos group changed after it was discover in the detection cycle in airupnp? Maybe an additional "group" after the + in the advertised name.
It would show you, that there is a Sonos group so it is ok for some other speaker not to be shown. And you can distinguish between single speakers.
thank you already in advance.

**Comment by philippe44** [comment]
Unfortunately I don't detect if a player has some slaves, I just know that a player *is* a slave

**Comment by philippe44** [comment]
Closed for inactivity
