### ISSUE TITLE
raspbian: stuck on binding step

### ISSUE THREAD

**Issue by vytotas** [philippe44/AirConnect#251]
Hello!
Trying to run airconnect on raspberry and stuck at binding step.

```
pi@raspberrypi:~/airpnp $ ./airupnp-arm -l 1000:2000
[10:56:44.160952] main:1374 Starting airupnp version: v0.2.25.0 (May  3 2020 @ 17:41:50)
[10:56:44.163786] main:1382 no config file, using defaults
[10:56:44.177857] Start:1099 Binding to 192.168.178.70:49152
```
Same result when using other linux machine. Any suggestions?
Thanks!

**Comment by philippe44** [comment]
something in your network configuration is blocking the UPnP broadcast messages

**Comment by pwt** [comment]
If you’re running airupnp on a machine connected via wireless, try a wired connection instead. Some routers don’t forward the multicast discovery packets over their wireless interfaces.

**Comment by philippe44** [comment]
Closed for inactivity
