### ISSUE TITLE
Airconnect to jongo A2

### ISSUE THREAD

**Issue by CCR78** [philippe44/AirConnect#253]
I'm trying to connecting to Jango A2 the device is visible in the list but no audio is coming .
could you help me  ?

I tried also to use e different value for the latency like for Sonos but nothing (-l 1000:2000)

Thank 
Claudio

**Comment by timtn** [comment]
Try another codec?
```
  -c <mp3[:<rate>]|flc[:0..9]|wav|pcm>	audio format send to player
```

**Comment by philippe44** [comment]
Or a firewall on your system. You did not tell what is the OS/CPU

**Comment by CCR78** [comment]
Os ->  Docker on unraid.
CPU ->  Intel® Atom™ CPU 330 @ 1.60GHz

**Comment by pwt** [comment]
Are you using `network=host` for the Docker AirConnect container?

**Comment by CCR78** [comment]
No, I'm using a custom br0 (dedicated ip)

**Comment by pwt** [comment]
> No, I'm using a custom br0 (dedicated ip)

You could try `net=host` to confirm that the bridge configuration isn't the source of the problem.

**Comment by philippe44** [comment]
You need host mode

**Comment by CCR78** [comment]
I think that the issue was about the codec. 
These are the codes supported from Jongo:
	- Includes WMA (Standard V9), AAC, MP3, MP2
        
But I think that I have to configure the docker to consider the config.xml file.
because if  I run the container doesn't work but if I connect to the console and I run  ./airupnp-x86-64 and in this way it works (in the config file I fill for this device the codec mp3).

Could you help for that ? I'd like not lose the configuration  when I stop and start the container (config.xml).

**Comment by pwt** [comment]
You’ll need to copy config.xml into the container filesystem.

**Comment by CCR78** [comment]
the config.xml is in the bin folder in the same folder of  airupnp-x86-64

**Comment by CCR78** [comment]
I used this guide and it works right now.
https://www.synoforum.com/resources/airconnect-use-airplay-to-stream-to-upnp-sonos-chromecast-devices.75/
Thank a lot for the help.

**Comment by philippe44** [comment]
Great and thanks @pwt for your help
