### ISSUE TITLE
Set Default Volume

### ISSUE THREAD

**Issue by maxexcloo** [philippe44/AirConnect#255]
I understand how to manually set the volume for Chromecast devices with a config but it would be nice to have a flag to set it as default without config - is this possible? Happy to put in a pull request too but not too familiar with C++ so far :)

**Comment by philippe44** [comment]
You mean media_volume?

**Comment by maxexcloo** [comment]
Sorry, yes 👍

**Comment by maxexcloo** [comment]
Oh never mind, I'm silly. Will fix it on my end!

Thanks for your help!

**Comment by philippe44** [comment]
I was about to add a -v command line option, so it's not needed?

**Comment by maxexcloo** [comment]
It would be nice but I can live without it, didn't realize that there was a <common> section in the config :)

**Comment by philippe44** [comment]
it's done in 0.2.26 :-)
