### ISSUE TITLE
Airplay2 Support

### ISSUE THREAD

**Issue by nstefanelli** [philippe44/AirConnect#258]
Hi there! Looks great, quick question. I was considering buying a Nest Home Hub (which supports Chromecast streaming) and was wondering if this exposes the devices as airplay 2 devices? Would like to use it in conjunction with other airplay 2 speakers. If not, are you considering adding support for Airplay 2?

Thanks again!

**Comment by timtn** [comment]
AirConnect and AirCast only support airplay 1. 

Related topic: https://github.com/philippe44/AirConnect/issues/218

**Comment by philippe44** [comment]
Closed for inactivity
