### ISSUE TITLE
Remove AirConnect

### ISSUE THREAD

**Issue by rogersjandrew** [philippe44/AirConnect#259]
Hello,

Will you please help me remove AirConnect. I can no longer connect to my Sonos speakers. Thank you very much!

![IMG_1207](https://user-images.githubusercontent.com/66797204/84423318-19f29980-abd3-11ea-8f4b-ac0c6179b383.png)

**Comment by philippe44** [comment]
On what system?

**Comment by rogersjandrew** [comment]
It was on Sonos. I simply unplugged the speakers and it removed AirConnect. I was hoping to play movies from my computer, MacBook Pro, to a projector and to my Sonos using AirConnect. Unfortunately there was an audio delay. 

Thanks for your response,

Andrew 

-------- 

ANDREW ROGERS
PURDIE ROGERS 
2288 W Commodore Way, Suite 200
Seattle, WA 98199
T 206-628-7700 EXT 13

DIGITAL & TRADITIONAL MARKETING
