### ISSUE TITLE
Some devices lose AirPlay destionations while others still find them

### ISSUE THREAD

**Issue by vicegold** [philippe44/AirConnect#26]
While playing on a Mac playback via UpNP-> AirPlay stopped and all AirPlay devices weren't available anymore through the sound menu.

When i tried with my iPhone i still saw them there. Here's my log from stopping on a Mac and resuming on an iPhone:

https://pastebin.com/HXMcEa5q

**Comment by philippe44** [comment]
Is this reproducible?
