### ISSUE TITLE
issue with multiple network

### ISSUE THREAD

**Issue by saparm** [philippe44/AirConnect#261]
i have pi4 running ovpn as gatevay. my ifconfig is as below.

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.100  netmask 255.255.255.0  broadcast 192.168.1.255
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
```
so airconnect works good. when i turn on openvpn the tun adds to my interfaces.
 
```
tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.8.0.9  netmask 255.255.255.0  destination 10.8.0.9
```
  then airconnect crashes. with
` UpdateThread:721 [0x48f118]: removing unresponsive player (Living Room+)
`
error

**Comment by timtn** [comment]
Did you try `-b 192.168.1.100`?

> When you have more than one ethernet card, you case use -b [ip] to set what card to bind to.

**Comment by saparm** [comment]
> 
> 
> Did you try `-b 192.168.1.100`?
> 
> > When you have more than one ethernet card, you case use -b [ip] to set what card to bind to.

yes it stucks on 

[13:29:04.678699] Start:1103 Binding to 192.168.1.100:49153

**Comment by saparm** [comment]
was running on ubuntu, changed to raspbian. problem resolved.
