### ISSUE TITLE
output to pipe instead of act as brigde to other devices

### ISSUE THREAD

**Issue by jgabriel98** [philippe44/AirConnect#266]
I know that the project is meant to act as a bridge.
But i want to know if it is possible to make i behave in a more simple way, by just outputing the audio to a pipe, and nothing more.

In other words: acting just as as airplay receiver/interface.

i've been looking for some project that does this , but everyone is more complex, and yours seems to be the most simple/clean and well maintened

**Comment by philippe44** [comment]
Isn't shairport a better choice? I think it's simple to use as well, no?
The problem with my project is that it is a many-to-many bridge, so I need first real UPnP / CC to "mirror" and then there are potentially many outputs to send to stdout

**Comment by jgabriel98** [comment]
yeah, actually i had tried shairport-sync before. But i was getting a lot of problems with it pipe support.
but i've managed to find out the problem and the solution a couple of hours after my post here.

so, in other words:
i agree and this issue can be closed or even deleted (if possible)
