### ISSUE TITLE
Does this allow me to stream audio from OSMC on Raspberry Pi to a Sonos One?

### ISSUE THREAD

**Issue by mrengy** [philippe44/AirConnect#269]
I read the entire readme, and I have heard good things about this application, but I'm not sure if it fits my use case.

I have a Raspberry Pi 3 running [OSMC](https://osmc.tv/), and I'd like to play videos on the Raspberry Pi and play the video on a projector while streaming the audio to a Sonos One speaker.

I wasn't clear from the readme if this is supported (the readme describes creating virtual AirPlay devices and acting as a bridge / proxy between AirPlay clients and Sonos players, which sounds like not what I'm trying to do).

If this use case is supported, how do I install it on my Raspberry Pi 3 running OSMC? I am familiar with SSHing into OSMC and using wget and then going into the OSMC interface to install add-ons [as described here](https://makingstuffwork.net/technology/install-netflix-amazon-prime-video-plex-raspberry-pi-kodi-osmc/). Is that what I should do in this case? Also which [binary in the folder](https://github.com/philippe44/AirConnect/tree/master/bin) should I use?

Thanks.

**Comment by philippe44** [comment]
I don't know OSMC but regardless what you want is audio/video synchronization and the Sonos access will not let you do that. You can't control timing on Sonos using UPnP access because UPnP does not allow timing control in general. And Sonos does not disclose their proprietary sync protocol. Your best chance is because Sonos One supports AirPlay, then you should look for AirPlay support in OSMC

**Comment by mrengy** [comment]
Thanks. I am looking into Airplay support in OSMC. 

However, OSMC also has an audio / video offset option https://discourse.osmc.tv/t/where-is-the-audio-delay-offset/79178/18 . Also, OSMC is based on Debian. Given that, would this use case be viable?

--

**Comment by philippe44** [comment]
No it will mostly not work. The delay using UPnP is unpredictable. It can look like it's "similar" most of the time, but it really does vary randomly, there is nothing to make it guaranteed and repeatbale.

**Comment by philippe44** [comment]
closed for inactivity
