### ISSUE TITLE
Best Practises for getting AirUPnP working in networks?

### ISSUE THREAD

**Issue by Connor0308** [philippe44/AirConnect#270]
Dear,

a while ago, I already tried to get AirConnect running in my network. Since I failed, I took the easy road and switched to Spotify.
However, I am back. But even after reading through a lot of threads, I am unable to get it (the airupnp part) working. 
For simplicity reasons, I decided to go with the [dockerized version](https://github.com/1activegeek/docker-airconnect) of your tool an a Synology 918+. Since the container is up and running, I hope that the ticket here is a valid option.

While the aircast component is up and running, the aircasts comes up, but doesn't discover anything.
 
```
[19:10:32.953975] main:1385 Starting airupnp version: v0.2.27.0 (Aug  3 2020 @ 11:17:59)
[19:10:32.954118] main:1393 no config file, using defaults
[19:10:33.008689] Start:1103 Binding to 192.168.1.10:49152
```

What I understood is that this is in someway related to the network setup as it seems to cancel the mDNS package.
So far, I have tried nearly every setting that I found on my router - but without success. This is why I am looking forward to ANY idea.

Here is some information on my network topology:

Unifi USG  ==> NAS (LAN IP segment 192.168.1.10)
                   ==> Sonos (WiFi IP segment 192.168.20.XXX)

What I enabled is 
- UPnP (Services >> UPnP)
- mDNS (Services >> mDNS)
- IGMPv3 enabled (WiFi-Networks >> Multicast Enhancement)

Additionally I disabled the IGMP Snooping on all related networks.

Putting it all together - I am stuck.

Any idea on how to proceed?

Thank you for your support,
regards

**Comment by Hofyyy** [comment]
Hello, I do not have time now, but i have also the complete unify stuff and they had bugs ins the firmware regaeding mdns proxy service. I can send you my worling versions tomorrow

**Comment by Connor0308** [comment]
@Hofyyy This would be great - thank you for your support.

**Comment by pwt** [comment]
What speakers are you expecting to discover? Are you sure you shouldn't be running aircast instead of airupnp?

**Comment by Connor0308** [comment]
I want to include a group of Sonos Play:1 speakers.
Accordingly to my knowledge, these are include using airupnp.

**Comment by pwt** [comment]
> I want to include a group of Sonos Play:1 speakers.
> 
> Accordingly to my knowledge, these are include using airupnp.

Yes, that's correct. You mentioned 'aircasts', which is why I checked.

**Comment by Hofyyy** [comment]
I use 4.4.51.5287926 for the firewall, 5.14.18 controller, and 4.3.20 for the devices. i think the controller version is important. because their you have to enable die mdns service ...

**Comment by Hofyyy** [comment]
The firewall is also important, because the mdns reflector service is running on the firewall.

**Comment by philippe44** [comment]
and you're running the docker container in host mode?

**Comment by Connor0308** [comment]
First thank you for your swift replies. I really appreciate this.

@philippe44: Yes, I am. 

@Hofyyy : Apart from the controller version I am already on the respective firmware versions. The controller version 5.14.18 seems to be a RC - where can I download it, because from the official sources, I can only see the 5.13.32 as available.
And to be on the safe side, what other settings did you apply on the controller?

**Comment by Connor0308** [comment]
@pwt : That is true - I just wanted to mention that aircast is working with other devices as expected. Sorry for confusing you.

**Comment by eizedev** [comment]
@Connor0308 

You might also try using the [Synology Airconnect](https://github.com/eizedev/AirConnect-Synology) package instead of the docker container. Then you could rule out that the problem might be due to docker (host mode) or anything related to that. (Exclusion Procedure)

**Comment by Connor0308** [comment]
@eizedev : Thank you for the suggestion. Honestly, I tried it in beforehand, but switched to the dockerized version, as it offers me access to the logs not only via CLI. At least for the debugging on my side, this offers some advantages. But I will get back to that package afterwards.
As well thank you for pointing me on the RC possibilities. I was able to have my controller flashed to 5.14.18. 
However, it is still not finding the Sonos speakers, but is producing some other content in the logs.

This is what is inside the logs now after flashing to 5.14.18 and enabling IGMP spoofing again

```
[09:37:55.723531] main:1385 Starting airupnp version: v0.2.27.0 (Aug  3 2020 @ 11:17:59)
[09:37:55.723719] main:1393 no config file, using defaults
[09:37:55.725312] Start:1103 Binding to 192.168.1.10:49152
[09:41:13.696705] CheckAndLock:259 device is NULL
[09:41:13.696954] CheckAndLock:259 device is NULL
[09:41:13.696987] CheckAndLock:259 device is NULL
[09:41:13.697010] CheckAndLock:259 device is NULL
[09:41:13.697032] CheckAndLock:259 device is NULL
[09:41:13.697054] CheckAndLock:259 device is NULL
[09:41:13.697076] CheckAndLock:259 device is NULL
[09:41:13.697098] CheckAndLock:259 device is NULL
[09:41:13.697120] CheckAndLock:259 device is NULL
... Continues for a longer time...
```

So there is some progress here.

**Comment by Connor0308** [comment]
@eizedev : Just for your feedback: I just switched to the package, but this does not change the behaviour.

**Comment by Hofyyy** [comment]
Just one stupid idea. We had a discussion about the upno media receiver versions in another thread. I understood the default is at the moment one. But i think their are version 2 and 3 devices in the market. So you should try to force version 2 and or 3.

**Comment by Connor0308** [comment]
@Hofyyy : This is certainly not a stupid idea - just how do I do this?

**Comment by pwt** [comment]
Worth a try, but just to note that this is not required for Sonos speakers. The default UPnP version works fine.

**Comment by Hofyyy** [comment]
Regarding the Unify settings:
I have some vlans. One for my normal stuff like laptops and one separate wlan only for the audio stuff.
Because I only bridge between chromecast and airplay I use airconnect. So I have no upnp settings enabled.
With mdns service enabled and multicast allowed in general it worked for me out of the box.
If i remember it correct, unify had the bug that the webinterface does not launch mdns. so that was a ui bug.
So maybe you can check via SSH if the service is running. See below.

1. mdns
- Because I only use airconnect I have the unify upnp service off.
- But I enabled the mdns service.
Maybe you can start the service via SSH in your software version and see if it helps
See:
https://community.ui.com/questions/Unifi-mdns-repeater-not-working-across-VLANs/b47199a0-5e7e-4caf-a8c6-d3c9c56f1e27

2. Multicast
LAN: IGMP Snooping -> off
WLAN: Block LAN to WLAN Multicast and Broadcast Data -> off

**Comment by Connor0308** [comment]
@Hofyyy 
Thank you for your continued support. I spent the evening of the last two days to get AirConnect up and running in my environment. I have no idea what I am doing wrong, but I can simply not get it running. 
Even the connection between the Sonos App (in segment 10) to the speakers (in segment 20) is blocked. After playing around with firewall and nearly all other setting, I am on controller version 6.0.XX, but without success.

Is there still any great idea out there? If not, I guess I will end this and get once again get back to Spotify, which offers a working solution in my environment...

Thank you - and sorry for keeping you busy.

**Comment by Hofyyy** [comment]
Hello @Connor0308,

no Problem. I like your idea to first get the Sonos App running, instead AirUpnp.
If you like we can also have a Signal Call to discuss the settings, but as you know I do not have the same audio vendor.

In my setup I had not to change anything in the firewall, because by default the VLANS are routed completely. Ok for multicast and upnp are special services, but they could be activated via Web UI. After all war running, I separated the VLANs step by step ...

If you have an email I can send you my signal ID

BEst regards

**Comment by Connor0308** [comment]
Hello @Hofyyy ,

thank you for your ongoing support. But I finally managed to have success on this topic.
What finally helped was [this](https://www.neilgrogan.com/ubnt-sonos/) article.
After enabling the IGMP proxy in the right VLAN, AirConnect is up and running with the Sonos.

Maybe it will help someone else in a comparable situation.

I will close the topic accordingly and simply enjoy :-).

Best regards

**Comment by TheSimu** [comment]
Above plus link from connor (https://www.neilgrogan.com/ubnt-sonos/) helped indeed in our unifi environment. 
If you have a unifi-wifi (no usg and such, no vlans) you have to turn off Auto-Optimize and turn on IGMP-Snooping. 

Snooping was deacitvated with us, turn it on, hearty apply, there we go. 

Thanks.
