### ISSUE TITLE
'No such file or directory'  when trying to execute on Raspberry PI

### ISSUE THREAD

**Issue by mickejansson** [philippe44/AirConnect#271]
Hello, awesome project!

However, I can't seem to execute the binaries on my Raspberry PI 4 (model b) running Ubuntu Mate 64-bit.

micke@raspberry:~$ ./AirConnect-master/bin/aircast-arm
bash: ./AirConnect-master/bin/aircast-arm: No such file or directory
micke@raspberry:~$ ./AirConnect-master/bin/aircast-arm5
bash: ./AirConnect-master/bin/aircast-arm5: No such file or directory

The files are there and should be executable...
micke@raspberry:~/AirConnect-master/bin$ ls -l
total 25232
-rw-rw-r-- 1 micke micke  436024 aug  3 22:07 aircast-aarch64
-rwxrwxr-x 1 micke micke  410968 aug  3 22:07 aircast-arm
-rwxrwxr-x 1 micke micke  423252 aug  3 22:07 aircast-arm5
-rw-rw-r-- 1 micke micke  604192 aug  3 22:07 aircast-bsd-x64
-rw-rw-r-- 1 micke micke 3088360 aug  3 22:07 aircast-bsd-x64-static

Not sure what the difference between arm and arm5 is...

**Comment by philippe44** [comment]
arm is armv6+, the most "classical" arm achitecture in 32 bits and arm5 is for older system with not float point. In your case, you're looking for a 64 bits arm system, so the aarch64 version

**Comment by mickejansson** [comment]
Thanks! Works a lot better now.
