### ISSUE TITLE
[Windows] airupnp cannot find config file

### ISSUE THREAD

**Issue by Philip-Nicolas** [philippe44/AirConnect#272]
Found using `airupnp-win.exe` on Windows 10.0.19041.

after creating `config.xml` using `-i`, then restarting, the configuration isn't loaded and the message `no config file found, using defaults` is still logged.

~~Possibly caused by line 144 in `airupnp/src/airupnp.c`, using `./` instead of `.\` :
```static char glConfigName[_STR_LEN_] = "./config.xml";```~~

**Comment by philippe44** [comment]
Normally Windows authorized / in path now. But I'm sorry, you say "found", what did you find?

**Comment by philippe44** [comment]
oh, I missed the title - so no, it is not related to that. What are you seeing exactly?

**Comment by Philip-Nicolas** [comment]
^ i think you're right

after creating `config.xml` using `-i`, and running `airupnp`, the configuration isn't loaded and the message `no config file found, using defaults` is still logged.

updated initial comment

**Comment by philippe44** [comment]
so where is the config.xml file located when you launch airupnp for the 2nd time? Are you sure there is no access right problem (r/w)

**Comment by Philip-Nicolas** [comment]
same directory as the executable. I can edit & save it just fine.

I've got this working on a macos computer, though, so this (possible) bug isn't much of a problem for me.

**Comment by philippe44** [comment]
ok, we'll leave it there then b/c it normally works under Windows
