### ISSUE TITLE
Logs stop after Start: Binding to

### ISSUE THREAD

**Issue by krunal-shah** [philippe44/AirConnect#278]
Hi I have been trying to use the binary on my MacOS 10.15.6 and when I run the script I only see the below logs:

```
[19:43:57.768179] main:951 Starting aircast version: v0.2.27.0 (Aug  3 2020 @ 11:17:19)
[19:43:57.768750] main:959 no config file, using defaults
[19:43:57.768867] Start:715 Binding to 192.168.0.195
```
and I do not see any AirPlay devices after this. Is this the result of some error?
I have 3 different Google Home Minis setup on the same wifi connection as the laptop. Could that be an issue?

Thank you for your help.

**Comment by philippe44** [comment]
I don't know MacOS much, but if you look in the closed issues, you'll see that it's likely a permission/firewall issue and I think others have found the solution

**Comment by krunal-shah** [comment]
Thank you for the pointer. Turning off the Firewall makes it work.
