### ISSUE TITLE
Error when trying to play from Soundsync

### ISSUE THREAD

**Issue by balaji-dutt** [philippe44/AirConnect#281]
Hello,

[Soundsync](https://github.com/geekuillaume/soundsync) is a recently launched OSS software that provides multi-room audio across any speaker setup. I tried to add a Sonos One for playback via AirConnect to SoundSync. I'm able to add the speaker to Soundsync without any issues, but when I try to playback any music, airconnect crashes with the following messages:

```
[08:17:37.186684] MasterHandler:655 [0x6a8580]: subscribe success
[08:19:31.677463] rtsp_thread:351 got RTSP connection 15
[08:19:31.693216] handle_rtsp:399 [0x7f1db800ef70]: challenge sZVpzyqjU2YEWB17mIhVEA==
[08:19:31.709712] handle_rtsp:392 [0x7f1db800ef70]: received ANNOUNCE
[08:19:31.709845] handle_rtsp:591 [0x7f1db800ef70]: responding:
RTSP/1.0 200 OK
Audio-Jack-Status: connected; type=analog
CSeq: 2


[08:19:31.717394] handle_rtsp:392 [0x7f1db800ef70]: received SETUP
Floating point exception
```

### Version Info
- airupnp v0.2.27.0
- Ubuntu 20.04

**Comment by philippe44** [comment]
Can you do a wireshark (pcap) capture of the exchange between the SoundSync & AirConnect? Obviously, SoundSync sends commands in a unusual way

**Comment by balaji-dutt** [comment]
Hi @philippe44, the author of SoundSync pushed out v0.4.4 a few days back and one of the changes he made in that seems to have fixed the issue with AirConnect as well in terms of playback.

The only issue that's left is that whenever AirConnect restarts, the port assigned to the device changes which breaks the playback. However, I've seen other comments by you that allowing the playback ports to be fixed would be significant effort and is not likely to happen soon 🙁

**Comment by philippe44** [comment]
> The only issue that's left is that whenever AirConnect restarts, the port assigned to the device changes which breaks the playback. However, I've seen other comments by you that allowing the playback ports to be fixed would be significant effort and is not likely to happen soon
>
Yes, unlikely - I have too much on my plate currently
