### ISSUE TITLE
Can't run aircast in a arm arch router running Openwrt

### ISSUE THREAD

**Issue by coolsnowwolf** [philippe44/AirConnect#285]
Hi Philippe,

I'm trying to run  aircast and airupnp  in a arm arch router running Openwrt.

-ash: ./aircast-arm: not found

Would it be possible provide default static  build of arm and armv6  ?  Thanks !

**Comment by philippe44** [comment]
here you go

**Comment by timtn** [comment]
Does it need to be compiled with uClibc?

**Comment by coolsnowwolf** [comment]
Runs good!  Many Thx!~

Could you also  provide default static build for aarch64 ?

**Comment by philippe44** [comment]
argh ... always more :-)

**Comment by coolsnowwolf** [comment]
Ohhhhh .... Thx a lot !~

![image](https://user-images.githubusercontent.com/31687149/96968251-4f28d400-1543-11eb-90fc-cb27b8784311.png)
