### ISSUE TITLE
aircast - Cover art / now playing support?

### ISSUE THREAD

**Issue by Prouser123** [philippe44/AirConnect#288]
Just wondering? - Chromecast devices with screens as well as the Google Home app support this, might be good instead of the default "Streaming from AirConnect" message?

Edit: saw this in README, isn't possible after all?

`
The audio, after being decoded from alac, can be sent in plain, or re-encoded using mp3 or flac. Most players will not display metadata (artist, title, album ...) except when mp3 re-encoding is used and for UPnP/DLNA devices that support icy protocol. Chromecast players do not support this (yet).
`

**Comment by philippe44** [comment]
No, it's not possible. I've not checked recently if CC now supports ICY, but if it still does not work, it means it still does not not support it as I think I've enable it by default

**Comment by philippe44** [comment]
Closed for inactivity
