### ISSUE TITLE
autostart with custom config file?

### ISSUE THREAD

**Issue by bonze4** [philippe44/AirConnect#29]
I build a .service file to autostart the program with my own config file:

[Unit]
Description=AirUPnP bridge
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
ExecStart=/var/lib/airconnect/airupnp-arm -x configfile
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target

It was just a try, but it doesn't work at all. Is there a possibility to autostart the program with a custom config file?

**Comment by philippe44** [comment]
why didn't you use the one in the README?

**Comment by bonze4** [comment]
because of my naming and enable/disable settings of my devices

**Comment by philippe44** [comment]
understood but I meant you just have to use the example and add "-x configfile" on the ExecStart linbe, why removing the rest of the options? The absence of "-z" is the problem

**Comment by bonze4** [comment]
It doesn't work. I tried it with the following line of code in my .service file
ExecStart=/var/lib/airconnect/airupnp-arm -x configfile -z
The Programm still starts with the default configuration.

thx for your help and this nice program :)

**Comment by philippe44** [comment]
I assumed that "configfile" was just symbolic of the actual configuration file. You need to give the fully qualified path of the real config file, otherwise the application does not know where to find it. So, for example , use -x /var/lib/airconnect/config-upnp.xml"

**Comment by bonze4** [comment]
It works! Thank you (y)
