### ISSUE TITLE
Request Airupnp to run on the openwrt router

### ISSUE THREAD

**Issue by love3kkk** [philippe44/AirConnect#291]
As the title：

Request Airupnp to run on the OpenWrt router，run on the openwrt router is the best solution for DLNA device！ and most MT7621 platform router can be used openwrt system in 24H。

**Comment by philippe44** [comment]
See https://github.com/philippe44/AirConnect/issues/285

**Comment by dterrahe** [comment]
MT7621 is MIPS, so #143 applies.
