### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by drheiser** [philippe44/AirConnect#295]
I'm using air-upnp with osx 10.12 and 10.13. Sometimes my Sonos play 1 devices are not detected while my Samsung TV is always regonized. Sonos is up and running, no issues. After subscribing my Samsung TV no further devices are found.
I'm using this set up: airupnp-osx-multi -l 1000:2000

**Comment by philippe44** [comment]
It's usually some network (gateway) issues related to multicast / IGMP snooping
