### ISSUE TITLE
Airconnect for Amazon Echo

### ISSUE THREAD

**Issue by lockevod** [philippe44/AirConnect#297]
Great work. I’m using air connect  with my chromecast devices but I want to migrate to Amazon echo (I prefer Alexa) and I think airconnect is not compatible with echo studio. Could you add this feature in future?

Thanks for your support

**Comment by philippe44** [comment]
Thanks - Unfortunately the way the Echo works make impossible to have controller-initiated playback. It's a very "voice-prompt/Amazon-centric" system
