### ISSUE TITLE
Buffer Overrun and no sound with SONOS

### ISSUE THREAD

**Issue by AlfaJackal** [philippe44/AirConnect#298]
I am trying to run AirConnect with my SONOS speakers. Unfortunately it does not work. Maybe you could have a look at my log:
https://codeshare.io/5Qoegw

uPNP and mDNS is enabled on my network.

Do you have an Idea what is going on and how to fix it?

**Comment by philippe44** [comment]
Your Sonos is not consuming the audio accumulated by airupnp. Maybe there is something wrong with parameters you're using

**Comment by philippe44** [comment]
Closed for inactivity
