### ISSUE TITLE
"No config file, using defaults" when there's a config file in the directory?

### ISSUE THREAD

**Issue by Abcmsaj** [philippe44/AirConnect#299]
<img width="434" alt="Screenshot 2020-11-17 at 15 06 50" src="https://user-images.githubusercontent.com/5143023/99407004-85f5ce00-28e6-11eb-9769-5fdb9756abd5.png">

I'm testing this on my Mac to ensure it works before I eventually move it to my Pi, but one thing I wasn't happy with was the volume on the Google devices is v quiet - also would like to rename the devices - so generated a config file using -i and edited it.

Ran the exec again and the first message I see is "no config file, using defaults" - I've tried renaming the .yml ext to .yaml just in case it couldn't see the file (even though it generated it like that!) - still no luck. When I run -i again, it overwrites the config file with default settings.

**Comment by philippe44** [comment]
it's a .xml file by default and you have to use -x to use it. The -i is just to create it, per documentation

**Comment by Abcmsaj** [comment]
Got it, thank you - Ctrl + F on the documentation for "-x" and the only instance of it being mentioned is in the auto Linux install section - so might be useful to mention it at the top of Config File Parameters section or even inside the Common Info - but thanks for letting me know!
