### ISSUE TITLE
UFW & Dynamic Ports

### ISSUE THREAD

**Issue by velafamily** [philippe44/AirConnect#301]
How do I make UFW work with dynamic ports? This was an issue brought up in issue #91 but no solution was every made available.

**Comment by AndreasPantle** [comment]
If your server is in a LAN environment you can open LAN connections by adding the rule:

```
$ sudo ufw allow from 192.168.xxx.0/24
```

This means that all incoming connections from 192.168.xxx.1 up to 192.168.xxx.254 are allowed.

**Comment by philippe44** [comment]
I don't have plans currently to restrict port usage to a certain range. It sounds simple but there are some complications that I don't gave time to deal with currently

**Comment by philippe44** [comment]
Well, finally done. See -a or <ports> parameter

**Comment by Luncheon3462** [comment]
> I tried to limit the port range using `-a`, but still some other ports were used. Using `netstat -tulpn | grep air`, I found the following additional ports (neither listed in the Readme nor specified with `-a`) being used while playing:
> 
> * 49152/tcp
> * 1900/udp
> * two dynamic udp ports, e.g. 49292 and 51140, they change when restarting airconnect
> 
> @AndreasPantle's workaround works fine:
> 
> > $ sudo ufw allow from 192.168.xxx.0/24
> > $ sudo ufw disable && sudo ufw enable
> 
> But I think it would be great to limit those two dynamic ports to the range defined with `-a`.

I am new to this, can someone please share what impact allowing the ports from 192.168.xxx.0/24 has on security?  My server is generally not visible from the internet as I use cloudflare tunnels.    Is there any way in the config for this app to force it to use the same ports every time?

**Comment by philippe44** [comment]
-a only sets the dynamic ports, opened while a steaming session opens. The UPnP ports 49152 and 1900/UDP are unaffected by this parameter.

**Comment by Luncheon3462** [comment]
Apologies for being a noob.   Are you saying that I could control which ports are used every time?

**Comment by philippe44** [comment]
> Apologies for being a noob. Are you saying that I could control which ports are used every time?
>
Yes, -a controls (should at least...) which dynamic ports are opened. So basically, it is 49152+1900 + whatever you specify with -a

**Comment by Luncheon3462** [comment]
Thank you for being patient with me.   In the readme file, you state that:

Use -a <port>[:<count>] to specify a port range (default count is 128, sets RTP and HTTP ports)

1.  what does count mean?
2. can you share with me an example of what I would enter into the command line terminal so that the dynamic ports are the same every time?

thank you.   do you have a link where I can donate to support your efforts?

**Comment by philippe44** [comment]
From memory, you specific a base per and then the maximum number of ports (the count). So for example -a 50000:64 says you can open up to 64 ports starting at 50000

**Comment by Luncheon3462** [comment]
> If your server is in a LAN environment you can open LAN connections by adding the rule:
> 
> ```
> $ sudo ufw allow from 192.168.xxx.0/24
> $ sudo ufw disable && sudo ufw enable
> ```
> 
> This means that all incoming connections from 192.168.xxx.1 up to 192.168.xxx.254 are allowed. Don't know if someone uses somethink better - I guess with UFW there is no other possibility in this matter.

@AndreasPantle My server (192.168.1.44)  is in my home (Router is 192.168.1.1) and is not exposed to the internet because I use cloudflare tunnels for anything I need to access via the internet.    The devices I want to listen to music on are at 192.168.1.66 and 192.168.1.88.   Can you help me better understand

1.  What is the exact command I need to type to allow the ports to open on my server (which is at 192.168.1.44)?
2. Is it safe to issue this command if my server is not exposed to the internet (I am using cloudflare tunnels)

Thank you for being patient with me.

**Comment by AndreasPantle** [comment]
> > If your server is in a LAN environment you can open LAN connections by adding the rule:
> > ```
> > $ sudo ufw allow from 192.168.xxx.0/24
> > $ sudo ufw disable && sudo ufw enable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This means that all incoming connections from 192.168.xxx.1 up to 192.168.xxx.254 are allowed. Don't know if someone uses somethink better - I guess with UFW there is no other possibility in this matter.
> 
> @AndreasPantle My server (192.168.1.44) is in my home (Router is 192.168.1.1) and is not exposed to the internet because I use cloudflare tunnels for anything I need to access via the internet. The devices I want to listen to music on are at 192.168.1.66 and 192.168.1.88. Can you help me better understand
> 
> 1. What is the exact command I need to type to allow the ports to open on my server (which is at 192.168.1.44)?
> 2. Is it safe to issue this command if my server is not exposed to the internet (I am using cloudflare tunnels)
> 3. Would {sudo ufw allow from 192.168.1.66} and {sudo ufw allow from 192.168.1.88} achieve the same?
> 4. Would {sudo ufw allow "airupnp-linux-x"} achieve the same?
> 
> Thank you for being patient with me.

You can take the same command with your servers ip address:

``` bash
$ sudo ufw allow from 192.168.1.44/24
$ sudo ufw disable && sudo ufw enable
```

So if your server is behind a firewall (save zone) which restricts the traffic to your LAN...
