### ISSUE TITLE
iOS/iPadOS

### ISSUE THREAD

**Issue by cedecode** [philippe44/AirConnect#302]
Is there a chance to get it to work on iSH (iOS-terminal with Alpine Linux)?
I use AirConnect just occasionally, so there would be no need to plug in and shut down a raspberry pi.

**Comment by philippe44** [comment]
It's a CPU emulator so it's probably way to slow, but you can try. AirConnect builds include a variety of OS and CPU, including x86 (32 and 64 bits)

**Comment by cedecode** [comment]
Thank you. Of course, emulation could be too slow. I tried it, x86 32 bit should be the best choice.
After adding `libc6-compat` I get:
> Error relocating ./airupnp-x86: __strcat_chk: symbol not found
> Error relocating ./airupnp-x86: __snprintf_chk: symbol not found
> Error relocating ./airupnp-x86: __vfprintf_chk: symbol not found
> Error relocating ./airupnp-x86: __fdelt_chk: symbol not found
…

Maybe some other components are missing, maybe the emulation is not compatible, but it was worth a try.

**Comment by pwt** [comment]
Try a static binary.

**Comment by cedecode** [comment]
> Try a static binary.

It‘s only a 32-bit-shell and unfortunately there‘s no `airupnp-x86-static`.
(Even though I tried `airupnp-x86-64-static` without success.)

**Comment by philippe44** [comment]
Let me know if this one works
[airupnp-x86-static.zip](https://github.com/philippe44/AirConnect/files/5939903/airupnp-x86-static.zip)

**Comment by cedecode** [comment]
> Let me know if this one works

So nice from you to compile this!
The good message: It’s is the first binary that runs with iSH (iOS).
Unfortunately, it calls a system function which isn‘t implemented yet. `dmesg` says  `missing syscall 160`

I think it‘s up to iSH. It‘s okay if you would close this thread now.

**Comment by philippe44** [comment]
Ok
