### ISSUE TITLE
Ignore Speakers Already Enabled with Airplay or Airplay 2

### ISSUE THREAD

**Issue by tyehill** [philippe44/AirConnect#303]
My network has a mixture of Airplay enabled Sonos Speakers and non-Airplay enabled speakers. If I run AirConnect, then some of my speakers show up twice. 

Is there any way to specifically ignore some speakers?  I looked through the configuration, but I didn't see anything about excluding speakers other than just setting a max limit.

**Comment by pwt** [comment]
Start `airupnp` with the `-o` option. Specifically, use:
```
-o S1,S3,S5,S9,S12,ZP80,ZP90,S15,ZP100,ZP120
```
to include any instances of Sonos speakers that don't natively support AirPlay 2.

**Comment by tyehill** [comment]
Well - that worked perfectly. Now I need to figure out how to generate/edit a config file so I don't have to start it over ssh every time. Thanks!

**Comment by RezzZ** [comment]
> Well - that worked perfectly. Now I need to figure out how to generate/edit a config file so I don't have to start it over ssh every time. Thanks!

did you figure this out? how do we add the "-o S1,S3,S5,S9,S12,ZP80,ZP90,S15,ZP100,ZP120" using a docker container and make it persist?
