### ISSUE TITLE
General Request for Help, Sonos Speaker doesnt Play

### ISSUE THREAD

**Issue by DarkLordImperatus** [philippe44/AirConnect#305]
I installed airupnp-win.exe on my computer, along with the four downloaded dll's in the same folder. Running windows.
When i run the startup command ./airupnp-win.exe -l 1000:2000 the server starts up correctly.
If I push a volume button on the Sonos playbar, it registers on the server as a local change (aka it DOES see the playbar through the wifi.... good job on that btw.)
But, no audio comes from my computer. I likely just dont know where to look to get the audio to go from my computer to the server. Can anyone help?

**Comment by pwt** [comment]
You need to play audio from an AirPlay client. Clients include all Apple macOS, iOS and iPadOS devices, and also (I think) iTunes running on Windows. If you have these devices, AirConnect running on your Windows PC will bridge their audio output to your Playbar -- i.e., it acts as an AirPlay target for the Apple devices, and sends their audio to Sonos.

There may be other third-party methods to play directly from Windows, e.g., see:
https://www.lifewire.com/where-to-get-airplay-for-windows-2000736

**Comment by DarkLordImperatus** [comment]
Wait, so does that put me right back at effectively "streaming music from app"? I was hoping to find a way around and use it as computer speakers.

**Comment by pwt** [comment]
Unfortunately, I think you've misunderstood the purpose of AirConnect. You may want to take a look at 'Stream What You Hear' instead: https://github.com/StreamWhatYouHear/SWYH.
