### ISSUE TITLE
Works on Mac, but not Pi

### ISSUE THREAD

**Issue by darryllee** [philippe44/AirConnect#307]
Hey there - this was exactly what I was looking for, so great. On my Mac (OS X 10.14.6), it works perfectly.

But I have two Raspberry Pis, a Pi 2, and a Pi Zero, and neither of them seem to be able to "find" the Chromecasts.

I've had success on the Mac on either of my two wifi networks (it's... complicated), as well as the wired network. All the same subnet.

But the Pi 2 is on the wired network, the PiZero is on the wireless, and neither one seems to be able to detect any Chromecasts.

I even tried saving the configuration from the Mac and using it on the Pis, with no success. 

Any ideas? Would love to have this always running on one of my underused Pis. (Pi 2 = PiHole, Pi Zero = print server, and backup PiHole.)

Thanks!

**Comment by philippe44** [comment]
It's likely a routing problem between your networks and especially the possibility to have broadcast/multicast on both. Check around that in your router

**Comment by darryllee** [comment]
Turns out I'm an idiot. I had downloaded and tried to run airupnp-arm instead of aircast-arm. Works perfectly. Thank you so much!
