### ISSUE TITLE
Standardise assets delivery

### ISSUE THREAD

**Issue by orbsmiv** [philippe44/AirConnect#309]
Firstly, really loving this project!

This is more of a request than an issue per se (and apologies if it's previously been asked) but would it be possible to make the assets (i.e. compiled binaries) available as _release assets_, rather than within the repository itself? It is unusual to include compiled materials in the repository as they're essentially ephemeral but making them available as release assets pins them to a specific version (which is always good!) but also allows other applications that use the Github API (e.g. https://github.com/autopkg/autopkg/wiki/Processor-GitHubReleasesInfoProvider) to access them in a standardised fashion. 

(An example of release assets in action can be seen here: https://github.com/supercollider/supercollider/releases)

(Depending on the compilation process you might also be able to leverage Github Actions to automatically build and attach the assets each time you define a release.)

**Comment by philippe44** [comment]
I know... you'right I'm just lazy with releases. At least I just tag version 0.2.30.0 ad added the binaries. I'll see if I can automate something with actions, I've just never looked into it.

**Comment by orbsmiv** [comment]
Many thanks – the binaries zip file asset is a great help!
