### ISSUE TITLE
"Stop Receiver" parameter

### ISSUE THREAD

**Issue by lars18th** [philippe44/AirConnect#31]
Please, can you explain the behaviour of the "Stop Receiver" parameter in the config file?

I can't see it the the README page.

Thank you!

**Comment by philippe44** [comment]
It's an amlost deprecated parameter. Google released a few month ago a buggy version of their receiver firmware. which was having a dead lock when a "stop" command was issue. The only option was to "unload" this receiver and to "reload" it between tracks. This parameters allowed that.

FYI, Chromecast devices require an application (a "receiver") to be loaded inside the device to handle audio/video download protocol and playback timing. Google provides a default version, but one can built their own. For example, this is how netflix (on CCV) handle DRM, by having their own app loaded in the CC and managing user authentification

**Comment by lars18th** [comment]
> FYI, Chromecast devices require an application (a "receiver") to be loaded inside the device to handle audio/video download protocol and playback timing. Google provides a default version, but one can built their own.

Thank you @philippe44 for this technical explanation. So, you know if it will be possible to compile a "custom" receiver for this project?

**Comment by philippe44** [comment]
yes
