### ISSUE TITLE
Airplay device from AirConnect doesn't show up in LMS

### ISSUE THREAD

**Issue by Briffou** [philippe44/AirConnect#313]
First, thanks for your apps ! 
Here is the situation: I have one airplay device and one chromecast device, both showing up and working correctly in LMS (thanks to your Airplay and Chromecast bridges). 
The issue is that I can't correctly sync audio between the two devices (which is expected I think) , so I decided to turn the chromecast receiver into an airplay receiver in hope of improving synchronization . First question : Is that a good idea ? If no, no need to read further !

In order to turn the chromecast into airplay receiver, I use AirConnect (the Syno package from @eizedev). So far so good, installation works and my chromecast device show up as an airplay device on my iPhone, and I can stream music from my iphone to the chromecast device.
But, the "new" airplay device (the chromecast) doesn't show up in LMS for any reasons. Any ideas why ?

**Comment by philippe44** [comment]
You cannot get sync between a CC device and any other device (except other CC from within the Google app by creating groups of course). AirConnect does not bring sync because it brings AirPlay

**Comment by Briffou** [comment]
That's what I thought. Had to try. Thanks !
