### ISSUE TITLE
Can't execute on Ubuntu 20.04

### ISSUE THREAD

**Issue by thirdcoasters** [philippe44/AirConnect#314]
When attempting to execute aircast-x86-64 the output is "bash: /var/airconnect/bin/aircast-x86–64: No such file or directory". The file is executable and seems to have the correct permissions. I don't see any missing dependencies when I run ldd. I'm sure I'm missing something simple here, any help would be appreciated. Thanks.

**Comment by philippe44** [comment]
What is exactly your OS?

**Comment by pwt** [comment]
> When attempting to execute aircast-x86-64 the output is "bash: /var/airconnect/bin/aircast-x86–64: No such file or directory". The file is executable and seems to have the correct permissions. I don't see any missing dependencies when I run ldd. I'm sure I'm missing something simple here, any help would be appreciated. Thanks.

Make sure you've downloaded the actual executable by checking that the file sizes match locally and on GitHub.

**Comment by thirdcoasters** [comment]
It's definitely 64-bit.

> What is exactly your OS?
> 
> [edit]: oops, missed the title. So I tried on my 20.04 x86 VM and it worked. Are you 100% sure you've installed the 64 bits version of Ubuntu?

**Comment by thirdcoasters** [comment]
> > When attempting to execute aircast-x86-64 the output is "bash: /var/airconnect/bin/aircast-x86–64: No such file or directory". The file is executable and seems to have the correct permissions. I don't see any missing dependencies when I run ldd. I'm sure I'm missing something simple here, any help would be appreciated. Thanks.
> 
> Make sure you've downloaded the actual executable by checking that the file sizes match locally and on GitHub.

File sizes match between my system and github.

**Comment by thirdcoasters** [comment]
Well after another reboot it's working now. ¯\_(ツ)_/¯

Please close and sorry for the hassle.

**Comment by philippe44** [comment]
No worries
