### ISSUE TITLE
Sonos stereo pair not working

### ISSUE THREAD

**Issue by jacobScottAllen** [philippe44/AirConnect#315]
Hello,

AirConnect is working for almost all of my Sonos speakers (play:1) except for a stereo pair. When I connect to the speaker pair, it will play, but only for a few seconds before stopping. It works fine when I separate the stereo pair and pair them (non-stereo) in the Sonos app.

## System information:
* Running on Raspberry Pi 3b
* 4 Sonos Play:1, 1 Sonos move (disabled through config file)

**Comment by pwt** [comment]
Just to note that there's no issue in general with AirConnect and Sonos stereo pairs, including when running on a Pi 3.

If you have Docker running on the Pi, you might want to try my Sonos-optimised Docker image for Pi devices: https://github.com/pwt/docker-airconnect-arm, to see if you get the same behaviour.

**Comment by jacobScottAllen** [comment]
Thank you for your response! 

As a follow-up, I believe this was a performance issue with the raspberry pi itself and not AirConnect.

**Comment by philippe44** [comment]
Good!
