### ISSUE TITLE
Also AirPlay Enabled Sonos Devices are being shown

### ISSUE THREAD

**Issue by tosten8489** [philippe44/AirConnect#316]
Is it possible to exclude airplay enabled Sonos devices from the running service? They show up as doublets in the iOS airplay picker.

**Comment by eizedev** [comment]
@tosten8489 

Sure, you could use the `-o` (include only listed models) argument for `airupnp` to only show the `models` specified with `-o`, no other speakers will be discovered by airupnp.

So it is not an exclude for all new speakers, it is an include for all old speakers.

> If you have other speakers rather than sonos, you also need to add their model numbers to the list.
> Instead of `-o` you can use `-m` for excluding model numbers or `-n` for excluding model names.

With `-o S1,S3,S5,S9,S12,ZP80,ZP90,S15,ZP100,ZP120` only the following device models will be discovered, so no speakers that are natively supporting AirPlay will be discovered:

| Model Number  | Friendly Name                       | Comment (Sonos seriesid, etc.) |
| ------------- | ----------------------------------- | ------------------------------ |
| S1            | Sonos Play:1                        | A101                           |
| S3            | Sonos Play:3                        | A100                           |
| S5            | Sonos Play:5                        | P100                           |
| S9            | Sonos Playbar                       | A100                           |
| S12           | Sonos Play:1                        | A200                           |
| S15           | Sonos Connect                       | S100                           |
| ZP80          | Sonos Connect (Previous)            | C100                           |
| ZP90          | Sonos Connect                       | C100                           |
| ZP100         | Sonos Connect:Amp (Previous)        | P100                           |
| ZP120         | Sonos Connect:Amp                   | P100                           |

#### airupnp command line arguments

```bash
v0.2.41.0 (Dec  8 2020 @ 18:43:14)
See -t for license terms
Usage: [options]
  -b <server>[:<port>]  network interface and UPnP port to use
  -a <port>[:<count>]   set inbound port and range for RTP and HTTP
  -c <mp3[:<rate>]|flc[:0..9]|wav|pcm>  audio format send to player
  -g <-3|-1|0>          HTTP content-length mode (-3:chunked, -1:none, 0:fixed)
  -u <version>  set the maximum UPnP version for search (default 1)
  -x <config file>      read config from file (default is ./config.xml)
  -i <config file>      discover players, save <config file> and exit
  -I                    auto save config at every network scan
  -l <[rtp][:http][:f]> RTP and HTTP latency (ms), ':f' forces silence fill
  -r                    let timing reference drift (no click)
  -f <logfile>          write debug to logfile
  -p <pid file>         write PID in file
  -m <n1,n2...>         exclude devices whose model include tokens
  -n <m1,m2,...>        exclude devices whose name includes tokens
  -o <m1,m2,...>        include only listed models; overrides -m and -n (use <NULL> if player don't return a model)
  -d <log>=<level>      Set logging level, logs: all|raop|main|util|upnp, level: error|warn|info|debug|sdebug
  -z                    Daemonize
  -Z                    NOT interactive
  -k                    Immediate exit on SIGQUIT and SIGTERM
  -t                    License terms
```

**Comment by pwt** [comment]
This is also discussed in: https://github.com/philippe44/AirConnect/issues/303.

**Comment by tosten8489** [comment]
Thanks a lot. Must have missed that.

**Comment by pwt** [comment]
> Thanks a lot. Must have missed that.

Feel free to close this issue ...
