### ISSUE TITLE
Samsung TV + Ikea Symfonisk

### ISSUE THREAD

**Issue by guberta** [philippe44/AirConnect#317]
Hi @philippe44 , I have a question because maybe I didn't understand it correctly. I have a Samsung TV and a Sonos Ikea Symfonisk, but the TV can't stream audio to my Sonos. Is this helping me with that? Because it's not clear for me. Pleas help me!!

When I installed it and run it, it only shows my TV as a duplicated Airplay device. But not my speak as a new device that the TV can stream.

**Comment by pwt** [comment]
AirConnect won't help: your Samsung TV is a target audio device (i.e., an output device), not a client (input) device.

**Comment by guberta** [comment]
Got it. One more question, if you know something about it: my TV can also be a input device to stream to specific Samsung Wireless Speakers. My idea is to "fake" a Samsung Wireless Speaker. Have you heard something about that? My curiosity is about how the Samsung Speaker are announcing themselves over the network that allows the TV to recognize how the network package looks like, what is the protocol and so on. Do you know maybe where can I find it?

**Comment by pwt** [comment]
Sorry -- no idea.

If one could develop software that does this, the big problem would be with audio/video synchronisation. Any bridge solution would require some buffering, which would destroy sync. (This is why AirConnect itself is unsuitable for use with video sources.)
