### ISSUE TITLE
I am extremely confused.

### ISSUE THREAD

**Issue by jaackelliott** [philippe44/AirConnect#318]
I came across this while wanting to have my Chromecast have airplay support. I have no experience in programming and would like to set this up on a Windows computer. Could you please extremely dumb this down for people like me?

**Comment by pwt** [comment]
Start by downloading the following files from https://github.com/philippe44/AirConnect/tree/master/bin :

```
aircast-win.exe
cc32160mt.dll
libeay32.dll
pthreadBC2.dll
ssleay32.dll
```

Then run the `aircast-win.exe` file. This should establish a basic, working AirPlay to AirCast bridge for your Chromecast devices.

Assuming you get this far, you can then think about how to run it as a self-starting service in the background.

**Comment by serialtoon** [comment]
> Start by downloading the following files from https://github.com/philippe44/AirConnect/tree/master/bin :
> 
> ```
> aircast-win.exe
> cc32160mt.dll
> libeay32.dll
> pthreadBC2.dll
> ssleay32.dll
> ```
> 
> Then run the `aircast-win.exe` file. This should establish a basic, working AirPlay to AirCast bridge for your Chromecast devices.
> 
> Assuming you get this far, you can then think about how to run it as a self-starting service in the background.

Download NSSM on Windows and set it as a service. Make sure you place the AirConnect folder with the files needed in a location that will stay there (maybe not your Desktop folder :P) 

Extract NSSM to a location ex. C:\
Open powershell or cmd type in nssm.exe install
Via the wizard select where aircast-win.exe is located
Once the service is created, you should see it in services.msc, right click and Start Service

**Comment by philippe44** [comment]
Closed for inactivity
