### ISSUE TITLE
FreeBSD version?

### ISSUE THREAD

**Issue by mk-conn** [philippe44/AirConnect#32]
Hi,

just wanted to ask, if its possible to get a binary that runs on FreeBSD?

**Comment by philippe44** [comment]
I don't have such build environement, so I can't, sorry

**Comment by mk-conn** [comment]
Okay, to bad. Maybe somebody could give me hint on how to compile that stuff myself?

**Comment by philippe44** [comment]
Most of the code should compile under freeBSD, there bunch of #define for that. What's the architecture you're using (arm, x86, x64)? I cant probably make the 1st compilation, but I will not make it part of my regular builds. When I now which CPU you want, I'll download a VM

**Comment by mk-conn** [comment]
Great! FreeBSD 11.0-STABLE amd64

**Comment by philippe44** [comment]
Good news is that it builds, runs and find devices, bad news is that there seem to be a networking issue of somekind which prevents proper connections to happen. I don't know what to do at that point and I can't investigate more. It might be due to my VM, so you can find the binaries here in bin/

**Comment by mk-conn** [comment]
Man! Thx a lot! It works like charme :)
