### ISSUE TITLE
Which binary to choose for PC Engines APU2 AMD64 platform

### ISSUE THREAD

**Issue by retostuder** [philippe44/AirConnect#323]
I was wondering if there was a binary available for download for the above mentioned platform?
If not, how would one compile the sources?
Thanks.
Reto

**Comment by philippe44** [comment]
If you run Linux, the x86-64 should do

**Comment by retostuder** [comment]
Dear Philippe,
Yes, it's working! No issues at all. "It just works". 
Working flawlessly on a PC Engine APU2 box with Debian 10.7 and your x86-64 binary.
What a great piece of software. No more going into the clunky Sonos S1 interface to listen to some AppleMusic.
Many thanks,
Reto
