### ISSUE TITLE
Raspberry/Stuck on “Binding to IP ADDRESS”

### ISSUE THREAD

**Issue by jolimk** [philippe44/AirConnect#324]
Hello, everyone.

I’m trying to install aircast-arm on my Raspberry Pi but I cant get it to work.  The installation is very fast but when I run aircast, I only get 3 lines, the last one just says Start:727 Binding to <IP ADDRESS>, and doesn’t list all my devices that are connected. What am i doing wrong? 

Thank you very much for all your help!

**Comment by jolimk** [comment]
@pwt

**Comment by pwt** [comment]
Note that I'm generally not much help on **aircast** as I have no compatible devices.

I include aircast in [docker-airconnect-arm](https://github.com/pwt/docker-airconnect-arm) as a convenience. Users tell me it works well for them, but I've never been able to test it myself.

**Comment by jolimk** [comment]
I’m not using docker... no idea how to do this, no idea what is that... sorry 😞

**Comment by philippe44** [comment]
can you describe your network a bit and post these 3 lines

**Comment by jolimk** [comment]
@philippe44 Thank you for getting back to me. I was doing something wrong and now it works. Sorry to bother you!! GREAT PROJECTO

**Comment by bertdom** [comment]
I'm running into the same problem. What did you do to resolve @jolimk

**Comment by jolimk** [comment]
Check your wifi settings. I had my Raspi connected to a different Wifi, same router, same home, but different SSIDs. Connected speakers AND raspi to same ssid fixed the issue.

**Comment by philippe44** [comment]
Closed for inactivity
