### ISSUE TITLE
video and sound can't be out of sync.

### ISSUE THREAD

**Issue by chuangzl** [philippe44/AirConnect#325]
when i see video in mac. airconnect version is 0.2.43.1. i changed sound to airconnect's output , so  the sound is delay to video speed. around 1-2 seconds. so there is some of config issues or others ? thanks.

some of log:
main:1415 Starting airupnp version: v0.2.43.1 (Jan 1...8:02)
airupnp-x86-64-static[1202]: [13:54:14.977640] main:1423 no config file, using defaults
airupnp-x86-64-static[1202]: [13:54:14.983185] Start:1127 Binding to 192.168.1.17:49152
airupnp-x86-64-static[1202]: [13:54:18.077283] AddMRDevice:1005 [0x7f74f1558010]: adding renderer (…-4940)
airupnp-x86-64-static[1202]: [13:54:18.077343] AddMRDevice:1032 [0x7f74f1558010]: cannot get mac …159603f
airupnp-x86-64-static[1202]: [13:54:18.099444] MasterHandler:668 [0x7f74f1558010]: subscribe success

**Comment by philippe44** [comment]
Please read the READMZ https://github.com/philippe44/AirConnect/blob/master/README.md
