### ISSUE TITLE
How to upgrade on RaspberryPi?

### ISSUE THREAD

**Issue by Sthelens1** [philippe44/AirConnect#327]
I note my installed version is a couple of releases behind current. How do I upgrade to this version? I regularly update raspberry Pi but I don't think AirConnect features in a repository so isn't updated automatically. I'm pretty much a noob when it come to Linux so sorry in advance if this is obvious.

**Comment by philippe44** [comment]
You can just copy over the updated files (airupnp & aircast) that match your OS/CPU
