### ISSUE TITLE
Cannot execute AirConnect on DS920+

### ISSUE THREAD

**Issue by Tatti01** [philippe44/AirConnect#328]
Hi Philippe,

I installed the actual file "AirConnect-x86-64-0.2.43.1-20210119.spk". When I try to activate, I get the message "Der Paketdienst konnte nicht ausgeführt werden".
Do you know, what's going wrong?

Regards
Michael

**Comment by eizedev** [comment]
Hi @Tatti01 

i think you have installed my package from https://github.com/eizedev/AirConnect-Synology, right? 
The downloaded package matches to the architecture of your NAS, DS920+, so it should start. 

Which speakers do you have in your network that you want to control with airupnp/aircast?
Do you have access to your NAS via SSH and can post the output of the [airconnect.log](https://github.com/eizedev/AirConnect-Synology#logfiles) here?

Also please take a short look at the [Readme](https://github.com/eizedev/AirConnect-Synology/blob/master/README.md). Some resolutions for common problems are explained there.

Thanks,
René

**Comment by Tatti01** [comment]
Hi @eizedev,

because I couldn't find this file in /var/log I deleted the package and reinstalled the package again. Now everything is working fine.
Sorry for my posting and thank you very much for your fast help.
Best regards
Michael
