### ISSUE TITLE
Volume needs to be adjusted after the script starts before Sonos starts playing anything

### ISSUE THREAD

**Issue by DeveloperACE** [philippe44/AirConnect#33]
In my quest to stream audio from my computer (macOS 10.13.2) to my Sonos PLAY:1 over ethernet, I have to say this is by far the best solution that I have tried so far so thank you!

While u sing v0.1.5.2 I have noticed that, after starting the script, my SONOS only seems to start actually playing the audio after I have hit either of the volume adjust keys on my keyboard.

This is just something I happened to notice and shouldn't be too major as I presume many people start this running once and forget about it.

Thanks for an awesome script!
DeveloperACE

**Comment by philippe44** [comment]
Did it happen with previous versions?

**Comment by DeveloperACE** [comment]
I don't know. I have only used the latest version and then kinda gave up on my project.

**Comment by philippe44** [comment]
I cannot reproduce it

**Comment by DeveloperACE** [comment]
I can't seem to either now. It was probably just a glitch on my end. My apologies.
