### ISSUE TITLE
Mac os iTunes sees sonos speaker pair but won't play

### ISSUE THREAD

**Issue by srolfe76** [philippe44/AirConnect#336]
I have an old MacBook Air running OSX 12.6 and iTunes 12.8.2.3. I have installed airconnect on a Pi0W. The setup works fine with my iPhone and I can send audio to the sonos speakers.

iTunes sees the speaker pair but doesn't stream to them.

This is the only entry i can see being generated trying to connect iTunes to the speakers

Mar 16 10:16:58 raspberrypi airupnp-arm[7494]: [10:16:58.638896] rtsp_thread:347 got RTSP connection 12
Mar 16 10:16:58 raspberrypi airupnp-arm[7494]: [10:16:58.654596] rtsp_thread:362 RTSP close 12

**Comment by philippe44** [comment]
Probably a firewall issue

**Comment by srolfe76** [comment]
Thanks, as a further update it's just iTunes Radio that won't stream. Music in the library is fine.
