### ISSUE TITLE
Disabling Some Devices

### ISSUE THREAD

**Issue by HanYolo44** [philippe44/AirConnect#337]
First off, thank you for creating airconnect. It's brought new life to my older Sonos speakers!

I just set up Airconnect on a raspberry pi.  I'd like it so that it only adds a single pair of Sonos Play 3 speakers to the airplay list, rather than everything it can find.  I've created a config.xml file, and set all the devices other than the ones I want to <enabled>0</enabled>, but all the devices still show up and some are duplicates of Sonos speakers that already have airplay.

Is there a way to make it behave the way I want? Thank you.

**Comment by pwt** [comment]
See: https://github.com/philippe44/AirConnect/issues/303 for a discussion of this.

Basically, in your case you can just start `airupnp-arm` with the command line option `-o S3`.

You might also want to take a look at: https://github.com/pwt/docker-airconnect-arm for a convenient, Sonos-optimised packaging of AirConnect.

**Comment by HanYolo44** [comment]
Perfect thank you!
