### ISSUE TITLE
Unable to see all audio devices in 3rd party software (Airfoil)

### ISSUE THREAD

**Issue by mhdj14** [philippe44/AirConnect#343]
I have been using AirConnect for a while now, and I must say that it works almost perfectly, outside of the occasional audible clicks you can throughout streaming audio via AirConnect.

My main and only issue I have is that I'm unable to group audio devices, so I can send audio to multiple devices at the same time. This is A Mac related issue, so unless it's possible to add grouping as a feature to Airconnect, it's not possible to do this natively (at this moment).

`If you want to skip the over-explanation and go directly to the crux of my question, then go to the text starting with "^" at the bottom.`

Here is where a program called [Airfoil](https://rogueamoeba.com/airfoil/mac/) comes into place. This software allows you to connect to any UPNP enabled device you want and how many you want at the same time to send audio to.

This is an image of how airfoil looks to me (on the right).

<img width="963" alt="Airfoil 1" src="https://user-images.githubusercontent.com/82095512/113865273-325c2200-97ac-11eb-81a8-ae991181d800.png">

As you can see Chromecast and Airplay devices show up natively in Airfoil. You can also see my computer as both a Chromecast and Airplay device thanks to [Airserver](https://www.airserver.com/Mac) (as seen in the image on the left). Airserver is a program that turns your computer into an Airplay and Chromecast video and audio receiver. So it appears that Airserver works with Airfoil.

Now I'm going to start AirUPNP to find my 2 HEOS speakers. This is the log:

> [14:22:46.024526] main:1420 Starting airupnp version: v0.2.50.4 (Mar 13 2021 @ 17:31:30)
> [14:22:46.024942] main:1428 no config file, using defaults
> [14:22:46.025463] Start:1130 Binding to 192.168.2.100:49152
> [14:22:46.074986] XMLGetFirstDocumentItem:1438 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL
> [14:22:46.075002] XMLGetFirstDocumentItem:1438 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL
> [14:22:46.083730] AddMRDevice:1008 [0x7fde79d17000]: adding renderer (PHILIPS TV)
> [14:22:46.094252] MasterHandler:669 [0x7fde79d17000]: subscribe success
> [14:22:46.110396] AddMRDevice:1008 [0x7fde79d193d0]: adding renderer (Keuken)
> [14:22:46.116798] MasterHandler:669 [0x7fde79d193d0]: subscribe success
> [14:22:47.104843] AddMRDevice:1008 [0x7fde79d1b7a0]: adding renderer (HEOS Link ATC)
> [14:22:47.108852] MasterHandler:669 [0x7fde79d1b7a0]: subscribe success

As you can see it can see my 2 HEOS speakers "Keuken" and "HEOS Link ATC" as well as my TV "PHILIPS TV".

In the next image you can see that my Mac recognizes them (as indicated by the "+" symbol), yet Airfoil doesn't recognize them all.

<img width="547" alt="Airfoil 2" src="https://user-images.githubusercontent.com/82095512/113867241-954eb880-97ae-11eb-8c0c-61fdd4ce13a7.png">

As you can see, Airfoil can only recognize 1 of them, and if you look loser at the AirUPNP log, it only shows the first device it found (at the bottom of the speaker list in Airfoil).

The first speaker is more or less random, as closing and restarting AirUPNP generally results in a different speaker being discovered first, which results in Airfoil recognizing a different AirUPNP speaker then the previous time.

^ For some reason Airfoil has no issues seeing the Airplay and Chromecast devices made by Airserver, yet it can only show the first device AirUPNP found and no others. I think has something to do with how AirUPNP "makes" these speakers. But I have no clue what exactly causes this issue.

&nbsp;

_Sorry for the wall of text, I just wanted to be sure anybody reading this understands what my issue is as as completely as possible._ 

&nbsp;

Is there anybody willing to take a look at this? If you have anything I could test out to see if it can solve the issue, then I glady test it out.

**Comment by timtn** [comment]
Does renaming the speakers with a config file help?

**Comment by artxia** [comment]
I am in the exact same situation.
In fact, after my tests, "Airfoil" only recognizes the first "airupnp" audio device that is loaded.
As you can see, with the "airupnp.xml" configuration file, I tested placing "play 1" and "apm+" first and second in the list.
"Airfoil" only recognizes the first device in the list every time. The macOS and iOS devices are fully recognized in all lists.

![image](https://user-images.githubusercontent.com/50513568/115154890-c6cd5b00-a0af-11eb-8cdb-e165eac8ee73.png)
![image](https://user-images.githubusercontent.com/50513568/115154922-f3817280-a0af-11eb-83a7-5699afafd9d5.png)

**Comment by philippe44** [comment]
It's not going to help much, but I remember having issues with AIrfoil in the past around that topic but can't find logs

**Comment by mhdj14** [comment]
So a new version of Airfoil just released. Version 5.10.3. And now it works as intended.

![Airfoil 5 10 3 fixed](https://user-images.githubusercontent.com/82095512/116889236-a0212f80-ac2c-11eb-90fc-95efbf40775b.jpg)

So this issue can close now...
