### ISSUE TITLE
Trying to set up on windows, but aircast keeps closing

### ISSUE THREAD

**Issue by Twistashio** [philippe44/AirConnect#344]
After about a few seconds of saying binding to ip the software closes. What could be the issue? It doesn't even give me an error message or anything...

**Comment by philippe44** [comment]
What is the command line you are using? Don't use -i as it is used for creating a reference config file and exit after ~30s

**Comment by Twistashio** [comment]
Sorry, turns out that the aircast from the zip file was not working properly. When I downloaded the individual files from the bin it started working right away.
