### ISSUE TITLE
Need to press pause->play after each initial connection with LG Soundbar

### ISSUE THREAD

**Issue by Juun89** [philippe44/AirConnect#345]
Hi,

First I want to thank you for the great piece of software. I've been running it on a Raspberry Pi and it's awesome.

There's one issue I can't seem to fix. Like the title says I have to press pause and then play after each initial connection with my LG soundbar to get the audio going. Volume control works fine right away, but audio never starts streaming. After pressing pause->play on my streaming device it works fine though. I've read the bit you wrote about the delays in the manual and I've been playing around with it, but can't get it to work. Do you have any suggestions?

Thank you very much.

**Comment by timtn** [comment]
Does [--noflush](https://github.com/philippe44/AirConnect#misc-tips) help?

**Comment by Juun89** [comment]
I edited the config file to reflect this and it worked. I did some testing with the codecs as well. Flac doesn't work with --noflush, mp3 and wav do. With wav there is almost no delay between pressing play/pause, so sticking with that for now.

Should anyone need the information, this is what I did:
Add following lines to config file:
<codec>wav</codec>
<flush>0</flush>

Or you could probably just add arguments instead:  -c wav --noflush

Thanks!
