### ISSUE TITLE
aircast-win quits with no errors on Windows 10

### ISSUE THREAD

**Issue by DanDixon** [philippe44/AirConnect#349]
Here's what happens when I try to run aircast-win.exe on my Windows 10 machine

![image](https://user-images.githubusercontent.com/10511776/117504799-e382e300-af37-11eb-9f3b-5d1e8d6f3c2c.png)

Interestingly, airupnp-win seems to work, but I'm wanting to send audio to Chromecast devices (I have 7 chromecast audio devices that I link together using speaker groups)

Thoughts on why one is working and the other doesn't? Or what to try next?

**Comment by philippe44** [comment]
Probably an issue with openSSL version on win10

**Comment by DanDixon** [comment]
Thanks for the reply. I'm unclear what steps to try next.

I installed this:
https://slproweb.com/products/Win32OpenSSL.html

But no change in the behavior of aircast-win.exe

What to try next?

**Comment by philippe44** [comment]
So AirCast just stops? No error message?

**Comment by WhiteAbeLincoln** [comment]
I am also seeing the same behavior - no error, just an immediate exit. I'm on Windows 10 Home 20H2 (build 19042.985), and running the latest version of aircast-win (0.2.50.2)

**Comment by philippe44** [comment]
Can you share your command line?
