### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by elgohr** [philippe44/AirConnect#352]
Thank you for the tool at first.

I'm just wondering why aircast occupies ~20% CPU of a raspberry pi 3B when idling.

Do you have an idea?
Will try to add benchmarks later

**Comment by pwt** [comment]
It shouldn't -- sounds like your maxing out a CPU core. So, check that you're using the -z or -Z option correctly.

**Comment by elgohr** [comment]
Exactly that. Thank you!
