### ISSUE TITLE
Chromecast metadata

### ISSUE THREAD

**Issue by yinka** [philippe44/AirConnect#358]
> Most players will not display metadata (artist, title, album ...) except when mp3 re-encoding is used and for UPnP/DLNA devices that support icy protocol. Chromecast players do not support this (yet).

Hi @philippe44 

Thanks for this wonderful software, was wondering if the above meant Chromecast will display metadata if I change the `flc:0` in my config to `mp3:320`  

If not, would you know the trick being used by Starling Home Hub [to send metadata to Chromecasts?](https://9to5mac.com/2021/06/06/airplay-support-comes-to-google-nest-speakers-in-latest-update-for-starling-home-hub/)

Thanks

**Comment by philippe44** [comment]
Initially, CC devices did not support ICY protocol, but if they do now, then use of mp3 should let metadata work. 

There is at least one way I can think of to have metadata (or anything) on CC, and that's to write your own "receiver", the code that sits inside CC devices and interacts with your sender. There is a default receiver provided by Google that I'm using, but companies like Netflix for example have their own code where they can keep their identification secrets while still leveraging the Google ecosystem and rendering protocols. Such "receivers" are light protocol handlers, you don't have to rewrite all the media management. 

Now, I don't have an interest to write such receiver which also needs to be signed by Google before CC devices would accept them (that's the security measure to prevent malicious to run on CC).  

Now, wrt Starling Hub, I have no idea what they did, but they also could have embedded a whole AirPlay receiver within their own receiver, that's probably doable

**Comment by yinka** [comment]
Thanks for explaining this, I can confirm mp3:320 doesnt nothing for now.

Cheers

**Comment by yinka** [comment]
Hi @philippe44 

I've only just noticed that casting from my iPhone to Google Nesthub now shows the full metadata and artwork.

Does Chromecast now support the ICY protocol? 

Thanks

**Comment by philippe44** [comment]
No, but with the help of another developer, I found a solution to send live metadata. There is now a special application loaded in the CC
