### ISSUE TITLE
Remove offensive legacy language

### ISSUE THREAD

**Issue by cl0vrfi3ld** [philippe44/AirConnect#360]
I've been messing around with AirConnect, and in the logs I've been seeing messages like `UpdateThread: Sonos Play:1+ is now slave`. The term `slave` in regards to worker and follower  processes is generally considered offensive, and can be easily changed to the examples I gave above (`worker` or `follower`).

**Comment by STUkh** [comment]
@1MaddieX I don't think author mean something offensive because even 3-4 years ago it was common practice for such naming. Feel free to create PR with changes and do not forget to pay respect for other work, this is still actual.
