### ISSUE TITLE
Sync Apple Music playback with SONOS speakers

### ISSUE THREAD

**Issue by stefan1983** [philippe44/AirConnect#361]
Hello everyone,

I am trying to sync the music playback on my MBP with the sound output on my Sonos Play:5 (Series 1) boxes, without any luck until now. Does any one of you have an idea how to get the music to sync on macOS (Apple Music) and SONOS speakers via AirPlay?

<img width="428" alt="image" src="https://user-images.githubusercontent.com/8542806/127934623-da97b79a-125d-4534-b049-676d8c28b862.png">

I am wondering, because SONOS themselves can get the playback in total sync through multiple of their speakers without any issues (no matter if its trough WIFI / LAN).

Thanks for any idea
Stefan

**Comment by stefan1983** [comment]
By the way: The playback is in total sync when playing music through both SONOS speakers (via the SONOS system itself).

**Comment by philippe44** [comment]
You cannot synchronize with AirConnect

**Comment by stefan1983** [comment]
To bad :/ 

Would be awesome
