### ISSUE TITLE
Chromecast Audios ghosted

### ISSUE THREAD

**Issue by diadeluz** [philippe44/AirConnect#362]
Hi,

Thanks for the awesome work. I can now air play off the cuff from my iPad to any chromecast in the house and that is priceless.

The only issue I’m facing is that after running aircast-win, the five Chromecast Audios (CCA) on my LAN cease to be discoverable by any casting app launched from any machine on the LAN. It takes rebooting the APs between the CCAs and the main router to restore the discoverability of the CCAs. 

That does not happen with the regular Chromecasts.

Would you have any idea why the CCAs misbehave? :)

Best,

D.

**Comment by philippe44** [comment]
I have a few CCA and don't see that. Do they disappear while playing or after? My iIOS-Google Home and my Windows-Chrome still see my CCA while playing. I can stop/change volume

**Comment by stevenswall** [comment]
Similar issue, all devices work, though casting to any Chromecast Audio devices does not, whether using digital or analogue output from them.

Tried running from Windows as the administrator as well and the same thing happens: Casting to groups or individual Chromecast devices work. (Google Home Mini, Google Nest Hub, Nest Hub v2, Google Home Max)

All devices are on the same Ruckus R720 access point, and still show under Android devices, but not on an iPhone 12.

I should be able to test just about any device, let me know if there is a log file that helps and how to export it. Thanks for making this!

**Comment by philippe44** [comment]
If you stop AirCast, do they become discoverable again?

**Comment by diadeluz** [comment]
Hi, sorry about the tardiness of my reply.

Here is my test case on a LAN with 6 CCA, 1 CC, 6 GH mini (+ 1 main router and 3 wired APs which provide wifi connectivity). I run this test on a Windows 10 PC

Note: I use this scancc node.js snippet to list what CCs and GHs the PC can see:
var scanner = require('multicast-scanner');
scanner({ full_scan: true }, (err, devices) => {
  if(err) return console.log(err.message);
  devices.forEach(device => {
    console.log(device);
  });
});

1 - I run scancc which shows all of the above (so does the Chrome scan menu)
2 - I run .\aircast-win.exe which prints AddCastDevice lines for all of the above.
3 - I run scancc, which fails to show the CCAs. Chrome no longer shows the CCAs as possible renderers.
4 - I terminate the aircast-win.exe process
5 - I run scancc, which again fails to discover any of the CCAs. Same for Chrome.
6 - I reboot the three APs and when I run scancc, the CCAs show up again both with scancc and in chrome’s cast menu.

Since the CCAs pose no problem for your configuration, I gather mine’s at fault. And since the APs’ reboot make the CCAs discoverable again, the culprit could be some AP setting…

**Comment by diadeluz** [comment]
OK, thanks. Will follow that lead and keep you posted.

**Comment by diadeluz** [comment]
Hi, 

I found an unmanaged switch with igmp snooping capabilities that was on my LAN a,s replaced it with a dumber one. 

Still no game, though: my CCAs keep vanishing when I run airconnect. 

The main router has its igmp snooping option ticked off. The 3 APs that provide wifi access do not offer such an option in their config pages. Which could mean any one of them could potentially wreak havoc if they have igmp snooping enabled by default.

I’ll check their feature list, run some quick tests, and get back to you to close this issue should my investigation prove fruitful.

**Comment by philippe44** [comment]
Any update/success?

**Comment by diadeluz** [comment]
Sorry for my tardiness. I have not been able to determine whether any of my APs were at fault as the tech specs do not mention igmp snooping and I just can’t make the time to set up traffic analysis tools to get to the bottom of this. 

I would say the chances that rogue igmp snooping is the culprit are very high but I have no hard rock evidence. So I guess you can close this issue since it seems no one else among your users encountered it.

Unfortunately for me this means I have to stop using aircast with my LAN as it is.

Thanks again for all the good work.
