### ISSUE TITLE
No audio on AudioCast when using airupnp

### ISSUE THREAD

**Issue by cooperaj** [philippe44/AirConnect#363]
I'm trying to get this to work with a https://audiocast.io/ device. It claims to support DLNA and it does work with Spotify Connect. I've currently got Home Assistant talking to it via LinkPlay (whatever protocol that is) but AirConnect doesn't output audio.

It looks to connect just fine, all the chatter in the logs looks ok etc. I've scoured the closed issues for any hints and have tried a number of things but nothings worked. One interesting thing it does it play the previous stream instead of the new AirPlay provided one i.e. if I'm listening via Spotify Connect, stop that, and switch to AirPlay, the Spotify Stream starts playing again. 

sdebug logs here https://gist.github.com/cooperaj/766e5fa2c17e4bfa6fcc95ae973a5d41

**Comment by cooperaj** [comment]
Config file:
```<?xml version="1.0"?>
<airupnp>
<common>
<protocolInfo>
<pcm>http-get:*:audio/L16;rate=44100;channels=2:DLNA.ORG_PN=LPCM;DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</pcm>
<wav>http-get:*:audio/wav:DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</wav>
<flac>http-get:*:audio/flac:DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</flac>
<mp3>http-get:*:audio/mp3:DLNA.ORG_PN=MP3;DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=0d500000000000000000000000000000</mp3>
</protocolInfo>
<enabled>1</enabled>
<max_volume>100</max_volume>
<http_length>-3</http_length>
<upnp_max>1</upnp_max>
<codec>mp3:320</codec>
<metadata>0</metadata>
<flush>1</flush>
<artwork></artwork>
<latency>1000:2000</latency>
<drift>0</drift>
</common>
<main_log>info</main_log>
<upnp_log>info</upnp_log>
<util_log>warn</util_log>
<raop_log>info</raop_log>
<log_limit>-1</log_limit>
<max_players>32</max_players>
<binding>?</binding>
<ports>0:0</ports>
<device>
<udn>uuid:FF310001-58D1-8419-EDC1-B6A8FF310001</udn>
<name>Study Speakers</name>
<mac>bb:bb:6c:38:41:ef</mac>
<enabled>1</enabled>
</device>
<device>
<udn>uuid:9eb67653-4e6d-46b8-abb7-7988642a424b</udn>
<name>[TV] TV+</name>
<mac>bb:bb:e5:82:4c:08</mac>
<enabled>0</enabled>
</device>
</airupnp>
```

**Comment by philippe44** [comment]
Can you try with no config file and post a log?

**Comment by cooperaj** [comment]
Mmm. Well this is embarrassing. Running without a config file (which I definitely did first and it also didn't work) is now working. I've got no idea what the difference might be between then and now but 🤷

Thanks :)
