### ISSUE TITLE
Small problems with Spotify on Mac

### ISSUE THREAD

**Issue by sebastian-ruiz** [philippe44/AirConnect#365]
I have airconnect running on a ubuntu machine. I have a google mini as my chromecast device. On my Mac I connect the system sound to the airplay device.

When playing Spotify, when pressing pause there is a small delay and then it pauses. Then after a few seconds the Google mini speaker plays again for a fraction of a second before being silent again.

This doesn't seem to happen when I play youtube in Firefox. In this case when I press pause, the sound stops immediately.

Thanks for the project and your help! :)

**Comment by philippe44** [comment]
Try 0.2.51.0 for the "blurp". The delay is intrinsic to the way Spotify/iOS manages pause.

**Comment by sebastian-ruiz** [comment]
Do you mean that it is fixed in 0.2.51.0? I'm using the latest version, so it should be fixed in that one as well then, shouldn't it?

**Comment by sebastian-ruiz** [comment]
I can't find commit 0.2.51.0 on the master branch. Could you please point me in the right direction? :)

**Comment by philippe44** [comment]
The binaries are here https://github.com/philippe44/AirConnect/tree/master/bin
