### ISSUE TITLE
How rescan airplay devices without restarting LMS?

### ISSUE THREAD

**Issue by fmalfatto** [philippe44/AirConnect#366]
I noticed that I switch off an old Sony speaker, LMS loses it until the server is restarted, also if the device is powered on again and reached on the network. Is there a way to rescan devices? I have LMS under piCorePlayer and your plugin works very well.
TY in advance

**Comment by philippe44** [comment]
Is this an LMS question or an AirConnect question?

**Comment by fmalfatto** [comment]
Sorry, wrong chat. I have Raop bridge under LMS. Feel free to delete this post, I'll rewrite it in the right site.
