### ISSUE TITLE
Access only for specific MAC addresses

### ISSUE THREAD

**Issue by MobiusOne91** [philippe44/AirConnect#37]
Hi,

In my opinion AirConnect is the only good working solution for AirPlay on Sonos. But I'm having one problem with AirConnect. When we are having guests in our home and they are connected to our WLAN, they are having automatically access to our Sonos speakers with their smartphones and (audio)apps. Would it be possible to add inside the config.xml a value to only grand access to specific MAC addresses? It wouldn't be a problem when guests could see our Sonos speakers, but I don't want them to be able to play something on them.

Thanks in advance.

**Comment by philippe44** [comment]
Thank you

Re MAC address, for some complicated reasons I don't have a reliable option to get MAC from IP address in my libraries when using static links (used for AirConnect), so I can't do that
I understand your concern but then you should do what I do, have a guest SSID and only let your guests at home see that network to avoid having rogue devices on inner network (I even do that for my daughter as her computer becomes regularly rogue ...)

**Comment by MobiusOne91** [comment]
No worries.

At the moment we are having a "difficult" network setup, because we are using a 2 mbit DSL and an up to 50 mbit (mostly 14) LTE connection. Both networks are connected with a switch and using the same subnet. My raspberry is the DHCP server on my subnet. I'm quite happy that I could setup that DHCP server with different gateway rules, like the Sonos speakers are using the DSL connection for streaming and I still can connect with them. Guest devices are also using the DSL connection as gateway.

Our Telekom router has a guest network function, so I can separate guests from our LAN. For proper setup of the DHCP server I needed to deactivate the integrated Telekom DHCP server. So when I activate the separation function, guest devices cannot get DHCP announcements, because all network traffic is blocked between those two "networks".

I only wanted to ask, if this is possible, but when someone us doing shit with the Sonos speakers, I will ban his MAC address inside the router ;)
