### ISSUE TITLE
Alexa cast extension?

### ISSUE THREAD

**Issue by pascalbremmer** [philippe44/AirConnect#370]
Hi there! Are there any plans to extend this great app to Alexa cast? O do you know any comparable service making this work already? I'd like to airplay on my Echos... Thanks for your answer and keep up the good work!

**Comment by philippe44** [comment]
You can't "push" audio to an Echo unless you have a skill requiring playback to start ... so too contorted

**Comment by pascalbremmer** [comment]
Ah I see. Sad thing but thanks for your reply! Have a nice weekend.
