### ISSUE TITLE
Issues playing on Huawei Sound X and Huawei Sound

### ISSUE THREAD

**Issue by NoedelVreter** [philippe44/AirConnect#377]
I'm having problems getting this to work with my Huawei Sound X and Huawei Sound. 
I'm using macOS Monterey on a M1 MacBook Air trying to play music from Apple Music. Unfortunately no sound is coming out from the speakers. Starting playback in Apple Music stops the first time I press play and then when I press play again the music seems to be playing in Apple Music but still no sound coming out of the speakers. After I exit the program suddenly a few seconds of sound comes from the speaker. Volume control does seem to work correctly though.

Attached is a log file with only "-c mp3" as flag. I have also tried my speakers with your Logitech Media Server plugin and that seems to work fine

[log.txt](https://github.com/philippe44/AirConnect/files/7447632/log.txt)

**Comment by philippe44** [comment]
The device does not like the HTTP answer. It might be again one of these numerous faulty stacks that want a content-length on HTTP/1.0. You can try to use "chunked" encoding, see README

**Comment by NoedelVreter** [comment]
I tried with chunked-encoding. But no luck.

Attached is a log with chucked encoding.

[log.txt](https://github.com/philippe44/AirConnect/files/7448841/log.txt)

**Comment by philippe44** [comment]
Can you confirm my UPnP plugin for LMS works?

**Comment by NoedelVreter** [comment]
Yes, I can play/pause music just fine. Not sure if it helps but here are the log and config from the LMS Plugin.

[upnpbridge.log](https://github.com/philippe44/AirConnect/files/7453772/upnpbridge.log)
[upnpbridge.xml.txt](https://github.com/philippe44/AirConnect/files/7453778/upnpbridge.xml.txt)

**Comment by philippe44** [comment]
It's probably mainly on me this time, an incorrect response to HTTP2 upgrade and/or a wrong mimetype. Can you check version 0.2.51.2 with normal and chunked-encoding?

**Comment by NoedelVreter** [comment]
I'm not home till next week. I'll report back as soon as I can, thanks for helping so far.

**Comment by NoedelVreter** [comment]
Hello again,

I tried with 0.2.51.2. Still no sound coming from the speakers.
Here is the log file:

[log.txt](https://github.com/philippe44/AirConnect/files/7520785/log.txt)

**Comment by philippe44** [comment]
Have you tried then falc and wav/pcm encoding with that version?

**Comment by philippe44** [comment]
Closed for inactivity

**Comment by woann** [comment]
> 我在将其与我的华为 Sound X 和华为 Sound 配合使用时遇到问题。 我在 M1 MacBook Air 上使用 macOS Monterey，尝试播放 Apple Music 中的音乐。不幸的是，扬声器没有发出任何声音。当我第一次按下播放键时，在 Apple Music 中开始播放就会停止，然后当我再次按下播放键时，音乐似乎正在 Apple Music 中播放，但扬声器中仍然没有声音。退出程序后，扬声器突然发出几秒钟的声音。不过，音量控制似乎工作正常。
> 
> 附件是一个仅包含“-c mp3”作为标志的日志文件。我还用您的 Logitech Media Server 插件尝试了我的扬声器，看起来效果很好
> 
> [日志.txt](https://github.com/philippe44/AirConnect/files/7447632/log.txt)

are you ok ?
