### ISSUE TITLE
Samsung Wam MultiRoom 

### ISSUE THREAD

**Issue by Fewk1** [philippe44/AirConnect#378]
Successfully installed AirConnect (MacOS UPnP) and some UPnP devices such as my Samsung TV show up. However I cannot add Samsung wireless MultiRoom speakers. Any hints?
/Fredrik

**Comment by philippe44** [comment]
Are they even UPnP or a Samsung invention? What does log says?

**Comment by Fewk1** [comment]
I believe they use UPnP protocol. I used the app UPnP mate to locate them on the network and got this information from one of the speakers. I can in no way say that I am an expert in this field and cannot decipher all of this, but I have a strong feeling that they use a UPnP protocol of some sort. 



Best regards 
Fredrik

**Comment by philippe44** [comment]
Try to use an UPnP manager like BubbleUPnP or even a tool like "DeviceSpy" to verify if it's actually UPnP

**Comment by philippe44** [comment]
Closed for inactivity
