### ISSUE TITLE
Airconnect stalls?

### ISSUE THREAD

**Issue by markbreneman** [philippe44/AirConnect#379]
Hello,

I've been tried installing AirConnect on MacOS(Monterey & Big Sur) and on an RPi using the corresponding binaries, but everytime I try to execute it seems to stall/hang on binding to the IP Address, and nothing happens . 

<img width="620" alt="Screen Shot 2021-11-08 at 9 43 00 AM" src="https://user-images.githubusercontent.com/1054373/140711695-1d7eea07-3c30-466e-92c3-71419333bc56.png">

I'm assuming this may have something to do with my Google Mesh Wifi setup.  Has anyone else run into this or have any ideas to try?

**Comment by philippe44** [comment]
You need to look for multicast enablement and especially IGMP snooping
