### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by Jens2022** [philippe44/AirConnect#388]
Dear Philipp,

please take my aplogies for the newbie question, which files should I install for a Hoobs 4 runing on raspberry pi 4? 

Thanks a lot for a hint. 

Best regards,

Jens

**Comment by philippe44** [comment]
I don't know, it can be either the armv6hf or aarch64

**Comment by Jens2022** [comment]
Hi Philippe, 

thanks a lot for your help. I could install aarch64. When I try to execute the file I get a „permission denied“ request: 

***@***.***:~ $ wget https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-aarch64
--2022-01-09 11:25:49--  https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-aarch64
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 521256 (509K) [application/octet-stream]
Saving to: ‘airupnp-aarch64’

airupnp-aarch64                     100%[==================================================================>] 509.04K  --.-KB/s    in 0.09s   

2022-01-09 11:25:52 (5.82 MB/s) - ‘airupnp-aarch64’ saved [521256/521256]


Do you have a hint how I can fix this? 

Thanks a lot. 

Best Regards

Jens

**Comment by philippe44** [comment]
Have you made it executable (chmox +x). Did you try armhf?
