### ISSUE TITLE
Yamaha MusicCast?

### ISSUE THREAD

**Issue by artusmode** [philippe44/AirConnect#389]
I was looking at these Yamaha devices (sounds bars etc) and their support page seems to indicate they support UPnP and a wide list of formats. Does anyone have one of these and does it work with Airconnect?  https://usa.yamaha.com/products/contents/audio_visual/musiccast/musiccast-faqs.html

Does MusicCast support NAS drives?
Yes. All MusicCast devices support playback from network-connected computers and NAS devices that use the UPnP (Universal Plug and Play) networking protocol.

**Comment by philippe44** [comment]
I have these - they do offer AirPlay and UPnP, AFAIR. As they offer natively AirPlay, why would you want AirConnect?
