### ISSUE TITLE
There's something errors

### ISSUE THREAD

**Issue by xxz3312** [philippe44/AirConnect#390]
I'm using the arm-staitc ver. on my ARMv7 device running openwrt system,the Kernel Version is 5.4.162.
It noticed
_Error in `./airupnp-arm-static': free(): invalid pointer: 0xaff00a38 ***_

**Comment by philippe44** [comment]
I need a bit more information - like a log

**Comment by xxz3312** [comment]
Thanks for your replay, I have fixed this errors.
