### ISSUE TITLE
Cast across vlan causes buffer overrun in cmd readout.

### ISSUE THREAD

**Issue by ernestmusser88** [philippe44/AirConnect#394]
### Discussed in https://github.com/philippe44/AirConnect/discussions/393

<div type='discussions-op-text'>

<sup>Originally posted by **ernestmusser88** January 10, 2022</sup>
Hello, thank you for making this program. it is really helpful. I am having a strange issue though. I have several Google Home speakers and some Raspberry pi projects on an IOT vlan with my phones and computers on a seperate home network. AirConnect is running on the IOT network and I am able to see my devices and begin casting to them. I get volume and transport control on the Google Home speaker, but when I hit play the command line begins displaying bufferoverruns and I get no audio. I have put specific traffic rules in place for known ports and ive tried forwarding all ports between the network. The system works without issues if the phone is connected to the IOT network. Could you provide any advice for further troubleshooting? Thank you.</div>

**Comment by 6b6561** [comment]
Take a look at https://github.com/philippe44/AirConnect/issues/312 and see if it can give you any hints on what to try.

**Comment by mag1024** [comment]
I had a similar problem (control works -- sound doesn't), and it took me a while to figure it out.
The fact that control works indicates that the airconnect <-> chromecast communication is not the issue. What I was overlooking is that airplay itself is a pull, not a push protocol, so the airconnect host needs to be able to create connections to the airplay source. In my case, the latter was on a different subnet.
It's quite unfortunate that there seems to be no way to airplay _from_ a trusted network to an untrusted one without creating large firewall holes.
