### ISSUE TITLE
Samsung Soundbar HW-Q900T

### ISSUE THREAD

**Issue by mazmar** [philippe44/AirConnect#396]
Hi

I have samsung soundbar Q900T it shows in spotify as network device, but it doesn't show in apple music app and it is not discovered via airconnect.

Any ideas how to make it work? Is it not UpNP nor chromecast?

**Comment by philippe44** [comment]
It does not seems to be compatible with upnp, chromecast or airplay, so no luck here

**Comment by 01046** [comment]
it's spotifyconnect,just for spotify
