### ISSUE TITLE
unable to create recv socket

### ISSUE THREAD

**Issue by ThinkDumbIndustries** [philippe44/AirConnect#397]
I'm on Ubuntu 18.04.6 LTS
I downloaded the prebuilt binary, marked it as executable. When I execute it, I get the following
```
$ ./aircast-x86-64 
[21:07:38.968960] main:974 Starting aircast version: v0.2.51.2 (Nov  1 2021 @ 23:31:36)
[21:07:38.969058] main:982 no config file, using defaults
[21:07:38.969263] Start:732 Binding to 192.168.0.5
recv bind(): Address already in use
unable to create recv socket
[21:07:38.970850] main:1015 Cannot start
```

**Comment by philippe44** [comment]
Likely you have an mDNS responder that does not accept to share the port with others. Old Avahi did that - see README

**Comment by ThinkDumbIndustries** [comment]
Yep, indeed.
I set `disallow-other-stacks=no` in `/etc/avahi/avahi-daemon.conf` as Misc tips, it starts up fine.
This is my first time using AirConnect! I'm running this on a server in a remote location at the moment, so I can't test that everything works unfortunately.
Thanks for you quick reply!
