### ISSUE TITLE
-z parameter not working as expected

### ISSUE THREAD

**Issue by danielgolden** [philippe44/AirConnect#40]
First, this is awesome. Thank you for maintaining this project, it's fills such a sweet spot in my life until AirPlay 2 is ready. Kudos!

Is there an example of what the command with non-interacive "-z" option enabled should look like? I've been using: `./airupnp-osx-multi -z -l 500:500`. The command runs, but I don't think it's running in the background because I still see a long list of logs as I play to my Sonos through iTunes on my MBP. Also, when I close the tab in iTerm2, the process quits. I can no longer play audio through the Sonos on my MBP.

**Comment by philippe44** [comment]
Thanks - The -z parameter does not apply to MacOS. You must use -Z and then daemonize the application "airupnp-osx-multi -Z -l 500:500&"
