### ISSUE TITLE
airupnp hangs on osx after running for many hours

### ISSUE THREAD

**Issue by dickinson-lab** [philippe44/AirConnect#401]
First of all thanks for making a very useful program, it works great.  However, I've noticed that it often stops working after it's been connected to my sonos speaker for more than a day.  Running the lastest version of airupnp on MacOS 11.6.2. 
Key observations: 
- When frozen, no sound is heard when audio is sent to the airplay device.  
- If the airplay device is de-selected, it can't be re-selected from the sound preferences menu (top right corner of the osx screen) even though it still appears as an available device. The spinning gear appears and persists until it times out and gives a "can't connect" error. 
- If airupnp was started from a launchd process, there is no way to stop or refresh it; I have to just kill it by using force quit in the activity monitor. 
- If airupnp was started from terminal, it does not respond to a command to exit (or ^C); it gets to the `flush renderers ...` output and then stays stuck there until the process is terminated by closing the terminal window.

Let me know if I can provide any log files that might help diagnose the issue.  Thanks again!

**Comment by philippe44** [comment]
I would need to have a log when and iOS device tries to connect and fails. unfortunately, I cannot test much on OSX as all I have is an old VM. Is there any chance you could try AirConnect on a different type of CPU/OS to help separating variables?

**Comment by dickinson-lab** [comment]
Sorry for the slow response, I had to wait for it to hang again.  Here are the log messages I saw: 
```
error	18:09:58.248754-0600	AirPlayXPCHelper	httpconnection_asyncConnectionConnected:1267: got error -6722/0xFFFFE5BE kTimeoutErr
error	18:09:58.248780-0600	AirPlayXPCHelper	### [0x3959] httpconnection_asyncConnectionConnected: failed with error -6722/0xFFFFE5BE kTimeoutErr.
error	18:09:58.248833-0600	AirPlayXPCHelper	OSStatus stream_eventReceived(FigTransportStreamRef, APTransportConnectionEvent, CFTypeRef, APTransportStreamConnectionStateRef), connection failed
error	18:09:58.248922-0600	AirPlayXPCHelper	### [0x1392] stream 0xFD18 disconnected with reason -6722/0xFFFFE5BE kTimeoutErr.
error	18:09:58.249263-0600	AirPlayXPCHelper	stream_WaitUntilConnected:899: got error -6722/0xFFFFE5BE kTimeoutErr
error	18:09:58.249299-0600	AirPlayXPCHelper	sdpsession_ensureTransportControlStreamResumedSync:1005: got error -6722/0xFFFFE5BE kTimeoutErr
error	18:09:58.249358-0600	AirPlayXPCHelper	sdpsession_ensureStartedInternal:611: got error -6722/0xFFFFE5BE kTimeoutErr
error	18:09:58.249403-0600	AirPlayXPCHelper	endpoint_activateInternal:3011: got error -6722/0xFFFFE5BE kTimeoutErr
error	18:09:58.249425-0600	AirPlayXPCHelper	[0x554C] Endpoint activation (seed 1) failed with error -6722/0xFFFFE5BE kTimeoutErr.
```

To be clear, there is not an iOS device in play here - rather, it's the Mac itself that I'm using to stream audio. 

I don't have access to a PC with an appropriate setup, unfortunately.  I wanted to buy a Raspberry Pi but they are sold out everywhere - chip shortage?  I will keep trying and let you know if I can get results on a different system.

**Comment by philippe44** [comment]
Is this the right Sonos player address 128.83.136.86:49313 ? It's a public routable address, so it's very surprising

**Comment by dickinson-lab** [comment]
No, that's the address for the computer itself.  The player is at 128.83.136.46.

**Comment by philippe44** [comment]
I understand, but why using such addresses?

**Comment by dickinson-lab** [comment]
I have no idea - it’s an office network and I don’t have any control over the router / network settings.

On Mar 4, 2022, at 12:58 PM, philippe44 ***@***.***> wrote:

﻿

I understand, but why using such addresses?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphilippe44%2FAirConnect%2Fissues%2F401%23issuecomment-1059432581&data=04%7C01%7C%7C2016846ca39b4978b41c08d9fe10e626%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637820170801047590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b%2B1k7dUTiQWZYh82ylAw36etYOTjByaNNWWCiSDErSk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADLJ23SD5LX57V7BNSOZNZ3U6JMLJANCNFSM5OZAJXOA&data=04%7C01%7C%7C2016846ca39b4978b41c08d9fe10e626%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637820170801047590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZIhk4nTZd9UCoDQT9a5MC6cyDEwq7xKfe4R7DjDFPWQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C2016846ca39b4978b41c08d9fe10e626%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637820170801047590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D43MTjINlBjCB3tjzXSY2cFbXaR%2FBZpKdRLN1vBxrcg%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C2016846ca39b4978b41c08d9fe10e626%7C31d7e2a5bdd8414e9e97bea998ebdfe1%7C0%7C0%7C637820170801047590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qd%2FHVC7txSGncplCui5t5P4%2B6nbWcyJLRnDjKydMA8k%3D&reserved=0>.

**Comment by philippe44** [comment]
well, unless I'm mistaken, it is very strange and unsafe setup. I have no idea how then airupnp can be broadcasted more widely and the consequences this might have.

**Comment by dickinson-lab** [comment]
Ok, on your advice I've re-configured my network setup to use private addresses.  I am having a different issue now, which I will post separately.
