### ISSUE TITLE
MaxOS universal (or arm64) builds for AirConnect?

### ISSUE THREAD

**Issue by lprimak** [philippe44/AirConnect#403]
Hi!

First of all, thank you for a wonderful program. I've been using it for many years.
I just upgraded my mac server to new arm-based version, and there is no universal build or aarch64 airupnp for it.
Thank you!

**Comment by nmcc1212** [comment]
+1, the aarch64 builds don't work

**Comment by philippe44** [comment]
I don't understand that comment - the aarch64 builds are for Linux

**Comment by nmcc1212** [comment]
ohhh, i tried them on macos 🤦‍♂️
any update on apple silicon support

**Comment by philippe44** [comment]
I have no plan for arm-macOS architecture. I have a unified cross-build system and I can't add such environment, it's too complicated

**Comment by lprimak** [comment]
Does that mean you don't use Xcode command tools to build on MacOS? Or am I missing something?

**Comment by philippe44** [comment]
No I don't directly. My macOS build is on Linux

**Comment by lprimak** [comment]
Oh I see. Disappointing but I get it

**Comment by lprimak** [comment]
And the Linux cross compiler doesn’t support universal builds I assume?

**Comment by philippe44** [comment]
No it's too old

**Comment by lprimak** [comment]
Update: Intel Airupnp on Arm Macs does work well using Rosetta 2

**Comment by MacsInSpace** [comment]
https://github.com/MacsInSpace/AirCastAirUpnpMacOS.pkg works on my new M1 (with Rosetta 2)
