### ISSUE TITLE
lost frequently

### ISSUE THREAD

**Issue by jackghyu** [philippe44/AirConnect#404]
hi, thank you for a great program!

I have just intalled a airconnect docker container (1activegeek). when I first run it, I can find my sonos play1 in airplay. but soom, the player dispe
[0315.pdf](https://github.com/philippe44/AirConnect/files/8262508/0315.pdf)
ared. when i restart the container, sometimes i can find it, but not always.

the operation system is DSM 7.01, router is Huaway WS5200. i attached the log. would you please take a look. thanks a lot!

**Comment by 6b6561** [comment]
Don't open the .pdf file, I ran a scan on it and it reported back as "Worm:Win32/Skeeyah" with status severe!!!
