### ISSUE TITLE
Macbook can't connect to Airplay

### ISSUE THREAD

**Issue by Dulox24** [philippe44/AirConnect#405]
Hi,

First of all I am very happy with AirConnect, thank you for this nice project.
Today I wanted to test if I could play the sound of my macbook as well with Airplay.
It does find the Sonos Group, but it doesn't play any sound. 
From my phone everything works fine. 
Anyone an idea ?

AirConnect is installed on Raspberry Pi
The group of speakers consists of:
1 Sonos Playbar
1 Sonos Sub
2 Sonos Play:1

Grt Joël

<img width="657" alt="Schermafbeelding 2022-03-25 om 21 46 22" src="https://user-images.githubusercontent.com/99218884/160198613-f17bd2cb-8527-4cc1-b099-b8decb847e59.png">

In Dutch it says: No connection possible with "Woonkamer Sonos" (Which is the group of speakers I added)

**Comment by philippe44** [comment]
Late answer but I'd need to see a log
