### ISSUE TITLE
Constant 100% CPU consumption

### ISSUE THREAD

**Issue by scaarup** [philippe44/AirConnect#409]
Maybe this is just by design, but the aircast process is constantly at around 100% CPU

![image](https://user-images.githubusercontent.com/8055470/164391170-bb478964-383c-4147-95ab-03c26d198a5a.png)

I am on a virtualbox'ed Ubuntu 20.04.4 LTS (x86_64 arch) - running aircast-x86-64.

**Comment by scaarup** [comment]
strace'ing the process, seems to be a loop of this:
![image](https://user-images.githubusercontent.com/8055470/164391694-a76ad385-efcb-4840-8a67-60462931e0c8.png)

Nothing is playing.

**Comment by philippe44** [comment]
How did you launch it?

**Comment by scaarup** [comment]
> How did you launch it?

Super basic, from roots crontab like this:
`* * * * * pidof aircast-x86-64 || /root/aircast-x86-64 -f /root/aircast.log`
![image](https://user-images.githubusercontent.com/8055470/164404086-061fbe15-b3b1-40e4-97d0-97e09c541260.png)

**Comment by philippe44** [comment]
Thats the issue. The README explains this: use systemd launch config or if you want to make that manually and background it, you must disable stdin access otherwise cpu is used at 100%.

**Comment by scaarup** [comment]
> Thats the issue. The README explains this: use systemd launch config or if you want to make that manually and background it, you must disable stdin access otherwise cpu is used at 100%.

Oops, very sorry. Didn't catch that. Thanks for the assistance though.
