### ISSUE TITLE
Synology Router package

### ISSUE THREAD

**Issue by bandesz** [philippe44/AirConnect#41]
Thanks for the great project!

I wanted to use it on my Synology Router, so I created a package for it: https://github.com/bandesz/AirConnect-SynologyRouter.

If you would like me to add anything (additional notes, licensing, etc.) please let me know.

**Comment by marco79cgn** [comment]
First of all, thank you.

I'm using a Synology DiskStation 115j and the arm version of AirConnect runs natively because there is an ARM (v7) CPU. But as far as I know, there are lots of different DiskStations available with different CPUs, so I guess your package will only run on ARM DiskStations? Correct me if I'm wrong.

A One-for-All solution probably needs a docker container (and a DiskStation capable of running Docker).

**Comment by bandesz** [comment]
@marco79cgn You're right, I only included the ARM binary in the package. What I added are simply the install, start/stop scripts and metadata. This is the supported architecture list based on what Plex supports in their ARMv7 package: "ipq806x armada370 armadaxp armada375 armada38x alpine alpine4k monaco comcerto2k" (e.g. the 115j is built on armada370).

The Synology dev docs suggest you should build separate packages for different architectures, so if people with non-ARM DiskStations will be interested I can extend the current solution with their help.

**Comment by bandesz** [comment]
I extended the build script so now we have packages for ARM, x86 and x86_64 architectures. I can't test it on a NAS server, but it's a start :)

**Comment by bandesz** [comment]
The current packages can be found here: https://github.com/bandesz/AirConnect-Synology/releases

**Comment by marco79cgn** [comment]
Cool, that was fast. :)
I just thought it was a good idea to clarify in the Readme that it only runs on arm architecture so that people are not confused. But your solution is even better.

**Comment by hjtech** [comment]
I have a DiskStation with an Intel CPU, will test the new packages and report back.

**Comment by philippe44** [comment]
Thanks for the work - it's now referenced in the readme, so I'll close this issue
