### ISSUE TITLE
airupnp-arm can’t running when open mitv 

### ISSUE THREAD

**Issue by 107064547** [philippe44/AirConnect#412]
airupnp-arm can’t running when open mitv,why?

**Comment by philippe44** [comment]
Sorry I don't understand what you want

**Comment by 107064547** [comment]
> 

when i open my mitv,the lunch will be stopped 
![Uploading 8A9D4EF3-253F-4C9A-B345-02633F513C2C.png…]()

**Comment by philippe44** [comment]
I still don't understand. What is mitv? Is this mythTV? What OS are you running, what CPU?

**Comment by 107064547** [comment]
> I still don't understand. What is mitv? Is this mythTV? What OS are you running, what CPU?

closed dlna can run,armbian,cpu is s805
