### ISSUE TITLE
Sync multiple speaker ?

### ISSUE THREAD

**Issue by JamesDAdams** [philippe44/AirConnect#413]
Hi,

first really thanks for your soft 👍 

It's possibly for AirConnect to create a new virtuel speaker on airplay (ex : AllSpeaker) and when we send the music to it, he send the music to all speakers ?

Thanks.

**Comment by JamesDAdams** [comment]
I specify that my s2 speakers I can select several but not the speakers created by AirConnect

![image](https://user-images.githubusercontent.com/20860324/167299020-de00466b-7a8a-4018-884b-e4b931534117.png)

**Comment by nehayward** [comment]
This is a limitation of Airplay 1 I believe.

**Comment by philippe44** [comment]
You can do multiple speakers in sync with AirPlay 1 but iOS devices do not let you use it. iTunes does

**Comment by nehayward** [comment]
Thanks for the clarification, this is correct. Airplay 2 allows for multiple on iOS correct? Also I’d like to get involved in the project and would love to help out in anyway.

**Comment by JamesDAdams** [comment]
> You can do multiple speakers in sync with AirPlay 1 but iOS devices do not let you use it. iTunes does

Realy thanks it's work with Itunes !!! <3 

![image](https://user-images.githubusercontent.com/20860324/168996732-a9ae7c9e-b677-4553-b95c-d6b42df305b0.png)

**Comment by JamesDAdams** [comment]
But there is a small delay between the speakers S1 & S2 (about 1s) It is not very serious. But it would be really nice to have an option to specify a delay for each speaker

**Comment by philippe44** [comment]
Yes indeed but that's a different issue. That's these are 2 different UPnP speakers and then there is no sync possible, sync is not a part of UPnP capabilities. So although iTunes sends the audio to both with sync data, that sync cannot exist on the UPnP side of the bridge.

**Comment by JamesDAdams** [comment]
> Yes indeed but that's a different issue. That's these are 2 different UPnP speakers and then there is no sync possible, sync is not a part of UPnP capabilities. So although iTunes sends the audio to both with sync data, that sync cannot exist on the UPnP side of the bridge.

Ok, but on the side of the bridge, it's possible to create a fake delay no ?

**Comment by philippe44** [comment]
No, you have absolutely no control on timing of UPnP devices.

**Comment by JamesDAdams** [comment]
ok
