### ISSUE TITLE
Error after a couple minutes closes Airplay Connection.

### ISSUE THREAD

**Issue by snjyr123** [philippe44/AirConnect#415]
I am casting to a Google home and after about 5 minutes, this error pops up, "[20:21:21.558] rtsp_thread:350 RTSP close 1380". Any way I could fix this?

**Comment by ask438** [comment]
Same, I just installed it on my Mac mini server and keep having the same error (to sonos). It was working fine on my raspberry pi so will switch back to that until it’s resolved…

**Comment by philippe44** [comment]
It's not an error message, it just means the AirPlay controller is ending the session
