### ISSUE TITLE
Install on Raspberry Pi not possible

### ISSUE THREAD

**Issue by nivek88** [philippe44/AirConnect#421]
Hi

it looks like the arm files have gone. If I want to install AirConnect to my rPi using 

https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-arm

I get ```ERROR 404: Not Found.```

Is there another way to install AirConnect to a Pi?

**Comment by philippe44** [comment]
The master is WIP, please refer to branch v2

**Comment by nivek88** [comment]
Thank you!
