### ISSUE TITLE
Syntax error on execution 

### ISSUE THREAD

**Issue by nivek88** [philippe44/AirConnect#422]
I recently had to reset my Pi and this time I can't get AirConnect to work again. If I try to execute the bin file 

```./airupnp-arm```

I do get an error message. 

```./airupnp-arm: line 8: syntax error near unexpected token `newline'```
```./airupnp-arm: line 8: `<!DOCTYPE html>'```

Linux raspberrypi 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux

**Comment by pwt** [comment]
Your `./airupnp-arm` is not a binary executable. Looks like it's an HTML document -- i.e., you downloaded a web page instead of a binary.

Did you try to update the binary at some point prior to the reset?
