### ISSUE TITLE
No sound on Google nest hub

### ISSUE THREAD

**Issue by Crafter89** [philippe44/AirConnect#426]
I am trying to stream to a Google nest hub. The AirPlay connection is working and it shows the name of the Google speaker. However I don't get any audio out of the speaker. What can I do? I have tried setting the codec to mp3 but it doesn't work.

**Comment by philippe44** [comment]
Tell me a bit more about where airconnect runs and post a log

**Comment by Crafter89** [comment]
It runs on Ubuntu Server 22.04.1 LTS. There is a folder in my users home directory which contains aircast-x86_64 and the config.xml. I have set it up to start automatically with Linux. Here I have a log and the content of the config file:

`Okt 10 09:51:00 server systemd[1]: Started AirConnect bridge.
Okt 10 09:51:00 server aircast-x86_64[2526]: [09:51:00.778080] main:972 Starting aircast version: v0.3.00.0 (Oct  8 2>
Okt 10 09:51:00 server aircast-x86_64[2526]: [09:51:00.778294] Start:732 Binding to 192.168.0.193
Okt 10 09:51:00 server aircast-x86_64[2526]: [09:51:00.862834] AddCastDevice:669 [0x55fc47f6bb20]: adding renderer (R>
Okt 10 09:51:00 server aircast-x86_64[2526]: [09:51:00.863002] AddCastDevice:675 [0x55fc47f6bb20]: creating MAC 47f6b>
Okt 10 09:51:04 server aircast-x86_64[2526]: [09:51:04.603854] rtsp_thread:342 got RTSP connection 9
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.813092] handle_rtsp:390 [0x7f1dbc00bc00]: challenge Rltg6w7uba>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.821081] handle_rtsp:383 [0x7f1dbc00bc00]: received ANNOUNCE
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.824811] handle_rtsp:587 [0x7f1dbc00bc00]: responding:
Okt 10 09:51:13 server aircast-x86_64[2526]: RTSP/1.0 200 OK
Okt 10 09:51:13 server aircast-x86_64[2526]: Audio-Jack-Status: connected; type=analog
Okt 10 09:51:13 server aircast-x86_64[2526]: CSeq: 4
Okt 10 09:51:13 server aircast-x86_64[2526]: 
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.826071] handle_rtsp:383 [0x7f1dbc00bc00]: received SETUP
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.827718] hairtunes_init:406 [0x7f1db80168c0]: UDP port-0 49930
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.827745] hairtunes_init:406 [0x7f1db80168c0]: UDP port-1 33066
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.827760] hairtunes_init:406 [0x7f1db80168c0]: UDP port-2 37961
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.827780] hairtunes_init:424 [0x7f1db80168c0]: HTTP listening po>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.827914] handle_rtsp:587 [0x7f1dbc00bc00]: responding:
Okt 10 09:51:13 server aircast-x86_64[2526]: RTSP/1.0 200 OK
Okt 10 09:51:13 server aircast-x86_64[2526]: Transport: RTP/AVP/UDP;unicast;mode=record;control_port=33066;timing_por>
Okt 10 09:51:13 server aircast-x86_64[2526]: Session: DEADBEEF
Okt 10 09:51:13 server aircast-x86_64[2526]: Audio-Jack-Status: connected; type=analog
Okt 10 09:51:13 server aircast-x86_64[2526]: CSeq: 5
Okt 10 09:51:13 server aircast-x86_64[2526]: 
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.829465] handle_rtsp:383 [0x7f1dbc00bc00]: received RECORD
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.829491] hairtunes_record:531 [0x7f1db80168c0]: record 0 0
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.829501] raop_cb:188 [0x55fc47f6bb20]: Stream
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.829528] handle_rtsp:587 [0x7f1dbc00bc00]: responding:
Okt 10 09:51:13 server aircast-x86_64[2526]: RTSP/1.0 200 OK
Okt 10 09:51:13 server aircast-x86_64[2526]: Audio-Jack-Status: connected; type=analog
Okt 10 09:51:13 server aircast-x86_64[2526]: CSeq: 6
Okt 10 09:51:13 server aircast-x86_64[2526]: 
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.830818] handle_rtsp:383 [0x7f1dbc00bc00]: received SET_PARAMET>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.830848] handle_rtsp:550 [0x7f1dbc00bc00]: SET PARAMETER volume>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.830861] CastSetDeviceVolume:336 [0x55fc47f6bb20]: Queuing SET_>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.830869] raop_cb:239 [0x55fc47f6bb20]: Volume[0..1] 0.3333
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.830898] handle_rtsp:587 [0x7f1dbc00bc00]: responding:
Okt 10 09:51:13 server aircast-x86_64[2526]: RTSP/1.0 200 OK
Okt 10 09:51:13 server aircast-x86_64[2526]: Audio-Jack-Status: connected; type=analog
Okt 10 09:51:13 server aircast-x86_64[2526]: CSeq: 7
Okt 10 09:51:13 server aircast-x86_64[2526]: 
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.832189] rtp_thread_func:766 [0x7f1db80168c0]: 1st sync packet >
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.857183] flac_init:221 [0x7f1db80168c0]: Using FLAC-0 (0x7f1da8>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.857406] buffer_put_packet:650 [0x7f1db80168c0]: fill [level:1]>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.858627] handle_rtsp:383 [0x7f1dbc00bc00]: received FLUSH
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.858707] hairtunes_flush:497 [0x7f1db80168c0]: FLUSH ignored as>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.858730] hairtunes_flush:513 [0x7f1db80168c0]: flush 58674 3695>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.858811] handle_rtsp:587 [0x7f1dbc00bc00]: responding:
Okt 10 09:51:13 server aircast-x86_64[2526]: RTSP/1.0 200 OK
Okt 10 09:51:13 server aircast-x86_64[2526]: Audio-Jack-Status: connected; type=analog
Okt 10 09:51:13 server aircast-x86_64[2526]: CSeq: 8
Okt 10 09:51:13 server aircast-x86_64[2526]: 
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.939079] search_remote_cb:632 [0x7f1dbc00bc00]: found ActiveRem>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.949505] raop_cb:213 [0x55fc47f6bb20]: Play
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.974592] CastConnect:358 [0x55fc47f6bb20]: SSL connection opene>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.975117] CastLoad:175 [0x55fc47f6bb20]: Queuing LOAD
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.975198] CastSimple:212 [0x55fc47f6bb20]: Queuing PLAY
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.975223] CastSetDeviceVolume:336 [0x55fc47f6bb20]: Queuing SET_>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.980381] read_bytes:174 [s-0x7f1dbc009760]: SSL error code 6 (e>
Okt 10 09:51:13 server aircast-x86_64[2526]: [09:51:13.980425] CastSocketThread:702 [0x7f1dbc009600]: SSL connection >
Okt 10 09:51:15 server aircast-x86_64[2526]: [09:51:15.854920] handle_rtsp:383 [0x7f1dbc00bc00]: received SET_PARAMET>
Okt 10 09:51:15 server aircast-x86_64[2526]: [09:51:15.855101] handle_rtsp:587 [0x7f1dbc00bc00]: responding:
Okt 10 09:51:15 server aircast-x86_64[2526]: RTSP/1.0 200 OK`

`<?xml version="1.0"?>
<aircast>
<common>
<enabled>1</enabled>
<stop_receiver>0</stop_receiver>
<media_volume>0.5000</media_volume>
<latency></latency>
<drift>0</drift>
<codec>mp3</codec>
<metadata>1</metadata>
<flush>1</flush>
<artwork></artwork>
</common>
<main_log>info</main_log>
<cast_log>info</cast_log>
<util_log>warn</util_log>
<log_limit>-1</log_limit>
<max_players>32</max_players>
<ports>0:0</ports>
<binding>?</binding>
<device>
<udn>20d26d975fbc7ca2bfa9929169afca61</udn>
<name>Ronny&apos;s Zimmer</name>
<mac>cc:cc:0c:16:a8:6d</mac>
<enabled>1</enabled>
</device>
</aircast>`

**Comment by philippe44** [comment]
Is this still valid?
