### ISSUE TITLE
Which prebuild for FreeBSD?

### ISSUE THREAD

**Issue by DavidZweistein** [philippe44/AirConnect#431]
Hey,
I was just wondering, which prebuild, if any, is executable in freebsd? Trying to get it running in a truenas jail... also the osx-multi file from the example isn't there, or am i missing something?

Thx and cheers!

**Comment by philippe44** [comment]
I'm in a middle of a refactoring and toolchain update. The osx, freebsd and solaris version are missing. I'll try to bring them back but I"m not 100% sure. Meanwhile, you can look at branch 2.x

**Comment by philippe44** [comment]
FreeBSD is back

**Comment by DavidZweistein** [comment]
Perfect, works like a charm. Thanks so much!
