### ISSUE TITLE
GLIBC not found

### ISSUE THREAD

**Issue by donjuanmon** [philippe44/AirConnect#432]
Having an issue running the latest version of Aircast on a Raspberry Pi 4 running Buster

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"

```
pi@pi4:/opt/airconnect/bin $ ./aircast-linux-arm 
./aircast-linux-arm: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.29' not found (required by ./aircast-linux-arm)
./aircast-linux-arm: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by ./aircast-linux-arm)
./aircast-linux-arm: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by ./aircast-linux-arm
```

Have not tried updating to Bullseye.. is that a requirement now?

**Comment by philippe44** [comment]
You can use the -static version and it should do

**Comment by donjuanmon** [comment]
Pinning to the latest tagged release has resolved my issue. I'll try setting up a new Pi with latest OS to see if latest version works. Thanks!
