### ISSUE TITLE
Can't install on RPi Zero

### ISSUE THREAD

**Issue by jonasftw** [philippe44/AirConnect#435]
How I try to install it:
`wget https://github.com/philippe44/AirConnect/raw/master/bin/aircast-linux-arm`
then
`chmod +x aircast-linux-arm`
and finally
`sudo ./aircast-linux-arm`
then I get error
`Illegal instruction`

I tried following this
https://github.com/philippe44/AirConnect/issues/138#issuecomment-454651523 
But I don't really understand how to use symlinks correctly. Thank you in advance
<details>
<summary>openssl version -a</summary>
OpenSSL 1.1.1n  15 Mar 2022
built on: Wed Jun 29 09:57:19 2022 UTC
platform: debian-armhf
options:  bn(64,32) rc4(char) des(long) blowfish(ptr) 
compiler: gcc -fPIC -pthread -Wa,--noexecstack -Wall -D__ARM_MAX_ARCH__=7 -Wa,--noexecstack -g -O2 -ffile-prefix-map=/build/openssl-g0RSef/openssl-1.1.1n=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/arm-linux-gnueabihf/engines-1.1"
Seeding source: os-specific
</details>

**Comment by philippe44** [comment]
It's that I don't support old PiZero anymore (CPU is old)

**Comment by jonasftw** [comment]
Is there any workaround?

**Comment by philippe44** [comment]
None that I'm aware of. These pi0 use an old arm chipset for which I have not built the binaries.

**Comment by philippe44** [comment]
I was able to build a compiler for these old processors. Give a try to the version containing "-armv6"

**Comment by jonasftw** [comment]
`pi@raspberrypi:~ $ ./aircast-linux-armv6`

```
[12:02:05.926987] main:884 Starting aircast version: v1.0.9 (Nov  5 2022 @ 22:48:42)
[12:02:05.934058] main:887 weird GLIBC, try -static build in case of failure
[12:02:05.934477] main:891 no config file, using defaults
[12:02:05.937769] Start:662 Binding to 192.168.31.19
```

**Comment by philippe44** [comment]
Hav you tried the static version? Have you verified that previous version did work? Can you rename that version by the name of previous one and try?

**Comment by jonasftw** [comment]
It used to work with RPi 4, though I used wired connection. Yes, I've tried the static version as well.

**Comment by philippe44** [comment]
So you have never tried the old version on a PiZero so the fact that it does not find anything is likely not due to the new version itself but to some network config where you have a different subnet where that pi now sits. FYI, I have verified that version on my own old Pi0 that I was able to dust off.

**Comment by jonasftw** [comment]
> It used to work with RPi 4, though I used wired connection. Yes, I've tried the static version as well.



> `pi@raspberrypi:~ $ ./aircast-linux-armv6`
> 
> ```
> [12:02:05.926987] main:884 Starting aircast version: v1.0.9 (Nov  5 2022 @ 22:48:42)
> [12:02:05.934058] main:887 weird GLIBC, try -static build in case of failure
> [12:02:05.934477] main:891 no config file, using defaults
> [12:02:05.937769] Start:662 Binding to 192.168.31.19
> ```
> 
> stuck here

Now I get stuck at the same message on RPi 4B too.

**Comment by philippe44** [comment]
Hmmm... and on the exact same pi4, the old version works, now ?

**Comment by jonasftw** [comment]
When I meant RPi 4, I was talking about the 4B

> It used to work with RPi 4, though I used wired connection. Yes, I've tried the static version as well.

**Comment by philippe44** [comment]
> It used to work with RPi 4, though I used wired connection. Yes, I've tried the static version as well.
> 
So I'm confused and we need a controlled experiment. On the same ou, with the same network conditions, what works and what does not work

**Comment by jonasftw** [comment]
So I played around with RPi's and this is what I found out. My router probably blocks wireless UPnP messages, because I can't communicate with UPnP devices wirelessly, however when I used wired connection I was able to connect UPnP volume with RPi, but I'm still stuck at `Binding to`.

**Comment by jonasftw** [comment]
Just reinstalled Raspbian.
Wired RPi 4B

```
pi@raspberrypi:~ $ ./aircast-linux-arm-static 
[00:30:18.417746] main:884 Starting aircast version: v1.0.9 (Nov  5 2022 @ 22:48:33)
[00:30:18.418257] main:891 no config file, using defaults
[00:30:18.418722] Start:662 Binding to 192.168.31.87
```

**Comment by philippe44** [comment]
Are you sure 193.168.31.x is the wired network ?

Envoyé de mon iPhone

Le 9 nov. 2022 à 14:31, jonasftw ***@***.***> a écrit :

﻿

Just reinstalled Raspbian.
Wired RPi 4B

***@***.***:~ $ ./aircast-linux-arm-static
[00:30:18.417746] main:884 Starting aircast version: v1.0.9 (Nov  5 2022 @ 22:48:33)
[00:30:18.418257] main:891 no config file, using defaults
[00:30:18.418722] Start:662 Binding to 192.168.31.87

**Comment by Xerus-de** [comment]
> I was able to build a compiler for these old processors. Give a try to the version containing "-armv6"

@philippe44 : Thank you for the new armv6 version. This worked for me on RPi Zero!

Best regards

**Comment by jonasftw** [comment]
It's probably router issues.
