### ISSUE TITLE
Phorus/Play-Fi fix uPNP

### ISSUE THREAD

**Issue by alikej** [philippe44/AirConnect#437]
I want to thank you for this software. Great Job!

I use AirUPnP bridge to render audio to Phorus/Play Fi - Klipsh the Three device. I can confirm that the only way to get audio from AirConnect to the device is to use the MP3 format. But other programs such as Audirvana+ player successfully deliver sound up to WAV 24/96 quality.

The Audirvana player provides a debug log that shows information about successful playback in WAV 24bit/96 kHz format. I hope this log will help the developer to fix this issue. Thanks for the response.

[Klipsh Audirvana.log](https://github.com/philippe44/AirConnect/files/10008327/Klipsh.Audirvana.log)

**Comment by philippe44** [comment]
Thanks - I would need a log of airupnp either usign flac or wav when it fails

**Comment by alikej** [comment]
Here is it (no sound):

**Comment by philippe44** [comment]
There is no file attached

**Comment by alikej** [comment]
Once again

**Comment by alikej** [comment]
Sorry, my fault ... 

[air.log](https://github.com/philippe44/AirConnect/files/10008451/air.log)

**Comment by philippe44** [comment]
SO you have tried using "-c flc" and "-c pcm" with no success, right? Have you tried also "-g -1" with also either flac or pcm?

**Comment by alikej** [comment]
Yes, I did - no success for both variants. I tried all http_lengt options, -1,  -3, 0. Results are the same.
[flc-1.log](https://github.com/philippe44/AirConnect/files/10012381/flc-1.log)
[pcm-1.log](https://github.com/philippe44/AirConnect/files/10012382/pcm-1.log)

**Comment by philippe44** [comment]
Sorry I don't understand what you mean by "playing to a manual stop"

**Comment by alikej** [comment]
I meant that both FLAC and PCM playback doesn't work. But play control on iOS shows on FLAC stream that the stream is playing (which is not true - you have to manually push stop button in control center). On the other hand, when trying to play the PCM, play control on iOS shows after a few seconds that the stream is not playing.
