### ISSUE TITLE
Can't run the application in Windows 11

### ISSUE THREAD

**Issue by CaptainMalReynolds** [philippe44/AirConnect#441]
It used to work fine in WIndows 10, but in Windows 11 I run aircast.exe and it gives me dll errors. I tried to re-install c++ libraries, tried to download DLLs manually and put them both into exe folder or windows folder - nothing helps. It started giving me another error like "the application was unable to start correctly", which is also dll related.
If I run static version it works, but normal one doesn't.
Any solution to that? Thanks

**Comment by philippe44** [comment]
What DLL did you use

**Comment by CaptainMalReynolds** [comment]
I tried to replace a whole bunch of dll, in particular:
libcrypto-1_1.dll
libssl-1_1.dll
ucrtbase.dll
ucrtbased.dll
vcruntime140.dll
vcruntime140_1.dll
vcruntime140_1_app.dll
vcruntime140_1d.dll
vcruntime140_app.dll
vcruntime140_clr0400.dll
vcruntime140d.dll
xinput1_3.dll

**Comment by philippe44** [comment]
Can you give me the message with just the libssl, libcrypto, urctbase,dll and vcruntime140.dll in the same directory

**Comment by CaptainMalReynolds** [comment]
It gives me "The code execution cannot proceed because VCRUNTIME140D.dll was not found. Reinstall the program..".
Even though vcruntime140.dll is in the same folder.

**Comment by philippe44** [comment]
Please use 1.0.13 and install https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by CaptainMalReynolds** [comment]
Thank you, installing 1.0.14 helped!

**Comment by WinkelCode** [comment]
I'm still having this issue in `1.0.8` (did the numbering change? There is no `1.0.14`?)

The problem is that it has been built in debug, rather than release mode. Note how the missing `.dll`'s end in `[something]d.dll`.
