### ISSUE TITLE
"No Player found" - No more option to select binary

### ISSUE THREAD

**Issue by MaDe74** [philippe44/AirConnect#442]
Hi there,

since yesterday LMS via the UPnP / DLNA bridge doesn't work anymore - there is no player to be found.

So, after I did not change anything within my configuration / hardware but have ticked the checkbox "automatic updates" within the LMS plugins-dialogue _I assume_ there has been changes in the UPnP / DLNA bridge plugin lately that have been installed in the background.

One thing I recognized **yesterday** was, that in the settings menue of UPnP / DLNA bridge the option to chose the binary (e.g. "arm.static") was gone. 
**Today**, after another update of the plugin there is just a hint/link advising "Windows users, please install this". But still no way to choose the fitting binary. And still "No Player Found"

So, if my "loss of players" is caused by an update of the plugin I'd be really happy if this issue would be fixed asap.

If not I'd be happy to receive an advice what to do next in order to get the thing running again. 

Thanks alot in advance,

kind regards,
Marcel

**Comment by philippe44** [comment]
Your in the wrong project
