### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by mickeynygaard** [philippe44/AirConnect#444]
Hi - Manually attempting to access https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/aircast-arm throws a 404, as is the same result when attempting via the docker instance by 1activegeek

Am I missing something or is something wrong somewhere?

**Comment by eizedev** [comment]
Hi, the url is not correct -> https://github.com/philippe44/AirConnect/blob/master/bin/aircast-linux-arm
