### ISSUE TITLE
confused :(

### ISSUE THREAD

**Issue by jospectrum** [philippe44/AirConnect#445]
"WARNING: /usr/local/Cellar/AirConnect-master/bin/aircast-macos-x86_64 is loading libcrypto in an unsafe way 

It really doesn't work at all. I've this message when I type "/usr/local/Cellar/AirConnect-master/bin/aircast-macos-x86_64". I think, I've completely confused the process, it's so complicated on Mac (even more so when you are French person), and I don't understand why there are exe files for windows, whereas AirPlay is an Apple feature, so it's for APPLE DEVICES??

**Comment by philippe44** [comment]
C'est une application qui marche sur n'importe quel ordinateur, que ce soit Windows, Linux, MacOS, freebsd ou Solaris. Ça réalise un pont entre AirPlay et Chromecast ou UPnP qui est offert à tous les ordinateurs sur le réseau. C'est très simple, même pour un français (ça a été créé par un français 😃). Pour un mac, j'ai ajouté des explications pour les versions macOS récentes pour cette histoire de libcrypto. Sinon, il suffit de prendre la version nommée -static.

**Comment by jospectrum** [comment]
Je me sens un peu honteux du coup - 

Mais en ce qui concerne les raccourcis libcrypto, j'ai beau faire un copier coller en remplaçant le x.y.z par la version de open ssl (3.0.7) ça m'indique ceci: "zsh: no matches found: /usr/local/opt/openssl[/3.0.7]/lib/libcrypto.dylib
zsh: no matches found: /usr/local/opt/openssl[/3.0.7]/lib/libssl.dylib". Soit j'ai pas compris ce qu'il était nécessaire de faire, soit j'ai aucune idée de ce que peut être le problème. J'ai aussi tenté d'ouvrir directement depuis la source les fichiers et ça m'indique "permission refusé" 
![Capture d’écran 2023-01-07 à 8 33 38 PM](https://user-images.githubusercontent.com/122173318/211167576-9571246b-0eaf-407c-bd7e-56ca16e29378.png)

**Comment by philippe44** [comment]
Le mieux est peut-être de commencer avec la version -static

**Comment by jospectrum** [comment]
ok, merci beaucoup ça marche! mais du coup c'est quoi la différence entre la version "-static" et la version sans. j'ai aussi installé docker mais je comprends pas du tout non plus le concept. en effet ça marche mais il y a beaucoup d'éléments qui restent très flous

**Comment by philippe44** [comment]
La version static n'a pas besoin de librairies externes. L'avantage de celles-ci est qu'elles peuvent êtres mises à jour indépendemment des applications qui les utilisent. Ca peut-être très important pour les libraries de cryptographie qui sont susceptibles d'avoir des trous de sécurité corrigés à tout moment. Mais parfois, comme ici, trouver les libraries externes peut-être problématique, ou elles peuvent ne pas être compatibles. Tout inclure dans l'application permet d'éviter ces problèmes mais plus de mises à jour sauf si c'st moi qui les fournis alors.

Pour le concept, l'application détecte les lecteurs Chromecast (respectivement UPnP) et pour chacun, elle crée un lecteur AirPlay "virtuel" et informe tout le monde sur le réseau de l'existence de ce lecteur virtuel. C'est tout. Ensuite, tout système qui est compatible AirPlay parle à ces lecteurs virtuels (en étant persuadé qu'il s'agit d'une vraie enceinte AirPlay) et mon application transcode tout en protocole Chromecast UPnP). Voilà.
