### ISSUE TITLE
1.0.13 - aircast/airupnp Core Dump - arm armadaxp

### ISSUE THREAD

**Issue by eizedev** [philippe44/AirConnect#446]
Hi @philippe44 

the user @tschniewind is using the Synology package AirConnect-Synology on his older Synology NAS system. It has a `Marvell Armada XP MV78230` cpu (ARM architecture). Version 0.2.51.2 was working fine with the ARM binaries. (More information in the [issue](https://github.com/eizedev/AirConnect-Synology/issues/63).
Another user has similar problems running on x86 architecture (32bit). But therefore i have no information if the processes dumped core.

Both binaries core dumped during startup. Using [aircast 1.0.13](https://github.com/philippe44/AirConnect/blob/master/bin/aircast-linux-arm) and [airupnp 1.0.13](https://github.com/philippe44/AirConnect/blob/master/bin/airupnp-linux-arm). Same with the static binaries.

Could you please check this? (logfiles with command line below)

If you need the compressed core files, perhaps @tschniewind could send them to you (on a safe way).
Thanks,
René

Log messages from `/var/log/messages`

```bash
2023-01-09T18:50:52+01:00 NAS2 coredump[12515]: Process airupnp[12514](/volume1/@appstore/AirConnect/airupnp) dumped core on signal [11]. Core file [/volume1/@airupnp.synology_armadaxp
_rs814.42962.core.gz]. Cmdline [/volume1/@appstore/AirConnect/airupnp -b 192.168.0.36:49154 -l 1000:2000 -x /volume1/@appstore/AirConnect/config.xml -o <NULL>,S1,S3,S5,S9,S12,ZP80,ZP90
,S15,ZP100,ZP120,1.0,LibreWireless,Fitzwilliam,2.2.6,AllShare1.0 -z -f /volume1/@appstore/AirConnect/log/airconnect.log -d all=info ]
2023-01-09T18:50:52+01:00 NAS2 coredump[12515]: Core file [/volume1/@airupnp.synology_armadaxp_rs814.42962.core.gz] size [45629]
2023-01-09T18:50:52+01:00 NAS2 coredump[12537]: Process aircast[12536](/volume1/@appstore/AirConnect/aircast) dumped core on signal [11]. Core file [/volume1/@aircast.synology_armadaxp
_rs814.42962.core.gz]. Cmdline [/volume1/@appstore/AirConnect/aircast -b 192.168.0.36 -l 1000:2000 -x /volume1/@appstore/AirConnect/config-cast.xml -z -f /volume1/@appstore/AirConnect/
log/airconnect.log -d all=info ]
2023-01-09T18:50:52+01:00 NAS2 coredump[12537]: Core file [/volume1/@aircast.synology_armadaxp_rs814.42962.core.gz] size [53658]
```

**Comment by tschniewind** [comment]
@philippe44 Many thanks for your support. Synology provides the following information for a RS814:
RS814 | Marvell Armada XP MV78230 | Dual Core | 2 | Yes | Armadaxp

I don't know if it's an arm5?

**Comment by philippe44** [comment]
No it's an armv7, so next thing is to take a log

**Comment by eizedev** [comment]
As discussed in this [issue](https://github.com/eizedev/AirConnect-Synology/issues/63) the problem is related to an old kernel in the RS814 Synology NAS and AirConnect version 1 does not support older kernel versions.
