### ISSUE TITLE
I don't understand anything right now! :(

### ISSUE THREAD

**Issue by aythequeenlin** [philippe44/AirConnect#447]
How do I even do this?? I'm so confused... :( I tried to get it working but I failed. I'm new with this shit! :'(

**Comment by philippe44** [comment]
Well, if you call it "shit", don't expect much support

**Comment by philippe44** [comment]
Well, obviously you're digging deeper.

**Comment by philippe44** [comment]
The comment "thanks for jumping to conclusion" would not qualify as a friendly and motivational remark to clean the air.

**Comment by philippe44** [comment]
Closed for inactivity
