### ISSUE TITLE
Both speakers have the same name

### ISSUE THREAD

**Issue by accpxyz** [philippe44/AirConnect#453]
First, thanks a lot for this project!
Before using any parameter, the two speakers can recognize the correct name. When using the - i parameter to generate and change the name in the configuration, and using the - x parameter,  name of the two speakers are the same. After viewing the configuration file, it is found that the udn(uuids) are the same. How to recognize them correctly？

**Comment by philippe44** [comment]
Strange - whare are these speakers? Can you show me the config file?

**Comment by accpxyz** [comment]
The config file :
[airupnp.txt](https://github.com/philippe44/AirConnect/files/10929831/airupnp.txt)

**Comment by philippe44** [comment]
These players have the same uuid which is forbidden by standard, AFAIK (uuid is supposed to be **unique**)
