### ISSUE TITLE
Huawai Sound X working but not correct

### ISSUE THREAD

**Issue by bloop16** [philippe44/AirConnect#459]
Hello,
I made my SoundX box running with Airupnp.
Debian 11
ios Device as transmitter
airupnp-linux-x86_64-static 1.0.17
LXC on Proxmox

Changing codec to mp3 worked for me.

Issue:
Box connects, and recognizes an incoming stream. The Stream stops immediately after start playing. In my stream device sound is still playing. After Stopping the Sound starts on the SoundX as long as it was streaming before. Afterword's it is not possible to play anything anymore.

[config.txt](https://github.com/philippe44/AirConnect/files/11158960/config.txt)
[Log.txt](https://github.com/philippe44/AirConnect/files/11159000/Log.txt)

Thanks a lot!

**Comment by philippe44** [comment]
I'm not sure I'm following exactly the sequence of events. This log shows a track being send, starting to play. Then about 40s after the request, the user (or at least the AirPlay controller) initiates a termination of playback.

**Comment by bloop16** [comment]
Sorry about my English...
Exactly, the track gots send, but nothing starts to play.
After 40sek i stopped the track. With stopping the track it started to play on the device for 40sek and then stopped.

**Comment by philippe44** [comment]
Try to use another codec that flac and try to change HTTP mode. I've seen many players that claim to be HTTP 1.1 and fail when "chunked" encoding is used, which is normally *mandatory* in 1.1. Huawei is a big offender there...

**Comment by philippe44** [comment]
Closed for inactivity
