### ISSUE TITLE
Releases no longer publishing

### ISSUE THREAD

**Issue by 1activegeek** [philippe44/AirConnect#461]
User recently opened an issue for me on the docker container about not pulling the latest version: https://github.com/1activegeek/docker-airconnect/issues/52. It seems right around the time I re-architected my build scripts to use the release notifications and creating tags, releases no longer were published.

Wanted to check if you may have something that just got missed somewhere, or if you are no longer planning to publish the releases? If not, can you point me at the best record to identify what the current version of the binary is? I'm thinking if you no longer publish releases I can do something like grab the first line of the changelog file which seems to usually show the current version? 

Would like to validate verify through you before I make changes to fix the container build process.

**Comment by philippe44** [comment]
It's just laziness on my side as the releases are done manually. I'll resume after a few updates

**Comment by 1activegeek** [comment]
All good. Any possibility I can help with building a Github Action maybe that can automatically build it for you? I'd imagine it shouldn't be much more than maybe packaging up the directory contents into a tarball. Should be relatively easily doable based on something like certain commit style, or maybe tag to add to the commit so it can flag it? Happy to help out. For now I might see about building in the backup using the changelog. Appreciate the app still, going strong in my house! 😃

**Comment by owlboy** [comment]
Looking forward to a binary release...

**Comment by 1activegeek** [comment]
Looks like this is back on track, and I was able to get the action running again to kick out the latest version and the appropriate tag on the GitHub. Marking as closed - thank you!!
