### ISSUE TITLE
chromecast volume

### ISSUE THREAD

**Issue by FatFairFoot** [philippe44/AirConnect#463]
Hello,

I just have a little issue with the volume, each time the cast begin the volume is low.
Maybe I'm missing something ?

I see this when the stream starts :

[17:06:15.188453] handle_rtsp:363 [0x7f2ba4013fd0]: received SET_PARAMETER
[17:06:15.188475] handle_rtsp:528 [0x7f2ba4013fd0]: SET PARAMETER volume -20.000000
[17:06:15.188489] CastSetDeviceVolume:299 [0x1150ac0]: Queuing SET_VOLUME
[17:06:15.188499] raop_cb:227 [0x1150ac0]: Volume[0..1] 0.3333
[17:06:15.188575] handle_rtsp:562 [0x7f2ba4013fd0]: responding:
RTSP/1.0 200 OK
Audio-Jack-Status: connected; type=analog
CSeq: 7

So, I generated a config file for aircast and set <media_volume>1</media_volume>, because I saw that this could help but nothing changes.
(Seeing in the logs that "[17:04:11.321656] main:891 no config file, using defaults" not displaying anymore so the confilg file seems to be processed)

Target devices are Nest Hubs and Nest Audios.

Could you help me with this ?

Thanks !!!

**Comment by philippe44** [comment]
I've updated to 1.1.1 which get rid of group volume scaling factor

**Comment by eizedev** [comment]
@FatFairFoot version `1.1.1` is available in latest `AirConnect-Synology` release for your device: https://github.com/eizedev/AirConnect-Synology/releases/tag/1.1.1-20230423

**Comment by FatFairFoot** [comment]
Thanks guys !!!!

Now, when I'm changing the volume while casting to a group of chromecast devices, it works like a charm ! :-)

But the cast is still beginning with a volume of 3/10.
Is there any trick to force the volume to be louder at the beginning of the cast ?
(It's juste t be more comfortable because I can change the volume by myself now :) )

Thanks again for your work !

**Comment by philippe44** [comment]
> @FatFairFoot version `1.1.1` is available in latest `AirConnect-Synology` release for your device: https://github.com/eizedev/AirConnect-Synology/releases/tag/1.1.1-20230423
>
BTW, I don't know if you saw that but I've released 2 new bridges (SpotConnect) that do Spotify to UPnP and Spotify to AirPlay. Let me know if you want to package them as well
