### ISSUE TITLE
SIGPIPE after a few seconds of playing to Chromecast group

### ISSUE THREAD

**Issue by jbyers** [philippe44/AirConnect#464]
Aircast linux-arm-static 1.1.3 exits with SIGPIPE after a few seconds of playing from an iPad (Audible app on iPadOS 16.3.1) to a Chromecast group. Group is comprised of a Nest Audio and a Nest Hub Max.

Playing to a single Chromecast device works fine. Debug log attached.
[debug.log](https://github.com/philippe44/AirConnect/files/11415854/debug.log)

Exit status is 141 (SIGPIPE):
```
 $ ./aircast-linux-arm-static -f debug.log
$ echo $?
141
```

**Comment by philippe44** [comment]
There might be a problem with group and the new feature that shows metadata. Such metadata is requested by the player and because AirPlay wants a blob and not an url, I had to create a tiny http server.

Try 1.1.5 where I've changed the way sockets are closed.

**Comment by philippe44** [comment]
Comment?

**Comment by philippe44** [comment]
Closed for inactivity
