### ISSUE TITLE
Initialisation volume defaults to 30%

### ISSUE THREAD

**Issue by frankie2784** [philippe44/AirConnect#468]
It would be helpful to be able to set the default volume when initialising aircast, or better yet to maintain the existing volume of the connected speakers.

At the moment, when initially connecting to an aircast speaker(s), the volume appears to default to 30%, regardless of what the speaker(s) was set to before pairing. A 30% default would be fine I guess if it were connected to a Google Nest, for example. However, 30% on my Samsung Q930B soundbar is incredibly loud (about 8% on the soundbar is equivalent to 30% on Google Nest). At the moment, with the current defaults, I have to make sure I'm not playing anything when I first pair the speaker, otherwise my neighbours will become very unhappy with me!

**Comment by philippe44** [comment]
The culprit is usually the AirPlay controller. I don't set volume until I've received an order from it

**Comment by Goooooooooood** [comment]
I have seen similar problems elsewhere.  https://github.com/philippe44/AirConnect/issues/350

I also have a similar issues. 
My iOS 12.4.1 volume is OK, it will remember the volume setting. 
But on my iOS 15.7.1 connection, the volume is always auto set to 30%.

**Comment by philippe44** [comment]
I really don't know why. From tests I've made, the controller actually sends a volume command at 30%, so there is not much I can do as volume must be handled.
