### ISSUE TITLE
Run AirConnect on XigmaNas faile

### ISSUE THREAD

**Issue by eastwoodnet** [philippe44/AirConnect#474]
Hey ，Someone can run Airupnp on freebsd OS ?
I was run airupnp-freebsd-x86_64-static  on XigmaNas system failed

```
xigmanas: ~# ./airupnp-freebsd-x86_64-static 
[15:07:07.099682] main:1367 Starting airupnp version: v1.1.7 (May 20 2023 @ 06:12:14)
[15:07:07.100089] main:1374 no config file, using defaults
[15:07:07.102360] Start:1086 Binding to iface re0@192.168.1.250:0
[15:07:07.102494] Start:1090 UPnP init in 192.168.1.250 () failed: -203
[15:07:07.102510] main:1406 Cannot start

```

Is there any error log can be read ?

**Comment by philippe44** [comment]
Is re0 your Ethernet interface?

**Comment by eastwoodnet** [comment]
Yes
`re0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>
        ether XX:XX:XX:XX:XX:ab
        inet 192.168.1.250 netmask 0xffffff00 broadcast 192.168.1.255
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
`

**Comment by philippe44** [comment]
Oh, try to specify a port to bind to. It seems that the UPnP library cannot bind on the one it chooses by default. Maybe you also need to give more authorizations. I'm not using FreeBSD very often.

**Comment by philippe44** [comment]
I also gave it a try on a fresh install of that XigmaNAS and it worked
