### ISSUE TITLE
Is the issue of Huawei Sound playing music without sound still unresolved?

### ISSUE THREAD

**Issue by woann** [philippe44/AirConnect#477]

**Comment by woann** [comment]
> I've not done anything for that

Is there no way to solve this problem?

**Comment by philippe44** [comment]
Candidly I don't even remember what was the issue and if there were logs

**Comment by woann** [comment]
> Candidly I don't even remember what was the issue and if there were logs

It's the problem that Huawei sound plays music without sound... You search for the keyword "huawei" in the issue, and several people have given feedback on this problem...

**Comment by philippe44** [comment]
Maybe we can try again with what you experience and send a log so I can have a fresh start
