### ISSUE TITLE
Compatibility with LMS AirPlay bridge?

### ISSUE THREAD

**Issue by ayush-bharti** [philippe44/AirConnect#478]
Hi Philippe,

Firstly, thank you so much for your amazing contributions to the open source community. I have just gotten into hosting LMS at home and have been discovering and enjoying all your wonderful contributions.

I have a few Google home minis setup in my house. I used AirConnect to enable AirPlay on them, this works great. I am able to play audio from my iPhone and Macbook to a google mini using it's Airplay equivalent. However, when I tried to the same using LMS's Airplay bridge feature, it doesn't even detect the google mini airplay devices. I have already tried generating a new config file as well as restarting LMS, but to no avail.

Btw, I am able to use the Chromecast bridge to cast music to the very same Google mini devices. So I am a little lost as to why this is happening. Any help you can provide or information pointing me in the right direction would be very helpful.

Thanks once again!

**Comment by philippe44** [comment]
Thanks - it's on purpose that virtual AirPlay devices created by AirConnect are ignore by the LMS AirPlay bridge. You should use directly the Chromecast or UPnP bridge

**Comment by ayush-bharti** [comment]
Understood. Thanks for your help!
