### ISSUE TITLE
huawei sound x  can be search , but  not have sound , can control the volume

### ISSUE THREAD

**Issue by oMosted** [philippe44/AirConnect#481]
huawei sound x  can be search , but  not have sound , can control the volume

**Comment by philippe44** [comment]
Have you read the instruction about firewall?

**Comment by woann** [comment]
> 你读过关于防火墙和docker主机模式的说明吗？



> Have you read the instruction about firewall and docker host mode?

Many people have already reported that Huawei Sound has this issue, why not solve it?

**Comment by woann** [comment]
> Have you read the instruction about firewall and docker host mode?

Many people have already reported that Huawei Sound has this issue, why not solve it?

**Comment by philippe44** [comment]
> > Have you read the instruction about firewall and docker host mode?
> 
> Many people have already reported that Huawei Sound has this issue, why not solve it?
>
??? I'm not sure of the meaning of that question

**Comment by woann** [comment]
> 
When using the "Huawei sound" sound system, the iPhone's airplay can search for the "Huawei sound" sound system, but there is no sound, even if the volume is turned to maximum. That is to say, except for the absence of sound, all other manifestations are normal

**Comment by philippe44** [comment]
Yes but I suggested to the OP that it might still be a network issue due to a docker configuration or a firewall problem. Other than that, your way to ask question is surprising, sounding a bit like : "why isn't the general Huawei problem already fixed, what have you been doing all this time, you lazy b...?"

**Comment by woann** [comment]
> 

The statement of network issues is not valid and has not been used in the Docker environment, and in the same network environment, Xiaomi's Xiaoai speaker can play normally. Of course, I just suggest that you solve this problem and have no other meaning. It may be that my English expression is not accurate.

**Comment by philippe44** [comment]
I suggested moving to http/1.0 on the other thread and here I have not received any response to my initial question nor did I get logs
