### ISSUE TITLE
Request support for mipsel platform

### ISSUE THREAD

**Issue by wangshe** [philippe44/AirConnect#484]
Hi sir, I want to use airconnect in a router with Openwrt system, the soc is MediaTek MT7621A,  it belongs to mipsel platform. Please support for this. Thanks a lot.

**Comment by philippe44** [comment]
I've added a mips32el version. Not sure it works, I don't have anything to test

**Comment by wangshe** [comment]
Thanks a lot, I'm going to test today.

**Comment by wangshe** [comment]
I got error "Illegal instruction", what should I do?
![微信图片_20230823083547](https://github.com/philippe44/AirConnect/assets/20431676/3d238494-0f33-4439-8c58-817448b66b76)

**Comment by philippe44** [comment]
Try the -static version. If it still does not work, I won't be able to help much. I don't have any hardware to check. It's compiled for a MIPS3000 type of CPU, 32 bits.

**Comment by philippe44** [comment]
oh ... you are launching just ./airupnp ???? you have to launch the mipsel dedicated version!!!, so ./airupnp-linux-mipsel or ./airupnp-linux-mipsel-static

**Comment by wangshe** [comment]
I lunched airupnp-linux-mipsel-static, just changed the file name to airupnp then I lunched. But is showing Illegal instruction

**Comment by philippe44** [comment]
I really don't know then. Maybe it's a 64 bits Linux version and you'd need the 32 bits runtime Linux environment. Maybe another instruction set should be used at compile time but I can't account for all versions of mips. I chose the mips32 which is supposed to be the most common.

**Comment by wangshe** [comment]
I have checked,  need to compile with openwrt golang.  Similar like compile this frp. https://github.com/wangshe/packages/blob/master/net/frp/Makefile.
But that is huage job.

**Comment by philippe44** [comment]
It's not going to work then
