### ISSUE TITLE
No Interfaces attached

### ISSUE THREAD

**Issue by hyyczz** [philippe44/AirConnect#486]
Hi
Thank you for your work~
I had a problem. I successfully installed the latest version Airconnect, and luci, and started to configured. (OPENWRT FOR DEVICE PHICOMME K2P)
However, Global Settings-Interface-Lan (No Interfaces attached), which means that it didn't work due to some incorrecting settings?
Network-Interfaces-lan, (type brige) showed there are some connectioned including wireless Adapter.
How can I solve this problem?

**Comment by philippe44** [comment]
Sorry that's not very clear. I'd need to see the log

**Comment by hyyczz** [comment]
> Sorry that's not very clear. I'd need to see the log

hi [philippe44](https://github.com/philippe44)

> Sorry that's not very clear. I'd need to see the log

Sat Sep 16 10:15:07 2023 daemon.notice hostapd: phy0-ap0: EAPOL-4WAY-HS-COMPLETED 3c:cd:57:2d:1c:67
Sat Sep 16 10:15:08 2023 daemon.warn odhcpd[3517]: No default route present, overriding ra_lifetime!
Sat Sep 16 10:15:15 2023 daemon.info hostapd: phy0-ap0: STA 58:b6:23:f0:d4:ed IEEE 802.11: authenticated
Sat Sep 16 10:15:15 2023 daemon.info hostapd: phy0-ap0: STA 58:b6:23:f0:d4:ed IEEE 802.11: associated (aid 2)
Sat Sep 16 10:15:16 2023 daemon.notice hostapd: phy0-ap0: AP-STA-CONNECTED 58:b6:23:f0:d4:ed auth_alg=open
Sat Sep 16 10:15:16 2023 daemon.info hostapd: phy0-ap0: STA 58:b6:23:f0:d4:ed WPA: pairwise key handshake completed (RSN)
Sat Sep 16 10:15:16 2023 daemon.notice hostapd: phy0-ap0: EAPOL-4WAY-HS-COMPLETED 58:b6:23:f0:d4:ed
Sat Sep 16 10:15:46 2023 cron.info crond[5389]: crond (busybox 1.36.1) started, log level 8
Sat Sep 16 10:15:46 2023 daemon.err uhttpd[3764]: sh: write error: Broken pipe
Sat Sep 16 10:15:48 2023 cron.info crond[5485]: crond (busybox 1.36.1) started, log level 8
Sat Sep 16 10:16:40 2023 kern.warn kernel: [  387.376604] process '/usr/bin/airupnp' started with executable stack
Sat Sep 16 10:17:05 2023 daemon.info procd: Instance airconnect::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Sat Sep 16 10:17:05 2023 daemon.info procd: Instance airconnect::instance2 s in a crash loop 6 crashes, 0 seconds since last crash
![微信截图_20230916103312](https://github.com/philippe44/AirConnect/assets/143316593/7b690219-3e3a-4498-b4c2-ff056ad7d9c5)
![微信截图_20230916103232](https://github.com/philippe44/AirConnect/assets/143316593/6b2ba884-e790-4e44-8cdc-03b4746486be)

**Comment by philippe44** [comment]
No I mean the log of airupnp. It's unlikely to work on openwrt though

**Comment by hyyczz** [comment]
> No I mean the log of airupnp. It's unlikely to work on openwrt though

sorry may  i ask how can I check the log of airupnp?  Any code for Putty?

**Comment by philippe44** [comment]
It's explained in the README. It's either output to stderr or into a file with "-f <logfile>"

**Comment by philippe44** [comment]
closed for inactivity
