### ISSUE TITLE
Not possible to cast to older google homes

### ISSUE THREAD

**Issue by SoCuul** [philippe44/AirConnect#487]
I currently have a home setup of 1 Google Home (1st Gen), 3 Google Home Minis (1st Gen) and 1 Google Nest Audio.

While all the devices appear in the airplay menu, I am only able to successfully play sound out of the Google Nest Audio, which is also the newest device out of this list.

I have tried resetting the other devices, and restarting the air connect server, but nothing seems to resolve the problem. No errors are shown when connecting to the other devices, it just shows no audio as being transmitted.

**Comment by philippe44** [comment]
Please attach a log

**Comment by SoCuul** [comment]
This is the only output I could find from docker. Is there a log file generated at another location?
```
[migrations] started
[migrations] no migrations found
Checking for valid arch options
Proceeding with linux-x86_64 arch
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____
      | __  |  |  | |  |  |    \
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
2023-09-17 03:12:28,032 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-09-17 03:12:28,039 INFO supervisord started with pid 155
2023-09-17 03:12:29,040 INFO spawned: 'aircast-linux-x86_64' with pid 158
2023-09-17 03:12:30,085 INFO success: aircast-linux-x86_64 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by philippe44** [comment]
There is a log of aircast itself. It depends how you started it, it's either in the stderr or a file, if you have used the -f option on the command line.

**Comment by SoCuul** [comment]
This is the untouched log, other than the fact I changed the values of the mac addresses.

[airconnect.log](https://github.com/philippe44/AirConnect/files/12654034/airconnect.log)

**Comment by philippe44** [comment]
What is your platform (OS/CPU)? I'll do a build with a couple of extra logs

**Comment by SoCuul** [comment]
> What is your platform (OS/CPU)? I'll do a build with a couple of extra logs

Feel free to let me know if you need more info :)

OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 5.15.0-83-generic
CPU: Intel i5-6260U (4) @ 2.900GHz

**Comment by philippe44** [comment]
[aircast-linux-x86_64.zip](https://github.com/philippe44/AirConnect/files/12655962/aircast-linux-x86_64.zip)
Try that, it will tell the IP and port discovered for the CC players. What seems to happen is that the socket connection fails, which is really weird. I've been using CC (all generations) for ages and never had that.

**Comment by philippe44** [comment]
Also, have you tried to run it native, not in docker? And docker is in host mode, right?

**Comment by SoCuul** [comment]
> Also, have you tried to run it native, not in docker? And docker is in host mode, right?

I've only ran it in docker, but it's in host mode.

**Comment by philippe44** [comment]
> I've only ran it in docker, but it's in host mode.
>
Let's see what this log gives

**Comment by philippe44** [comment]
Did you try the updated apps?

**Comment by SoCuul** [comment]
> Did you try the updated apps?

Ooh I just saw this now. I'll try it when I get home later tonight!

**Comment by SoCuul** [comment]
[aircast-sep19-516pm.log](https://github.com/philippe44/AirConnect/files/12667414/aircast-sep19-516pm.log)

Here it is. I made sure to do a few things such as skipping and returning to previous song, changing volume and playing/pausing. Hope this can be of help.

**Comment by philippe44** [comment]
That is a really weird error you're having. Can you do 2 things

1- take log with that version
2- try to disable ipv6 in your docker *and* host to see
[aircast-linux-x64.zip](https://github.com/philippe44/AirConnect/files/12678700/aircast-linux-x64.zip)

**Comment by SoCuul** [comment]
> That is a really weird error you're having. Can you do 2 things
> 
> 
> 
> 1- take log with that version
> 
> 2- try to disable ipv6 in your docker *and* host to see
> 
> [aircast-linux-x64.zip](https://github.com/philippe44/AirConnect/files/12678700/aircast-linux-x64.zip)
> 
> 

How I disable ipv6 on my docker host?

**Comment by philippe44** [comment]
I think that does up to next reboot
```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
```

**Comment by philippe44** [comment]
Same thing, did you see I attached a version?

**Comment by SoCuul** [comment]
[aircast-sep22-1207am.log](https://github.com/philippe44/AirConnect/files/12697768/aircast-sep22-1207am.log)

Here's the updated log with ipv6 disabled.

**Comment by philippe44** [comment]
ahah, can you try the attached files
[bin.zip](https://github.com/philippe44/AirConnect/files/12698299/bin.zip)

**Comment by SoCuul** [comment]
Here you go!
[aircast-sep22-344pm.log](https://github.com/philippe44/AirConnect/files/12704974/aircast-sep22-344pm.log)

**Comment by philippe44** [comment]
There is a routing problem with your box, probably then. Can you try, from within the docker, to ping 192.168.0.113?

**Comment by SoCuul** [comment]
> There is a routing problem with your box, probably then. Can you try, from within the docker, to ping 192.168.0.113?

I've been running all the updated builds (that you attached here) on the bare-metal machine. Nothing has been dockerized.

But if I try pinging them, all three are unreachable, except for the one (Nest Audio) that is working fine with AirConnect.

Now that I know this, do you have an suggestions on how I might be able to fix this? I've confirmed it's nothing to do with the firewall rules as well.

**Comment by philippe44** [comment]
it's an interesting issue ... likely to look around your router or how your network architecture is done

**Comment by SoCuul** [comment]
Oh, I just noticed one key difference between the speakers. The ones that function are connected to the 2.4GHz band, and the ones that are unreachable are on the 5GHz band. I'll see if changing that will fix it.

**Comment by SoCuul** [comment]
Unfortunately, same problem.

**Comment by SoCuul** [comment]
Oh my god, all of this is because months ago I turned on "device isolation" in my router. Turning it off fixed everything!

Thank you so much for all your help troubleshooting haha.

**Comment by philippe44** [comment]
Still glad we sorted it out and I improved my logs a bit, so all good 😄
