### ISSUE TITLE
Sonos Play3 paired as Stereo ist not discoverd by airconnect 

### ISSUE THREAD

**Issue by Spy-1** [philippe44/AirConnect#488]
My Sonos Play3 paired as Stereo are not discoverd by airconnect.
Changing from - flac to - wav did no changes.
What can i do?

**Comment by philippe44** [comment]
Post a log to start with

**Comment by Spy-1** [comment]
Thank you for your Help.
The missing Play3 are on 192.168.178.28 and .29. Theire name is Sonos-Play3-Kueche-li and Sonos-Play3-Kueche-re.
Here is the log:
[airconnect.log](https://github.com/philippe44/AirConnect/files/12708332/airconnect.log)

**Comment by philippe44** [comment]
It's a very long log with a lot of history. Did it ever work? I've just tried on a group with a Play:5 and a Play:3 and it worked as expected. Anything special in your network infrastructure?

**Comment by Spy-1** [comment]
Yes, it has worked before (because of this i send a "long" Log).

But now I got it working again after resetting all my Sonos speakers and reinstalling airconnect several times. 
Verry Curious!

**Comment by philippe44** [comment]
good then - can we close this issue?
