### ISSUE TITLE
BOSE SoundTouch (not an issue - just an information)

### ISSUE THREAD

**Issue by chpusch** [philippe44/AirConnect#49]
Thanks for the awesome software! Just wanted to inform you, that is working like a charm with my bose SoundTouch devices. Maybe something you can add to the overall information. It seems that a lot of SoundTouch users are searching for such an solution. Regards, christian

**Comment by marco79cgn** [comment]
You mean you get the Bose Soundtouch (e.g. Soundtouch 10) speaker as AirPlay targets? Sounds awesome! Does this also work flawless with groups?

**Comment by chpusch** [comment]
Hi, yes I get every bose SoundTouch as an airplay device (Bose SoundTouch 10 & bose SoundTouch connect). 

I have tried the groups via the bose SoundTouch app and it worked. Initially I streamed to one speaker via airplay and group them in the SoundTouch app.

**Comment by philippe44** [comment]
Thanks, I've added the information to the readme
