### ISSUE TITLE
Allow for not appending '+' to the name of clients

### ISSUE THREAD

**Issue by sidevesh** [philippe44/AirConnect#493]

**Comment by philippe44** [comment]
you can create a config file and there you name each player how you want

**Comment by sidevesh** [comment]
yeah, but it would be helpful to disable the appending of '+' to the name behavior globally,
if you think this makes sense then I can add an attribute on the common section of config to disable that behavior and send a PR.

Thanks btw for your project, has been working great with my MacBook!

**Comment by philippe44** [comment]
ok, I've added something very simple using '-N' (no config file equivalent) where you can use a C string format %s to do a bit of transformation. Yes, it can be dangerous and no it's not a public API so it's not a big danger and no I'm not going to add a regex :smile:

**Comment by sidevesh** [comment]
cool cool, can you give me an example usage I will try it out ?

**Comment by philippe44** [comment]
like -N "I-don-t-like-the-plus-%s-but-I-like-this"

**Comment by sidevesh** [comment]
Is -N available on the latest release ? Trying to use -N just prints help

**Comment by sidevesh** [comment]
Ah I see you pushed it it the 1.3.0 commits

**Comment by sidevesh** [comment]
This does not seem to work for me, if I use `-N "%s"` then I get some JSON stringified as the name of the AirPlay speakers rather

**Comment by MKReyesH** [comment]
> This does not seem to work for me, if I use `-N "%s"` then I get some JSON stringified as the name of the AirPlay speakers rather

I have tried the same and it is not working for me neither
<img width="368" alt="Captura de pantalla 2024-01-22 a las 17 35 09" src="https://github.com/philippe44/AirConnect/assets/33583170/d6f9a402-34c4-450f-afa1-aa68212ca64a">
