### ISSUE TITLE
How I can use this in conjunction with multi-speaker listening? 

### ISSUE THREAD

**Issue by grandencrypted** [philippe44/AirConnect#496]
Am I missing something, or is that not supported yet?

**Comment by philippe44** [comment]
I don't understand the question: is this for the chromecast or upnp version? For CC, it works but the group has to be formed using the Google controller and UPnP, by standard, does *NOT* have support for groups. Only Sonos does and Sonos is supported, as an exception.

**Comment by grandencrypted** [comment]
Chromecast. When I try to play a chromecast speaker via airplay via your program paired with another airplay enabled device, i can't play audio over both at the same time like can I can with my Sonos, Roku, or BluOS enabled amplifier .

**Comment by philippe44** [comment]
you're welcome
