### ISSUE TITLE
running from command line works as expected but running as a service doesnt

### ISSUE THREAD

**Issue by jowtron** [philippe44/AirConnect#497]
running:
 /var/lib/airconnect/airupnp-linux-arm-static -l 1000:2000 -z -x /var/lib/airconnect/airupnp.xml
works as expected

but running as a systems service results in it starting and being deactivated instantly.
Oct 21 11:37:09 PiZero2w systemd[1]: Started airupnp.service - AirUPnP bridge.
Oct 21 11:37:09 PiZero2w airupnp-linux-arm-static[9951]: [11:37:09.297] main:1378 Starting airupnp version: v1.3.0 (Oct 14 2023 @ 00:21:30)
Oct 21 11:37:09 PiZero2w systemd[1]: airupnp.service: Deactivated successfully.

**Comment by jowtron** [comment]
my airupnp.service file is as follows and I'm running it on the dietpi distro

[Unit]
Description=AirUPnP bridge
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/var/lib/airconnect/airupnp-linux-arm-static -l 1000:2000 -z -x /var/lib/airconnect/airupnp.xml
Restart=on-failure
RestartSec=30

[Install]
WantedBy=multi-user.target

**Comment by philippe44** [comment]
it's -Z man, not -z 😄

**Comment by jowtron** [comment]
Ahh! Thankyou!!
