### ISSUE TITLE
Health check support

### ISSUE THREAD

**Issue by sidevesh** [philippe44/AirConnect#498]
Would it be possible to add, if its not already possible somehow, a simple healthcheck endpoint to this so that it can be monitored from within container for example ?

**Comment by philippe44** [comment]
What type of check would you consider? Because you can verify that it did not crash and that's pretty much most you should do. Otherwise, you could on the fly check the log for some specific things you'd like.

**Comment by sidevesh** [comment]
Anything compatible with https://docs.docker.com/engine/reference/builder/#healthcheck

Is there an existing command that can be used to check if airconnect is working okay or an endpoint to curl and get a success reaponse from maybe ?
