### ISSUE TITLE
Unable to start application on Mac

### ISSUE THREAD

**Issue by 01qwasa10** [philippe44/AirConnect#501]
System Version: macOS Sonoma
Environment: Mac Mini with M2
App Version: aircast-macos-arm64-static 1.3.1

I was not able to start the service at all after multiple attempts and also rebooting the system. Firewall is off, Google Nest Audio behaving normally. Could not figue out the issue by myself therefore come here and ask for help. Thx. 
Aircast did function smoothly till yesterday.
![Screenshot 2023-11-13 at 22 44 08](https://github.com/philippe44/AirConnect/assets/61235151/73bfbc15-71af-40e2-8205-29d6963252a2)

**Comment by philippe44** [comment]
It is still starting normally but it does not find any device. It's an issue with your network were now device can't be discovered anymore (multicast response blocked? NAT? new or updated router?). Something has changed there.

**Comment by philippe44** [comment]
Closed to inactivity
