### ISSUE TITLE
Can somebody help me please on osx

### ISSUE THREAD

**Issue by rolandoloera** [philippe44/AirConnect#512]
when i run it it show me error Abort trap: 6 :(

detail:

**MacMini:~ loera$ /Applications/aircast-osx-multi ; exit;
[16:46:52.242] main:948 Starting aircast version: v1.6.1 (Dec 25 2023 @ 23:20:04)
[16:46:52.243] main:955 no config file, using defaults
[16:46:52.243] Start:708 Binding to 192.168.2.70 [en1] with mask 0xffffff00
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Proceso completado]**

**Comment by philippe44** [comment]
Try the static version

**Comment by rolandoloera** [comment]
thank you :) but when I try to open it "aircast-macos-x86_64-static" it open with TextEdit OSX app and not with terminal app it's strange, ¿can i use a command from terminal to open it?

**Comment by rolandoloera** [comment]
> Try the static version

static version works like a charm for me many thanks for your effort coding :)
