### ISSUE TITLE
Windows Identifying AirConnectUPNP as a virus

### ISSUE THREAD

**Issue by CDeLeon94** [philippe44/AirConnect#515]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FBearfoos.A!ml&threatid=2147731250

**Comment by CDeLeon94** [comment]
Launched application and it appeared to work for a minute, before it closed and the exe was quarnateened by windows security

**Comment by philippe44** [comment]
it's Trojan:Win32/Bearfoos.A!ml, so !ml means it's added by machine learning. No idea why, likely a false positive
