### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by ghost** [philippe44/AirConnect#518]
deleted

**Comment by philippe44** [comment]
It's a single zip now

**Comment by gabrieluggla** [comment]
Still can't get it to work. What would the URL be in my case using Terminal?

**Comment by philippe44** [comment]
bro, it's in the first chapter of the README (Installing) and the name of the file in rig he there on the GitHub page...

**Comment by gabrieluggla** [comment]
Still 404. This is what I'm trying:

wget https://raw.githubusercontent.com/philippe44/AirConnect/master/airconnect-aircast-linux-armv6.zip

Can you please tell me what I'm doing wrong?

**Comment by philippe44** [comment]
Look at the README, it's a one file that you can simply see on the UI in GitHub. You download the WHOLE file and then you extract / unzip what you AFTER you downloaded the big zip.

**Comment by gabrieluggla** [comment]
But I want to download it using Terminal. Why is it so hard for you to explain?

**Comment by pwt** [comment]
Something like:
```
VERSION=1.7.0
wget https://github.com/philippe44/AirConnect/releases/download/${VERSION}/AirConnect-${VERSION}.zip && \
    unzip AirConnect-${VERSION}.zip aircast-linux-armv6 && \
    rm AirConnect-${VERSION}.zip
```

**Comment by ALaDoffe** [comment]
Hi 

If you want the latest version :

``sudo wget https://github.com/philippe44/AirConnect/raw/master/AirConnect-1.8.1.zip``

**Comment by gabrieluggla** [comment]
> Hi
> 
> If you want the latest version :
> 
> `sudo wget https://github.com/philippe44/AirConnect/raw/master/AirConnect-1.8.1.zip`

Finally, THANK YOU!
