### ISSUE TITLE
SSL problem with Raspberry Pi 5

### ISSUE THREAD

**Issue by StargateSGx1** [philippe44/AirConnect#522]
I tried to install Airconnect on my Raspberry Pi5 with Raspberry Pi Os Lite (64bit)
I used the airupnnp-linux-aarch64 binary but on startup i get the error: Start:1111 Cannot load SSL libraries
I have installed OpenSSL 3.0.11 on my Pi.

**Comment by philippe44** [comment]
You need to install openssl 1.x. I assume you latest distribution only has 3.x. I can't remember the exact command but it's apt-get install openssl<something,something>

**Comment by StargateSGx1** [comment]
Hi,

ok its now working.
I have  installed libssl via dpkg:
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1n-0+deb11u5_arm64.deb
sudo dpkg -i libssl1.1_1.1.1n-0+deb11u5_arm64.deb
