### ISSUE TITLE
CPU load on Ubuntu LTS 24.04 and RPi5

### ISSUE THREAD

**Issue by DoWenzl94** [philippe44/AirConnect#529]
Hi, I've been having some trouble since I migrated my system to a RPi5. The airupnp-linux-armv6-static doesn't work anymore and shows a CPU load of 100% on all cores. The airupnp-linux-aarch64-static works, but it also has a CPU load of 100% on one core. Do you have the possibility to check that?

**Comment by philippe44** [comment]
Have another look at the README, you likely have an error in the command line

**Comment by DoWenzl94** [comment]
your right, my bad!
