### ISSUE TITLE
Start:735 Starting pico HTTP server on port 38617

### ISSUE THREAD

**Issue by threepoint2** [philippe44/AirConnect#538]
Arch Linux.
When running 
I get the following: then it just stops (different port every time) - any ideas what to check next?

> [blasterdroid@blasterdroid-desktop AirConnect-1.8.3]$ sudo ./aircast-linux-x86_64 l 1000:2000
> [19:33:04.458] main:952 Starting aircast version: v1.8.3 (Feb  1 2024 @ 01:10:52)
> [19:33:04.458] main:959 no config file, using defaults
> [19:33:04.459] Start:709 Binding to 192.168.1.21 [enp2s0] with mask 0xffffff00
> [19:33:04.463] Start:735 Starting pico HTTP server on port 38617

Thanks in advance.

**Comment by philippe44** [comment]
What are you trying to use in term of device?

**Comment by threepoint2** [comment]
Running airconnect on arch linux to for the purpose of streaming to sonos speakers. I've had this working on windows fine but on linux is just stops at the starting pico http server line with no obvious error. Does it log anywhere I can check?

**Comment by philippe44** [comment]
oh, you are running AIRCAST which is for ChromeCast, you must run AIRUPNP

**Comment by threepoint2** [comment]
It's working fine now, just needed to run AIRUPNP; chalk this one up to user error. marking the issue as solved. thank you for your help :)
