### ISSUE TITLE
UPnP will not start on Mac

### ISSUE THREAD

**Issue by mfreudenstein** [philippe44/AirConnect#57]
Hi philippe44, hoping you might be able to assist. I followed your instructions, but when I run the executable, I am getting the attached message. Am I missing something?
<img width="682" alt="screenshot 2018-02-27 23 18 18" src="https://user-images.githubusercontent.com/36899670/36770500-87fc0332-1c18-11e8-9bcf-238c1e6b5046.png">

**Comment by philippe44** [comment]
You might have more than one network interface on your mac and the wrong one is picked. Try using the -b option on the command line once you know your IP address. There might as well have a issue with firewall

**Comment by seanchs** [comment]
Hi there,

I want to say Thank You for this great tool. Apologize for any confusion. I
was trying to install it on my Raspberry Pi 3 but I am not very technique
savvy.

I already run following command on Raspberry Pi3: wget
https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-arm

But I don't know what to do next?

Thanks a million,

Sean

**Comment by mfreudenstein** [comment]
What do you mean by -b option? What would that look like? Sorry, not a coder...

**Comment by philippe44** [comment]
Look at the command line by typing ./airupnp-arm -h. It will give you all the syntax of what you can add as options. So for example, you can do ./airupnp-arm -l 1000:2000 -b 192.168.2.10 is 192.168.2.10 is the IP address of you machine 
Or look st the README and generate a config file, you find the explanations how to add the IP address to be used in this config fil#

**Comment by philippe44** [comment]
closed for inactivity (2 weeks)
