### ISSUE TITLE
How to install it on Raspberry Pi 3? 

### ISSUE THREAD

**Issue by seanchs** [philippe44/AirConnect#58]
Hi there,

I want to say Thank You for this great tool. Apologize for any confusion. I was trying to install it on my Raspberry Pi 3 but I am not very technical savvy.

I already run following command on Raspberry Pi3: 
wget https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-arm

But I don't know what to do next? Anyway to share step-by-step guidance? 

Thanks a million,

Sean

**Comment by vladserkoff** [comment]
Follow these steps: https://github.com/philippe44/AirConnect#running, just substitute `airupnp-osx-multi` with `airupnp-arm`

**Comment by seanchs** [comment]
_
