### ISSUE TITLE
Default groupings

### ISSUE THREAD

**Issue by bdormael** [philippe44/AirConnect#60]
Hi,

Maybe I didn't search very well, but I couldn't find it back, not really an issue but more kind of feature request:

- Is it possible to preconfigure groups for my Sonos speakers in the config file ?

Eg. via Apple Music I want to be able to select a speakerset which includes Living & Diningroom already grouped together without going to the Sonos app and group there first and then select the master in Apple Music.

Thx for the great app, using it daily

Benny

**Comment by philippe44** [comment]
You can't create the group from AirConnect. Now, if the set is already grouped, only the master will appear. as an airPlay target. If you break it up, former slaves will re-appear and if you reform the (or another) group, then slaves will be removed

**Comment by philippe44** [comment]
closed for inactivity
