### ISSUE TITLE
Severe stuttering with "roon" radio and shuffle

### ISSUE THREAD

**Issue by tokenviking** [philippe44/AirConnect#61]
Hi Philippe,

I am using aircast-win.exe v 0.2.0.4 on a Windows 10 lap top. But I had the same problem with 0.2.0.1.

With the roon "radio" or "shuffling" features I am having problems with very serious stuttering when the queue changes from one sample rate to another. For example, from 44.1khz to 96khz. By default roon is set set up to down sample everything to 44.1 khz to comply with airplay limitations.

I have tried playing around with latency settings. For example 1000:1000, 1000:2000, 2000:3000. But there is no change in behavior and the lag between tracks becomes very long so I have reverted to the default settings.

Is there a configuration option I could try or is this a fixable problem for a future release?

Many Thanks,
Tony

**Comment by philippe44** [comment]
I'm not sure I'm following: doesn't Roon support directly Chromecast?

**Comment by tokenviking** [comment]
Hi Phillipe,
No. Roon does not support Chromecast at all. It has been on their roadmap since September 2015:
https://community.roonlabs.com/t/chromecast-audio-as-endpoint-on-roadmap/3981

Roon have an issue with UPnP which they will not support so one result is no support for Chromecast. There is a lot  of demand for this, so many have started experimenting with your airplay driver.
In this use case, some with multiple CC's reporting stability issues (see the thread above). I have a much simpler use case. A single zone in a travel scenario where I want to maintain a roon library on a work laptop but output to any available device in a hotel room. Typically that will be a flat screen TV.
Provided all my files are a uniform sample rate I don't seem to have a problem. But in a travel scenario I have quite a mixture. I am downloading files, some I have queued to down sample to MP3 but haven't gotten around to it yet. Sometimes I have ripped CD's I have found in a second hand store not available in my home town. The end result is I have quite a mixture that I want to queue on radio or shuffle.
I hope you can help. There are a lot of frustrated roon users who would greatly appreciate your fantastic solution!.
Many Thanks,Tony  
_______________________________________
Tony Casey
Nordre Frihavnsgade , 94, 1. th.DK-2100 København ØDenmark

Mob +45 91 11 24 45 (Current)Mob +353 (0)87 931 8941
tony_casey@yahoo.com

**Comment by philippe44** [comment]
I see - I did thought that Roon started to support CC a while ago. 

So, I'd need a log of what happening during track change. Normally, Roon should stream a continuous flow of AirPlay audio, but it might be that they don't and do something funny during track change. 

AirCast does work if you teardown and re-establish AirPlay sessions continuously, but problem might happen if the AirPlay source leave the stream "open" but does not send audio anymore (it should not do that). Normally, I insert silent frames in this case, but it's not the most tested use case for obvious reasons

**Comment by tokenviking** [comment]
What you ate describing is what I see. If I am quick during track change and pause roon off/on then a lot of the time airplay just continues normally.  Otherwise, aircast will crash.

I can get you some logs but I am not a very technical person. Do you mean the roon logs or the aircast logs, or both? I can figure out how to get the roon logs but with aircast is their a switch or something to create a log file?

**Comment by philippe44** [comment]
Are you sure the app is crashing? The way to get a log is pretty simple: add '-x log.txt' to the command line. it will create a log.txt file. Do a few test that reproduce the problem and email me the log.txt

**Comment by tokenviking** [comment]
Hi Phillippe,

Here is a link to a roon log. I used a playlist where you can see all behaviors on track changes. Sometimes they work. Sometimes they don't. The pattern with the stuttering seems to be changes in sample rate. What I do then is pause and restart in roon and then the track continues normally.

https://logitel-my.sharepoint.com/:t:/g/personal/tony_casey_logitel_ie/EUH9TjWubadDrtzA_ipzEo4B7IG0RZQ6Goy5IKzffZxmsw?e=APfZo3

Let me know if you need the aircast logs as well. I will try and figure out how to do that.

Tony

**Comment by tokenviking** [comment]
I just saw your message now. I will play the same playlist and make the aircast logs.

On the crashing. If I just leave it to play with the stuttering I am not seeing aircast crash. It is when I pause and restart roon too many times then I will see an error message from windows and it forcibly shuts down aircast.

**Comment by tokenviking** [comment]
Hi Philipe,

I cannot create an aircast log. The command I am using is:

aircast-win.exe -x log.txt

No log is being created in the aircast directory.

What I am doing is:

1. aircast-win.exe -x log.txt
2. Start roon.
3. Start playlist (with mixture of different sample rate files).
4. Let roon play for a while to replicate behavior.
5. Pause roon play.
6. Before I have a chance to type "exit" on the cmd prompt aircast console, aircast crashes with a windows error message "something has gone wrong . . .", and then windows closes down aircast.
7. No log is written to log.txt. Maybe because aircast has been closed by windows before it has a chance? 

What I can do is I cut and past the cmd console messages where the stuttering behavior occurs.

https://logitel-my.sharepoint.com/:t:/g/personal/tony_casey_logitel_ie/EYqwqpMbUEtJlpVBxruwqqsBN1mCqTwclw-S8jiRXNjtpA?e=xeznPd

Maybe you can use this? If not, please advise how I can make a log.txt file and I will try again.

Many thanks,
Tony

**Comment by philippe44** [comment]
Oh I'm sorry this is -f log.txt

**Comment by tokenviking** [comment]
Hi Philippe,

Here is a link to a log. I used a playlist exhibiting the behaviour.  When stuttering started usually at a track change to a different sample rate I just paused/restart in roon so that play continued normally.

https://logitel-my.sharepoint.com/:t:/g/personal/tony_casey_logitel_ie/EZ7h9C2ANvlPra_jmD9C4A8BroKl36vynwnaSVR4628gnw?e=IQSric

Thanks,
Tony

**Comment by philippe44** [comment]
Can't see anything significant. I guess I'll have to resubscribe to roon

**Comment by tokenviking** [comment]
Ok. Good luck. Hope it's nothing that needs fixing at the roon end!

**Comment by philippe44** [comment]
I think I've found the issu with Roon and corrected it in 0.2.0.5. It's working fine on my configuration now

**Comment by tokenviking** [comment]
Ok Philippe. That's great. I am in travelling at the moment. I will test with my system and let you know how I get on. _______________________________________
Tony Casey
Nordre Frihavnsgade , 94, 1. th.DK-2100 København ØDenmark

Mob +45 91 11 24 45 (Current)Mob +353 (0)87 931 8941
tony_casey@yahoo.com

**Comment by tokenviking** [comment]
Hi Philippe,

Just to confirm, 0.2.0.5 seems to be working with every combination of sample rates I have tried. Sorry I could not confirm earlier. Many thanks for this! Much appreciated.

Tony

**Comment by philippe44** [comment]
Thanks - can we close this item?

**Comment by tokenviking** [comment]
Hi Philippe. Yes can close. Good work. Many thanks again. 

    On Wednesday, 21 March 2018, 19:48:43 CET, philippe44 <notifications@github.com> wrote:  
 
 
Thanks - can we close this item?
