### ISSUE TITLE
Sonos disappears regularly

### ISSUE THREAD

**Issue by persi-persu** [philippe44/AirConnect#62]
Hello,
I have disconnection problems with a pair of Sonos PLAY: 1 in stereo mode and AirUPnP on Windows / macOS. My AirPlay source is a Mac. I do not know if it's because of my network, my router is an Asus RT-AC68U. I use the recommended settings for Sonos on AirUPnP and my router. All the software is up to date and the speakers work great for other things. There is no need for my Mac to connect by Airplay for problems to appear. However, if my Mac is not turned on, there does not seem to be any.

Here are some logs: https://gist.github.com/anonymous/4f4c85c9edeae2607808191fbd387ac5

**Comment by philippe44** [comment]
Unfortunately it's clear in the log that for 6 times in a row, the PLAY:1 does not respond to the UPnP discovery (6*20s = 2mins). I'm suspecting that your router or something else in your network filters out the UPnP discovery request

**Comment by persi-persu** [comment]
Thank you, it was apparently my router. For those who have the same problem, you have to login by ssh and run `echo 0 > /sys/class/net/br0/bridge/multicast_snooping` but it does not stay after a reboot. For that, it takes more work.
