### ISSUE TITLE
Device discovery and dual band router

### ISSUE THREAD

**Issue by prrrnd** [philippe44/AirConnect#63]
Hello,

I have a dual band router, on which a Sonos One is connected to the 2.4GHz band and my computer to the 5GHz one.
Everything works as expected when the speaker and my computer are on the same band (2.4GHz), but it simply can't find the speaker when the computer is on the 5GHz band. (The Sonos One can only use the 2.4GHz or ethernet).
Any idea regarding what could be the cause? I have tried playing around with the `-b` option, but without any success.

My end goal would be to use a Raspberry Pi (wired, ethernet) with the Sonos One(wireless, 2.4GHz).

Cheers, and thanks for maintaining this project 👍

**Comment by philippe44** [comment]
You’re probably missing a configuration in your router that allows the two networks to be bridged, or to allow multicast to go between

**Comment by philippe44** [comment]
closed for inactivity
