### ISSUE TITLE
Google Cast Targets Disappearing

### ISSUE THREAD

**Issue by cgarst** [philippe44/AirConnect#67]
Hi, wonderful tool! I'm having a bit of an issue with some devices disappearing. I have the Google Wifi mesh system which doesn't have much tinkering ability, so I'm hoping I can find a more direct workaround than the recommended router multicast tweak. They'll pop back in for a bit if I power cycle those devices. Of my 10 Google cast targets, 3 of them are intermittently taken out of AirConnect as so:

`[11:38:34.101479] mDNSsearchCallback:418 [0x787a8]: removing renderer (Office Speaker+) 3`

Here's another logged case ran with `./aircast-arm -d all=debug -f logfile`. If I can somehow log more information about the expiration please let me know.

[12:33:44.740682] mDNSsearchCallback:365 ----------------- round ------------------
[12:33:44.740890] mDNSsearchCallback:369 [ACTIVE] host 192.168.86.22, srv 192.168.86.22, name Google-Cast-Group-810d9c4eb14b4a0eb4bff45d171bc6c1._googlecast._tcp.local
[12:33:44.740974] UpdateCastDevice:468 [0x7500eb00]: changed ip:port 192.168.86.22:42275
[12:34:59.974663] mDNSsearchCallback:365 ----------------- round ------------------
[12:34:59.974881] mDNSsearchCallback:369 [EXPIRED] host 192.168.86.27, srv 192.168.86.27, name Google-Cast-Group-810d9c4eb14b4a0eb4bff45d171bc6c1-1._googlecast._tcp.local
[12:37:39.129885] mDNSsearchCallback:365 ----------------- round ------------------
[12:37:39.130093] mDNSsearchCallback:369 [ACTIVE] host 192.168.86.27, srv 192.168.86.27, name Google-Cast-Group-810d9c4eb14b4a0eb4bff45d171bc6c1-1._googlecast._tcp.local
[12:37:39.130230] UpdateCastDevice:468 [0x7500eb00]: changed ip:port 192.168.86.27:42275
[12:37:40.137304] mDNSsearchCallback:365 ----------------- round ------------------
[12:37:40.137487] mDNSsearchCallback:369 [EXPIRED] host 192.168.86.22, srv 192.168.86.22, name Google-Cast-Group-810d9c4eb14b4a0eb4bff45d171bc6c1._googlecast._tcp.local

**Comment by philippe44** [comment]
Difficult to say - expired really happens when a device has not sent its mDNS keep-alive message and as not either responsed to the regular (every 20 seconds) queries. When they dissappear, they never come back unless you power cycle them? Are these the same 3 that always cause the issue? If yes, any idea of the active topology they use

**Comment by cgarst** [comment]
They do come back after a long while. It's not the same devices missing each time, but randomly 2 or 3 of the 10 targets. When devices are missing with AirConnect, I've noticed they're still available as cast targets in the Google Play Music iOS app.

I did manage to capture a config.xml with all devices present, is running AirConnect with that supposed to affect expiration at all?

**Comment by philippe44** [comment]
No, the config file with all devices present does not affect airconnect. The config files does not force device creation but it just tells airconnect what paramaters to use when a device with a know id is discovered. Other application might choose to keep unresponsive devices for a longer time (did you try to see what happens with these when you unplug the device). I choose to remove them when they fail to update their presence at the time they said they would. But then a search is made pretty often and a device that has just 'disappeared' is brought back immediately if he responds. There is no 'penalty box'. When you say they come back after a long while, can you be more specific: how long?

**Comment by cgarst** [comment]
It seems it's several hours before devices come back. Last night I was missing 3 devices which were back this morning. Now I'm down 6 devices at the moment. They don't appear when restarting AirConnect of course, so wondering what's going on with their mDNS.

Regarding what happens in Google Play Music when I unplug the device, it seems to go off the list after about 1 minute.

**Comment by philippe44** [comment]
If they do not appear after restarting AirConnect, at least that points really much more to a networking issue, where these requests/responses are being filtered out.

Maybe Google play music keeps an open SSL connection with all players and mark them missing when such connection fails. I used to do that but I don't think that is a viable option for a system which is supposed to be idle & waiting for most of its time - I thought that if every background controller would do the same, it would be bad for the Cast device. I assumed it might make sense if you're an application like play music and you're ... well I don't know.

Do you have any wayt to test without using the Google WiFi Mesh?

**Comment by cgarst** [comment]
Thanks for all the info. I reset the entire mesh yesterday morning and haven't had a disappearance yet. Let me see how long this holds. I may try that Avahi version. I'll continue testing and If I find a general suggestion for using AirConnect Google Wifi that may help others I'll report back.
