### ISSUE TITLE
Still a noticeable delay macbook pro high sierra

### ISSUE THREAD

**Issue by LocDaiNguyen** [philippe44/AirConnect#69]
After getting everything to work and running this command `./airupnp-osx-multi -l 1000:2000` I still get a noticeable delay. Video and audio from sonos is off 1-2s.

**Comment by philippe44** [comment]
The audio delay cannot be managed/controlled due to the nature of the proxy. One side is RTP, the other side is HTTP with no parameter to control playback timing/delay. It's independant of the latency parameters. I've updated the README to make that a clear statement.

**Comment by philippe44** [comment]
Closed for inactivity
