### ISSUE TITLE
Right way to run on Raspberry Pi startup

### ISSUE THREAD

**Issue by rkpatel33** [philippe44/AirConnect#7]
Do you have a suggestion on how to properly startup `bin/airupnp-arm` after the PI boots?

I currently have this line (which works when I run it from a terminal) in my `/etc/rc.local` file:

```
/absolute/path/to/repos/AirConnect/bin/airupnp-arm -l 1000:2000 -z &
```

I have made the file executable with `chmod +x` and confirmed it runs properly when I run it manually, however, it does not seem to run on startup. There is also no process running when I try `ps aux | grep airupnp`. I find it strange since this is the same place I run `airsonos` from as well.

I thought maybe its because the network is not setup yet, so was considering putting  a script in `/etc/network/if-up.d/` but have not tried it yet.

Thx.

**Comment by rkpatel33** [comment]
My apologies, this seems to be working ok. Not sure what was going on before.

**Comment by b099l3** [comment]
I was having a similar problem tried:

- a script in `rc.local`
- a script in `/etc/xdg/lxsession/LXDE-pi/autostart`
- a service that waits till the network is up in `/etc/init.d/`

Moved to adding a cronjob with `@reboot` and piping it to a log file where I seen this:

> [23:18:06.888702] main:1187 Starting airupnp version: v0.1.2.0 (Nov 20 2017 @ 12:11:45)
> [23:18:06.889019] main:1195 no config file, using defaults
> [23:18:06.897017] Start:961 UPnP init failed: -208
> 
> [23:18:06.897116] main:1220 Cannot start UPnP
> [23:18:06.897145] main:1279 stopping squeelite devices ...
> [23:18:06.897166] main:1280 stopping UPnP devices ...
> [23:18:06.897186] Stop:1006 terminate search thread ...
> [23:18:06.897207] Stop:1009 flush renderers ...
> [23:18:06.897234] Stop:1012 terminate main thread ...
> [23:18:06.897257] main:1282 all done

So I'm guessing something is not ready yet for the UPnP. So for a quick workaround I just added a delay at the start of the cronjob like this:
`@reboot sleep 60; sh /home/pi/startup.sh >/home/pi/Logs/cronlog 2>&1` and it seems to work now.

just added the cronjob with : `sudo crontab -e`
and this is in my startup.sh:
`/home/pi/airupnp-arm -l 1000:2000`

**Comment by philippe44** [comment]
See updated README for a systemd unit example
