### ISSUE TITLE
Different issues on Pi Zero W

### ISSUE THREAD

**Issue by levithan88** [philippe44/AirConnect#75]
I am quite new to linux so maybe I am doing something essentially wrong:
I tried to run airupnp-arm on my Pi Zero W.

After updating und upgrading and updating the FW to 4.14.34+ (armv61) and installing the openssl from your link and downloading the airupnp-arm into the /var/lib/airconnect folder I tried to start the programm in different ways. (I also used the chmod +x thing)

Clicking on it asks whether I would like to execute or execute in terminal - nothing happens.
using ./airupnp-arm in the directory in terminal says "illegal instruction"
same with root rights (sudo su)
I tried ./airupnp-arm & but it only gives me "[1] 942" as an answer
I tried vi airupnp-arm and it says "airupnp-arm" [readonly][incomplete last line][converted] 6027 lines, 614701 characters. Press ENTER or type command to continue 
I press Enter and many blue @^ and some letters appear, seems crushed.

Is it possible that the programm will not run on my Rpi Zero W?

**Comment by philippe44** [comment]
I don't have a piZero but it should work.  Don't try to edit a binary file, nothing good will come out of that.. Still, the reported size is strange astht efile is ~400k. The x86, bsd and windows version are ~600k. If you do, in that directory type "ls -l", what is the size of the airupnp-arm? Wat do you get if you type "readelf -A airupnp-arm".

**Comment by levithan88** [comment]
"ls -l" says:
total 416
-rwxr-xr-x 1 root root 424260 Apr 20 00:12 airupnp-arm

"readelf -A airupnp-arm" says (I leave the Tags before the : ):
"6J"
v6
Yes
Thumb-1
VFPv2
4
Needed
Needed
Needed
IEEE 754
8-byte
8byte, except leaf SP
int
Deprecated
VFP registers
v6

Somwhere I read, that those "illegal instructions" accur when you try to use an newer package on an older processor... Pi Zero uses Armv6 and the others v7 i guess...

**Comment by philippe44** [comment]
Should not been needed, but have you tried the arm5 version?

**Comment by levithan88** [comment]
Jup tried that right away with same "illegal instruction" outcome... In 2 weeks or so I can try it on an Rpi3, maybe I am doing something wrong (really new to linux) - but I did it step by step a few times from scratch now (with raspian and raspian lite).

**Comment by philippe44** [comment]
I found an A+ on my shelves and it worked (it's supposed to be the same processor as Zero, a BCM2835). It's running jessie

**Comment by mcolyer** [comment]
> I found an A+ on my shelves and it worked (it's supposed to be the same processor as Zero, a BCM2835). It's running jessie

Weird, I just tried the airupnp-arm5 on my BCM2835 (Raspberry Pi Model B) and I'm getting an illegal instruction message as well. Running with strace I get this:

```
set_tid_address(0xb6ef6278)             = 1357
set_robust_list(0xb6ef6280, 12)         = 0
rt_sigaction(SIGRTMIN, {sa_handler=0xb6e972b0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0xb6b686c0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0xb6e97390, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0xb6b686c0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
ugetrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0xb6d65b30} ---
+++ killed by SIGILL +++
Illegal instruction
```
@philippe44 anything else I can do to debug?

**Comment by mcolyer** [comment]
So I figured out the issue. The README mentions install libssl from a regular debian mirror. If you follow those instructions on an older raspberry pi it doesn't work out well. The link you want instead is http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb, which will provide a version of libssl1.0.0 that isn't arm7.

**Comment by philippe44** [comment]
Good - But where you using stretch on these 2 boards?

**Comment by levithan88** [comment]
Thanks a lot! I got it running and even the airconnect.service works after a few permission-problems etc.

Now I can use the very small and energy-saving Pi Zero W as Service for Sonos :) hope it will keep working 24/7 from now on! So the different link for libssl was the problem...

**Comment by philippe44** [comment]
Thanks - I've updated the README.

Let the service ownership be root. TO edit it, just do 'sudo vi airconnect.service'. When you change back ownership, are you sure it worked. What does 'ls -l' say?

**Comment by levithan88** [comment]
in the directory "ls -l" says
total 64
- rw------ 1 root root 266 Apr 22 22:32 airconnect.service
and many more

so I guess it belongs to root now. still when i start the service an extra window pops up - a real desktop window to provide the password. when I type raspberry it starts just fine - but on bootup thats a problem.

**Comment by philippe44** [comment]
My services mode are 644 (rw-r--r--) but I don't think it matters for that purpose. Can you copy the exact content of your file? Do you use sudo when you startup manually?

**Comment by philippe44** [comment]
Closed for inactivity
