### ISSUE TITLE
logfile error in airupnp.c

### ISSUE THREAD

**Issue by JFdeB** [philippe44/AirConnect#80]
Dear Philippe, Awesome project.
I found a coding error in airupnp.c
line 766 reads: 
if (glLogFile && glLogLimit == - 1) {
I think this needs to be the same as in aircast.c line 506
if (glLogFile && glLogLimit != - 1) {
(note the difference between != - 1 and == -1)
In airupnp.c the logfile is never resized.
Thanks,
JFdeB

**Comment by philippe44** [comment]
Good catch, I've rebuild a new version with the correction

Thank you

**Comment by JFdeB** [comment]
Well ........ :)
Thank You for an awesome project.
Downloaded the rebuild.

On Apr 28, 2018, at 8:05 PM, philippe44 <notifications@github.com<mailto:notifications@github.com>> wrote:


Good catch, I've rebuild a new version with the correction

Thank you
