### ISSUE TITLE
Covers not working

### ISSUE THREAD

**Issue by Jeronimo654** [philippe44/AirConnect#81]
The Chromecast view is showing a black square. Is there a way to get the cover working.

**Comment by Jeronimo654** [comment]
I see. That‘s unfortunate. Would it be possible to add wallpapers or something similar? Flickr, drive album. Something like that

**Comment by philippe44** [comment]
I probably can, but it will remain stack as I don't think why CC would refresh the URL. So if you listen for 2 hours on the same AirPlay "source", coverart will not change

**Comment by Jeronimo654** [comment]
Afaik the CC can interpret HTML5, too. That‘s an approach that could work. A quick google search already gave me a few ideas but unfortunately i don’t have the time atm.

**Comment by philippe44** [comment]
What I can easily do, probably, is add a parameter that points the coverart of the metadata to an URL. I'm not sure this is going to be enough though https://developers.google.com/cast/docs/reference/messages#MediaInformation

**Comment by philippe44** [comment]
I've done that in 0.2.1.0 - you can use parameter <artwork>. In my experience, CC do not accept all image sizes, so mileage will vary

**Comment by philippe44** [comment]
Closed for inactivity
