### ISSUE TITLE
Small glitch

### ISSUE THREAD

**Issue by sschuste** [philippe44/AirConnect#83]
Hi, there is a micro bug in the documentation. It says:

_wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb then install it with sudo dpkg -i libssl1.0.0_1.0.1t-1+deb8u7_armhf.deb_

Download one version but install another? I'm sure you double-checked it five times :-D

**Comment by philippe44** [comment]
Corrected, thanks
