### ISSUE TITLE
Add AppleTV/Appstore Binaries for running on native appletv

### ISSUE THREAD

**Issue by aenertia** [philippe44/AirConnect#84]
Am at inlaws who are Apple ecosystem locked in they have atv (gen2 I think) and I went and bought them a chromecast as they hate the Remote and also chromecast fixing a lot of issues they have.

Whilst they have Mac laptops and I could go that route. It would make more sense to have the daemon running on the always on AppleTV.

**Comment by philippe44** [comment]
I understand but I have no experience developping for iOS and that's probably a lots of effort. The application is made to be multi-platforms, but ATV is probably a different animal in term of minmum requested UI. 
One route you can go is buy a PI (super cheap), hide it somewhere and forget about it

**Comment by aenertia** [comment]
it's just an armhf; IIRC for the older gen atv's 2/3 - at least jailbroken atv's could probably just run the headless daemon which has been compiled for the target  (will require access to a desktop mac with xcode) i.e https://wiki.awkwardtv.org/wiki/Apple_TV_Binaries

**Comment by philippe44** [comment]
My Mac compiler for macOS VM has Xcode on it then I need to figure ou compile options and misc items ...

**Comment by philippe44** [comment]
I mean - you can see my macOS makefile, can propose a few mods to it?

**Comment by aenertia** [comment]
You're a step up on me. I'm a GNU/Linux nerd and know only enough mac environment stuff to be dangerous tbh - and don't generally have an OSX environment at all. Mostly I get angry mapports/fink is hinky and in weird varying levels of support for things I've long taken for granted.

**Comment by philippe44** [comment]
I tried a bit more, some "simple" files compile but some things are missing like openssl that might have been replaced in iOS. It's a bit too much for me to investigate at that time. Maybe somebody reading this ticket will be willing to help

**Comment by j3d1c4nna** [comment]
I think this will not be possible, at least on the 2nd generation AppleTV, as it's totally locked down (it was only the 1st gen that were able to be jailbroken). The only hacking that's ever happened with the gen2 is allowing it to play files from a plex media server, but that involved lots of janky settings tweaks and a program running on your computer which mimics the Trailers app on the AppleTV.

I think any efforts on this front would be better served on the 4th Gen and 4k boxes, which are open for programmers.

Cheers

**Comment by philippe44** [comment]
Closed - will not be done
