### ISSUE TITLE
new airplay devices discovered but impossible to Connect

### ISSUE THREAD

**Issue by tiduch** [philippe44/AirConnect#85]
Hi,

First of all, many thanks for this great project !

I tried to install the package on my synology but it didn't work ( failed to start airupnp on any of the local interfaces, pleaske make sure you have at least one UPnP/Sonos device on your network).
I opened all my rules on the firewall : same result.

Then, I tried on 2 laptops Windows, works directly untill I tried to use my iphone to stream to the new device created. I launch the stream and 10 seconds later, Iphone says impossible to connect.
+ after running the aircast-in.exe for a few minutes, the iphone doesn't find anymore the new devices created.

Can you help?

Many thanks

Note 
I'm using Chromecast Audio (2x)

**Comment by philippe44** [comment]
On Windows, it probably means your firewall is preventing proper streaming. Try to either add aircast-win.exe in the authorized application list or try to fully disable your firewall for a test. Other than that, you can launch it with a log (-f log.txt) and send me the log.txt. 
On the Syno, I'd need to have a log as well. Are you sure you're using the right binary? Synos have all sort of processors

**Comment by tiduch** [comment]
Thanks Philippe for this prompt reply.
I will try that in the coming days !

**Comment by tiduch** [comment]
Please find the Log for the Syno.

Right Binary : I installed with the packages. I tried with the right binary (ARM for my syno).
I also disable the Firewall of the Syno (Should I do it on my router/firewall too?)

![airconnect2 syno 2](https://user-images.githubusercontent.com/39463234/40322663-6547f380-5d33-11e8-9496-d34529e26ef3.jpg)

For the log on Windows, i do not know how to created it. I tried with
 start aircast-win -f log.tx
Not working, start aircast-win works.

thanks

**Comment by philippe44** [comment]
Does this Syno have more than one NIC? On Windows, just open a command line window, go to the directory where the aricast-win is and type "aircast-win -f log.txt"

**Comment by philippe44** [comment]
Then it's a firewall issue or an element of your network between you NAS and the CC that filters out mDNS packet. People usually ask why does this not happen using my Android Phone ? Because it's sitting on the same WiFi network as the CC. Your NAS is reaching your WiFi router through potentially other equipment or the WiFi router filters out some packets between the wired and wireless trunks.

**Comment by tiduch** [comment]
Thanks Philippe,

I tried but didn't find the root cause, I will ask some friend with extra skills on network.

I close for now the ticket.
Thanks
