### ISSUE TITLE
Naming sceme fix/config

### ISSUE THREAD

**Issue by kolobus** [philippe44/AirConnect#86]
Hi.

Is there any chance to config or tune naming of discovered devices? Currently I have 2 Sony TVs of the same model (different size) and they both expose them to airconnect with the exactly same name and with no possibility to guess which one is which.

Thank your for your work!

**Comment by philippe44** [comment]
See the instruction in the README to create a config file. In that file, you can set the name of the player to be anything you want

**Comment by philippe44** [comment]
close for inactivity
