### ISSUE TITLE
heos UPnP support?

### ISSUE THREAD

**Issue by atoudam** [philippe44/AirConnect#87]
Hi, have to say love this app
had been looking for a while for something like this and was about to attempt a build of my own.
one small issue I have is I can't get it working with my Denon Heos UPnp speakers
I have the Heos 1 and Home theatre sound bar.
the app finds both units and advertises them to my airplay devices
I can connect via airplay and adjust the volume (on iPhone) and it causes the volume light to blink on the Heos speaker. I can even playback an audio track and everything looks like its working (the track is playing on iPhone, Stuff is happening in the AirConnect log (no errors) ) the only thing is there is no sound coming out of the speakers. any ideas what this could be? is there any info I can paste here from my setup that would help?. Iv started to dig into the UPnP spec, the Heos spec, and the app to see if I can find what is not lining up (i.e. is the app sending the stream to the wrong address for Heos) however I can't see any simple cause for the issue.

**Comment by philippe44** [comment]
If I remember well, HEOS are not properly compatible with UPnP. There is one small difference in the protocol (I can't remember which one exactly, but I had the issue a while ago with another application I developped)

**Comment by atoudam** [comment]
thanks for your quick response.
so I was playing with it (to get a good amount of info in the log) and I managed to get it to work (sort of)
so I started my music playing on iPhone (sending to Heos1) it was playing but I had no audio as  usual then I went into the Heos app and hit play (why not give it a go)
and the audio started coming out.
so I though "ok I have to hit play in Heos app each time I use AirPlay"
turns out that's not the case as I have tried everything to break it 
stopped/ started Airconnect
started other music / changed input on Heos 
stopped and Started airplay from multiple devices etc
however it continues to work via Airplay everytime, 
it even works now on my other Heos speaker (home cinema) of which I never hit play for on in the Heos app
so support for Heos is 99.9% already in AirConnect, there is just some tiny little piece that Heos needs different  
as soon as I can break it again I will try the "Hit Play in Heos app" fix and keep hold of the log so I can post it here and hopefully be of some help
I'm sure I can get it to break, however in the meantime its working great, thanks for this app 
and hopefully, this info can help others with Heos kit

**Comment by philippe44** [comment]
Closed until you're able to reproduce it
