### ISSUE TITLE
AirPlay 2 support?

### ISSUE THREAD

**Issue by jhurliman** [philippe44/AirConnect#88]
Are there any plans for AirPlay 2 support?

**Comment by philippe44** [comment]
Unfortunately the AirPlay2 specifications are not public, so there is nothing I can do

**Comment by bedwell84** [comment]
:( Do you happen to know how the AirPlay (1) protocol came to be public? Was it always published, leaked, released officially sometime after the original launch..?

**Comment by marco79cgn** [comment]
It was possible with AirPlay 1 because the private key was extracted from an AirPort Express device.
https://news.ycombinator.com/item?id=2431318

**Comment by philippe44** [comment]
CLosed - I may work on that if AirPlay 2 is public one day

**Comment by JayPalm** [comment]
Apple has updated the airport express firmware with Air Play 2, so hopefully the private key will be reverse engineered / discovered soon.

**Comment by jolimk** [comment]
Any advance on this matter?
