### ISSUE TITLE
syntax error near unexpected token

### ISSUE THREAD

**Issue by pablopoo** [philippe44/AirConnect#89]
Hi,
got this message on the latest bin, both on Linux and MacOS:

./airupnp-x86-64: line 7: syntax error near unexpected token `newline'
./airupnp-x86-64: line 7: `<!DOCTYPE html>'

./aircast-osx-multi: line 7: syntax error near unexpected token `newline'
./aircast-osx-multi: line 7: `<!DOCTYPE html>'

Thanks!

**Comment by pablopoo** [comment]
sorry, was an issue with github.

**Comment by gramata** [comment]
Hi, 
I seem to be getting a similar error with the 1.1.0 version for armv6
Downloaded from:
```
sudo wget https://github.com/philippe44/AirConnect/blob/master/bin/aircast-linux-armv6
```

Error:
```
pi@homebridge:/var/lib/airconnect $ ./aircast-linux-armv6
./aircast-linux-armv6: line 8: syntax error near unexpected token `newline'
./aircast-linux-armv6: line 8: `<!DOCTYPE html>'
```

**Comment by philippe44** [comment]
You are not using the right link to download, you are downloading the html page.
