### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by jhurliman** [philippe44/AirConnect#9]
It looks like the code in this repo is licensed under the GPL v3; would you mind adding a license file to the repo to confirm?

**Comment by philippe44** [comment]
I can do the update, but some code (ex alac) is under a different license and there is derivative that I've done from other peices as well under other licenses. My parts are under v3, but I have to say that I did not pay too much attention to that to the (except using only authorized other software). Is there any specific reason why you want me to do that?

**Comment by jhurliman** [comment]
I started on an easy-to-use wrapper app for audio streaming and if I ever finish it, it would be helpful to include the license files of any software that is linked in or packaged with it.

**Comment by philippe44** [comment]
understood, will do

**Comment by philippe44** [comment]
done
