### ISSUE TITLE
Ports 

### ISSUE THREAD

**Issue by PeterVanPan** [philippe44/AirConnect#91]
Hi! 

I'm running AirConnect in a Docker.... 

Here is my docker-compose:
 Airconnect:
    container_name: AirConnect
    restart: unless-stopped
    image: swilsonau/docker-airconnect
    network_mode: "host"
    environment:
      - TZ=${TZ}

It works perfect... if ufw is turned off. 

Which ports does the Airconnect use? It is not only _49152_  as I realized with netstat. 
`
Blurb@Blub:~$ sudo netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:49152           0.0.0.0:*                      LISTEN      19184/airupnp-x86-6 
tcp        0      0 192.168.178.52:46593    0.0.0.0:*               LISTEN      19184/airupnp-x86-6 
tcp        0      0 0.0.0.0:38691           0.0.0.0:*                      LISTEN      19184/airupnp-x86-6 

`

Thanks in Advance

**Comment by philippe44** [comment]
It's fully dynamic ports

**Comment by PeterVanPan** [comment]
Thanks for the fast answer... 

How can accommodate that with UFW ?? damn I'm such a noob

**Comment by philippe44** [comment]
Good - would you mind closing the ticket?

**Comment by PeterVanPan** [comment]
yeah.. sure. sorry

**Comment by velafamily** [comment]
> Thanks for the fast answer...
> 
> How can I accommodate that with UFW ?? damn I'm such a noob
> 
> Edit: found a solution - thanks

What was the solution?

**Comment by AndreasPantle** [comment]
> Thanks for the fast answer...
> 
> How can I accommodate that with UFW ?? damn I'm such a noob
> 
> Edit: found a solution - thanks

Would you share the solution with us please?
