### ISSUE TITLE
Start-parameter for "not searching new devices" and/or setting codec for each device individually

### ISSUE THREAD

**Issue by BayaroX** [philippe44/AirConnect#94]
Hi! First of all, thank you so much for your ingenious work! Finally an AirPlay bridge that works reliably!

But I still have a little problem or request - would it be possible for you to add a start parameter to prevent searching for new devices and only use the devices that are in the config loaded with"-x"?
Background is this - I have 1 device which only works with PCM codec and all others want FLAC. That's why I run AirConnect twice. But if a new device is added, I always have to adjust the Configs (device - enable - 1/0), because otherwise there is confusion.

Or would it be "better" to set a default codec in config which is used for current and new devices (in my case "FLAC") and then make the codec in config individually customizable to pcm/wav for each device?
Something like that, for example:
```
<device>
<udn>uuid:1234567890</udn>
<name>Device XY+</name>
<mac>aa:bb:cc:dd:ee:ff</mac>
<codec>pcm</codec>
<enabled>1</enabled>
</device>
```

I am not sure which variant is "better", either the 2 instances of AirConnect with the possibility to prevent the search for new devices - or the possibility in the config to define the codec for each device individually. Or even both? 

Many thanks in advance and best regards
Chris

**Comment by philippe44** [comment]
Hi - This is already the way it works today. Every option in the common section can occur in device specific section as well and it will take precedence. So in your case, set flac in the common section and just repeat the codec parameter in that specific device section but just set it to pcm

**Comment by BayaroX** [comment]
Oh, embarrassing, I must have skipped that in the readme. I should have taken a look at the sources.
Thank you and best regards
Chris

**Comment by philippe44** [comment]
No worries - the README could be more clear, I’ll update it
