### ISSUE TITLE
Airplay2 compatibility not working with multiple devices

### ISSUE THREAD

**Issue by buzzlulu** [philippe44/AirConnect#97]
Hello
Complete newbie and amateur here.  With that said I was able to install and successfully run this.  My Chromecast Audio device appears under Airplay and can receive music.

With Airplay2 I can stream to multiple Homepods at the same time.  If I try to add the Chromecast device the Homepods cut out and music will only play to the Chromecast.  It appears this will not let me send music to the Chromecast device AND to multiple Homepods at the same time?

It the functionality not possible?

Thanks

**Comment by jpzfm** [comment]
The private key required for AirPlay 2 is not public yet, maybe one day...

**Comment by philippe44** [comment]
It does not works for 2 reasons

- AirConnect only supports AirPlay 1 and I don’t think you can mix 1 and 2 in a group. Airplay 2 protocol specifications are not public
- AirConnect cannot do find timing control of the  Chromecast device that would be required for synchronization. The way to do such control is not documented for CC devices

**Comment by buzzlulu** [comment]
Thank you very much for the reply!
I guess back to hoping Apple will bring Airplay2 capabilities to old Airport Express devices - OR come out with a new Chromecast priced/type device

**Comment by philippe44** [comment]
Or they decide to release they’re spec and Google as well. I could build a bridge then. Fill free to ask to all of them, that my contribution ask: try, legally of course, to CC sync protocol and AP2 specs

**Comment by philippe44** [comment]
Closed for inactivity
