### ISSUE TITLE
Running exe on Windows 10: "This app can't run on your PC"

### ISSUE THREAD

**Issue by snappyfoo** [philippe44/AirConnect#98]
Googling suggests this is due to a SmartScreen filter, which I can't disable. In any case, is it possible to make changes to this app so it is considered safe to run by Windows 10?

Update: 
Found this available on SourceForge and this works. Thank you :)

Although I see my Chromecast Audios listed in the Airplay selector for audio, I'm unable to connect to any. I am using iOS 12 beta though, could this be the issue?

**Comment by philippe44** [comment]
no, it's likely a firewall issue of Win10. You need to enable aircast-win.exe in its firewall

**Comment by philippe44** [comment]
Closed for inactivity
